# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_v_decision/msg_v_decision.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_common.msg
import msg_obj.msg
import msg_safety_diagn.msg

class msg_v_decision(genpy.Message):
  _md5sum = "9972371d5850ca25138bae62dc721d39"
  _type = "msg_v_decision/msg_v_decision"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 task_mode   #(任务类型)前往装载点:10001 前往装载区候车区:10002 前往卸载点:10003 前往卸载候车区:10004 前往停车场停车点:10005 前往停车候车区:10006 取消当前:10007 保持当前任务:10008
uint16 target_id #0保留  1自检  2启动发动机  3静态测试  4待机  5路径跟踪 6路口通行 7路口等待 8卸载...
uint16 task_num	#任务编号
uint16 task_state	#任务状态	0：保留  1：未就绪  2：执行中  3：完成/等待
int32 system_state #(矿卡当前模式状态) 自检:20001 启动发动机:20002 静态测试:20003 轨迹跟随:20004 排队停车:20005 跟车模式:20006 后台轨迹跟随:20007 卸载模式:20008 装载模式:20009 安全停车:20010 关闭发动机:20011 紧急停车:20012 待机:20013 装载完成:20014 后台绕障:20015

msg_obj/Obj[] obj_fuse  	#障碍物信息结构体
msg_obj/Obj[] target_obstacle  #距离自车最近障碍物
float32 dis2front  		#自车与前车距离
float32 distance2vehicle	#车辆与全局路径的最小横向距离差值
float32 distance2obstacle	#目标障碍物最近点最小横向距离差值

msg_safety_diagn/DiagnDataStruct[] fault_info   #故障信息结构体
uint16 event_report #1：车端请求后台局部路径规划 2:车端到达装载点 装载状态切换后触发装载请求事件 3:车端完成卸载任务后出发卸载完成事件
uint8 mode	#(矿卡当前执行的模式)手动：0    自动：1    远程遥控：2
uint8 is_update_map #地图更新情况:0:未更新 1:更新成功 2:拒绝更新
uint32 traj_id
msg_common/WayPoint[] way_point
float32 remote_spd
float32 remote_steering
uint8 remote_parking
uint8 remote_stopengine
uint8 remote_service_brake #行车制动
uint8 remote_park_brake #停车制动
uint8 remote_load_brake #装载制动
uint8 gear_num 		#档位
uint8 carrier_control		#货舱控制信号
uint8 turn_light		#转向灯信号
uint8 dipped_light		#近光灯信号
uint8 marker_light		#示廓灯信号
uint8 emer_light		#紧急信号灯信号
uint8 trumpet			#喇叭信号
bool[] is_clean

================================================================================
MSG: msg_obj/Obj
float64 x #单位m
float64 y #单位m
float64 z #单位m
float32 vx #单位m/s
float32 vy #单位m/s
float32 vz #单位m/s
float32 width #宽度，单位m
float32 length #长度，单位m
float32 height #高度，单位m
#float64 yaw_angle #横摆脚，角度信息，单位为度
uint8 track_state #跟踪状态,0：删除或无效；1：新的；2：测量的；3：预测的；4：待删除；5：待跟踪
uint8 predict_length #预测时长， 单位s
int32 type #障碍物类型, 0:未知；1：汽车；2：卡车；3：行人；4：摩托车；5自行车；6：大障碍物；7：小障碍物； 8：矿坑； 9：灰尘
uint32 type_age #障碍物类型时间长度，单位s
float32 orientation #障碍物形状方位角，单位度，
float32 bbox_yaw
float32 bbox_pitch
float32 bbox_roll
float32 ax #x轴加速度，单位m/s^2
float32 ay #y轴加速度，单位m/s^2
float32 az #z轴加速度，单位m/s^2
msg_common/Covariance cov     #协方差
uint8 type_certainty #障碍物类型确信度 0-100
uint8 obj_certainty #障碍物存在确信度, 0:无效；1：小于0.25；2：小于0.5;3：小于0.75;4：小于0.9;5：小于0.99;6：小于0.999
int8 source #数据来源编号，预设的传感器编号
msg_common/GridPoint[] contour_point #obj对象包含的点信息
uint32 id #跟踪之后给出的最终obj的id
uint8 absolute_motion #绝对的运动状态，0：未知; 1：静止；2：运动
uint8 relative_motion #相对车辆的运动状态，0：静止；1:迎面而来；2：远去；3：横越；4:未知
float32 orientation_rate #方向角速度

================================================================================
MSG: msg_common/Covariance
float32[] value #矩阵值
int8 row #协方差行
int8 col #协方差列
================================================================================
MSG: msg_common/GridPoint
float64 x
float64 y
float64 z
float32 length
float32 width
float32 height
================================================================================
MSG: msg_safety_diagn/DiagnDataStruct
int32 equip_num 
int32 diagn_type
msg_obj/Obj[] obj_state

================================================================================
MSG: msg_common/WayPoint
float64 x			#路径x坐标
float64 y			#路径y坐标
float64 z			#路径z坐标
float64 left			#距左边界值
float64 right			#距右边界值
float32 heading_angle		#路径的方向
float32 curvature		#曲率
float32 speed			#路径的速度
float32 distance		#路点与路径起点沿路径的距离
float32 slope			#坡度信息
uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)
float32 speed_limit	        #速度上限
uint8 direction			#0表示前进，1表示后退
uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点
float64 t			#时间
string area_name		#区域名称	
string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	
"""
  __slots__ = ['task_mode','target_id','task_num','task_state','system_state','obj_fuse','target_obstacle','dis2front','distance2vehicle','distance2obstacle','fault_info','event_report','mode','is_update_map','traj_id','way_point','remote_spd','remote_steering','remote_parking','remote_stopengine','remote_service_brake','remote_park_brake','remote_load_brake','gear_num','carrier_control','turn_light','dipped_light','marker_light','emer_light','trumpet','is_clean']
  _slot_types = ['int32','uint16','uint16','uint16','int32','msg_obj/Obj[]','msg_obj/Obj[]','float32','float32','float32','msg_safety_diagn/DiagnDataStruct[]','uint16','uint8','uint8','uint32','msg_common/WayPoint[]','float32','float32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_mode,target_id,task_num,task_state,system_state,obj_fuse,target_obstacle,dis2front,distance2vehicle,distance2obstacle,fault_info,event_report,mode,is_update_map,traj_id,way_point,remote_spd,remote_steering,remote_parking,remote_stopengine,remote_service_brake,remote_park_brake,remote_load_brake,gear_num,carrier_control,turn_light,dipped_light,marker_light,emer_light,trumpet,is_clean

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_v_decision, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.task_mode is None:
        self.task_mode = 0
      if self.target_id is None:
        self.target_id = 0
      if self.task_num is None:
        self.task_num = 0
      if self.task_state is None:
        self.task_state = 0
      if self.system_state is None:
        self.system_state = 0
      if self.obj_fuse is None:
        self.obj_fuse = []
      if self.target_obstacle is None:
        self.target_obstacle = []
      if self.dis2front is None:
        self.dis2front = 0.
      if self.distance2vehicle is None:
        self.distance2vehicle = 0.
      if self.distance2obstacle is None:
        self.distance2obstacle = 0.
      if self.fault_info is None:
        self.fault_info = []
      if self.event_report is None:
        self.event_report = 0
      if self.mode is None:
        self.mode = 0
      if self.is_update_map is None:
        self.is_update_map = 0
      if self.traj_id is None:
        self.traj_id = 0
      if self.way_point is None:
        self.way_point = []
      if self.remote_spd is None:
        self.remote_spd = 0.
      if self.remote_steering is None:
        self.remote_steering = 0.
      if self.remote_parking is None:
        self.remote_parking = 0
      if self.remote_stopengine is None:
        self.remote_stopengine = 0
      if self.remote_service_brake is None:
        self.remote_service_brake = 0
      if self.remote_park_brake is None:
        self.remote_park_brake = 0
      if self.remote_load_brake is None:
        self.remote_load_brake = 0
      if self.gear_num is None:
        self.gear_num = 0
      if self.carrier_control is None:
        self.carrier_control = 0
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.trumpet is None:
        self.trumpet = 0
      if self.is_clean is None:
        self.is_clean = []
    else:
      self.task_mode = 0
      self.target_id = 0
      self.task_num = 0
      self.task_state = 0
      self.system_state = 0
      self.obj_fuse = []
      self.target_obstacle = []
      self.dis2front = 0.
      self.distance2vehicle = 0.
      self.distance2obstacle = 0.
      self.fault_info = []
      self.event_report = 0
      self.mode = 0
      self.is_update_map = 0
      self.traj_id = 0
      self.way_point = []
      self.remote_spd = 0.
      self.remote_steering = 0.
      self.remote_parking = 0
      self.remote_stopengine = 0
      self.remote_service_brake = 0
      self.remote_park_brake = 0
      self.remote_load_brake = 0
      self.gear_num = 0
      self.carrier_control = 0
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.emer_light = 0
      self.trumpet = 0
      self.is_clean = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i3Hi().pack(_x.task_mode, _x.target_id, _x.task_num, _x.task_state, _x.system_state))
      length = len(self.obj_fuse)
      buff.write(_struct_I.pack(length))
      for val1 in self.obj_fuse:
        _x = val1
        buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
        _v1 = val1.cov
        length = len(_v1.value)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*_v1.value))
        _x = _v1
        buff.write(_get_struct_2b().pack(_x.row, _x.col))
        _x = val1
        buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
        length = len(val1.contour_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.contour_point:
          _x = val2
          buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
        _x = val1
        buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
      length = len(self.target_obstacle)
      buff.write(_struct_I.pack(length))
      for val1 in self.target_obstacle:
        _x = val1
        buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
        _v2 = val1.cov
        length = len(_v2.value)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*_v2.value))
        _x = _v2
        buff.write(_get_struct_2b().pack(_x.row, _x.col))
        _x = val1
        buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
        length = len(val1.contour_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.contour_point:
          _x = val2
          buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
        _x = val1
        buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
      _x = self
      buff.write(_get_struct_3f().pack(_x.dis2front, _x.distance2vehicle, _x.distance2obstacle))
      length = len(self.fault_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.fault_info:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.equip_num, _x.diagn_type))
        length = len(val1.obj_state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.obj_state:
          _x = val2
          buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
          _v3 = val2.cov
          length = len(_v3.value)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(struct.Struct(pattern).pack(*_v3.value))
          _x = _v3
          buff.write(_get_struct_2b().pack(_x.row, _x.col))
          _x = val2
          buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
          length = len(val2.contour_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.contour_point:
            _x = val3
            buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
          _x = val2
          buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
      _x = self
      buff.write(_get_struct_H2BI().pack(_x.event_report, _x.mode, _x.is_update_map, _x.traj_id))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f12B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet))
      length = len(self.is_clean)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.is_clean))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obj_fuse is None:
        self.obj_fuse = None
      if self.target_obstacle is None:
        self.target_obstacle = None
      if self.fault_info is None:
        self.fault_info = None
      if self.way_point is None:
        self.way_point = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.task_mode, _x.target_id, _x.task_num, _x.task_state, _x.system_state,) = _get_struct_i3Hi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obj_fuse = []
      for i in range(0, length):
        val1 = msg_obj.msg.Obj()
        _x = val1
        start = end
        end += 86
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
        _v4 = val1.cov
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v4.value = s.unpack(str[start:end])
        _x = _v4
        start = end
        end += 2
        (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
        _x = val1
        start = end
        end += 3
        (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.contour_point = []
        for i in range(0, length):
          val2 = msg_common.msg.GridPoint()
          _x = val2
          start = end
          end += 36
          (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
          val1.contour_point.append(val2)
        _x = val1
        start = end
        end += 10
        (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
        self.obj_fuse.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.target_obstacle = []
      for i in range(0, length):
        val1 = msg_obj.msg.Obj()
        _x = val1
        start = end
        end += 86
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
        _v5 = val1.cov
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v5.value = s.unpack(str[start:end])
        _x = _v5
        start = end
        end += 2
        (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
        _x = val1
        start = end
        end += 3
        (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.contour_point = []
        for i in range(0, length):
          val2 = msg_common.msg.GridPoint()
          _x = val2
          start = end
          end += 36
          (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
          val1.contour_point.append(val2)
        _x = val1
        start = end
        end += 10
        (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
        self.target_obstacle.append(val1)
      _x = self
      start = end
      end += 12
      (_x.dis2front, _x.distance2vehicle, _x.distance2obstacle,) = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.fault_info = []
      for i in range(0, length):
        val1 = msg_safety_diagn.msg.DiagnDataStruct()
        _x = val1
        start = end
        end += 8
        (_x.equip_num, _x.diagn_type,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.obj_state = []
        for i in range(0, length):
          val2 = msg_obj.msg.Obj()
          _x = val2
          start = end
          end += 86
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
          _v6 = val2.cov
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          _v6.value = s.unpack(str[start:end])
          _x = _v6
          start = end
          end += 2
          (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
          _x = val2
          start = end
          end += 3
          (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.contour_point = []
          for i in range(0, length):
            val3 = msg_common.msg.GridPoint()
            _x = val3
            start = end
            end += 36
            (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
            val2.contour_point.append(val3)
          _x = val2
          start = end
          end += 10
          (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
          val1.obj_state.append(val2)
        self.fault_info.append(val1)
      _x = self
      start = end
      end += 8
      (_x.event_report, _x.mode, _x.is_update_map, _x.traj_id,) = _get_struct_H2BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.way_point.append(val1)
      _x = self
      start = end
      end += 20
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet,) = _get_struct_2f12B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.is_clean = s.unpack(str[start:end])
      self.is_clean = list(map(bool, self.is_clean))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i3Hi().pack(_x.task_mode, _x.target_id, _x.task_num, _x.task_state, _x.system_state))
      length = len(self.obj_fuse)
      buff.write(_struct_I.pack(length))
      for val1 in self.obj_fuse:
        _x = val1
        buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
        _v7 = val1.cov
        length = len(_v7.value)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(_v7.value.tostring())
        _x = _v7
        buff.write(_get_struct_2b().pack(_x.row, _x.col))
        _x = val1
        buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
        length = len(val1.contour_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.contour_point:
          _x = val2
          buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
        _x = val1
        buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
      length = len(self.target_obstacle)
      buff.write(_struct_I.pack(length))
      for val1 in self.target_obstacle:
        _x = val1
        buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
        _v8 = val1.cov
        length = len(_v8.value)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(_v8.value.tostring())
        _x = _v8
        buff.write(_get_struct_2b().pack(_x.row, _x.col))
        _x = val1
        buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
        length = len(val1.contour_point)
        buff.write(_struct_I.pack(length))
        for val2 in val1.contour_point:
          _x = val2
          buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
        _x = val1
        buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
      _x = self
      buff.write(_get_struct_3f().pack(_x.dis2front, _x.distance2vehicle, _x.distance2obstacle))
      length = len(self.fault_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.fault_info:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.equip_num, _x.diagn_type))
        length = len(val1.obj_state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.obj_state:
          _x = val2
          buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
          _v9 = val2.cov
          length = len(_v9.value)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(_v9.value.tostring())
          _x = _v9
          buff.write(_get_struct_2b().pack(_x.row, _x.col))
          _x = val2
          buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
          length = len(val2.contour_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.contour_point:
            _x = val3
            buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
          _x = val2
          buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
      _x = self
      buff.write(_get_struct_H2BI().pack(_x.event_report, _x.mode, _x.is_update_map, _x.traj_id))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f12B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet))
      length = len(self.is_clean)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.is_clean.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obj_fuse is None:
        self.obj_fuse = None
      if self.target_obstacle is None:
        self.target_obstacle = None
      if self.fault_info is None:
        self.fault_info = None
      if self.way_point is None:
        self.way_point = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.task_mode, _x.target_id, _x.task_num, _x.task_state, _x.system_state,) = _get_struct_i3Hi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obj_fuse = []
      for i in range(0, length):
        val1 = msg_obj.msg.Obj()
        _x = val1
        start = end
        end += 86
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
        _v10 = val1.cov
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v10.value = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        _x = _v10
        start = end
        end += 2
        (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
        _x = val1
        start = end
        end += 3
        (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.contour_point = []
        for i in range(0, length):
          val2 = msg_common.msg.GridPoint()
          _x = val2
          start = end
          end += 36
          (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
          val1.contour_point.append(val2)
        _x = val1
        start = end
        end += 10
        (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
        self.obj_fuse.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.target_obstacle = []
      for i in range(0, length):
        val1 = msg_obj.msg.Obj()
        _x = val1
        start = end
        end += 86
        (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
        _v11 = val1.cov
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v11.value = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        _x = _v11
        start = end
        end += 2
        (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
        _x = val1
        start = end
        end += 3
        (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.contour_point = []
        for i in range(0, length):
          val2 = msg_common.msg.GridPoint()
          _x = val2
          start = end
          end += 36
          (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
          val1.contour_point.append(val2)
        _x = val1
        start = end
        end += 10
        (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
        self.target_obstacle.append(val1)
      _x = self
      start = end
      end += 12
      (_x.dis2front, _x.distance2vehicle, _x.distance2obstacle,) = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.fault_info = []
      for i in range(0, length):
        val1 = msg_safety_diagn.msg.DiagnDataStruct()
        _x = val1
        start = end
        end += 8
        (_x.equip_num, _x.diagn_type,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.obj_state = []
        for i in range(0, length):
          val2 = msg_obj.msg.Obj()
          _x = val2
          start = end
          end += 86
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
          _v12 = val2.cov
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          _v12.value = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
          _x = _v12
          start = end
          end += 2
          (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
          _x = val2
          start = end
          end += 3
          (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.contour_point = []
          for i in range(0, length):
            val3 = msg_common.msg.GridPoint()
            _x = val3
            start = end
            end += 36
            (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
            val2.contour_point.append(val3)
          _x = val2
          start = end
          end += 10
          (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
          val1.obj_state.append(val2)
        self.fault_info.append(val1)
      _x = self
      start = end
      end += 8
      (_x.event_report, _x.mode, _x.is_update_map, _x.traj_id,) = _get_struct_H2BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.way_point.append(val1)
      _x = self
      start = end
      end += 20
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet,) = _get_struct_2f12B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.is_clean = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.is_clean = list(map(bool, self.is_clean))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bb = None
def _get_struct_2Bb():
    global _struct_2Bb
    if _struct_2Bb is None:
        _struct_2Bb = struct.Struct("<2Bb")
    return _struct_2Bb
_struct_2b = None
def _get_struct_2b():
    global _struct_2b
    if _struct_2b is None:
        _struct_2b = struct.Struct("<2b")
    return _struct_2b
_struct_2f12B = None
def _get_struct_2f12B():
    global _struct_2f12B
    if _struct_2f12B is None:
        _struct_2f12B = struct.Struct("<2f12B")
    return _struct_2f12B
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_3d3f = None
def _get_struct_3d3f():
    global _struct_3d3f
    if _struct_3d3f is None:
        _struct_3d3f = struct.Struct("<3d3f")
    return _struct_3d3f
_struct_3d6f2BiI7f = None
def _get_struct_3d6f2BiI7f():
    global _struct_3d6f2BiI7f
    if _struct_3d6f2BiI7f is None:
        _struct_3d6f2BiI7f = struct.Struct("<3d6f2BiI7f")
    return _struct_3d6f2BiI7f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_5d5fIf2Bd = None
def _get_struct_5d5fIf2Bd():
    global _struct_5d5fIf2Bd
    if _struct_5d5fIf2Bd is None:
        _struct_5d5fIf2Bd = struct.Struct("<5d5fIf2Bd")
    return _struct_5d5fIf2Bd
_struct_H2BI = None
def _get_struct_H2BI():
    global _struct_H2BI
    if _struct_H2BI is None:
        _struct_H2BI = struct.Struct("<H2BI")
    return _struct_H2BI
_struct_I2Bf = None
def _get_struct_I2Bf():
    global _struct_I2Bf
    if _struct_I2Bf is None:
        _struct_I2Bf = struct.Struct("<I2Bf")
    return _struct_I2Bf
_struct_i3Hi = None
def _get_struct_i3Hi():
    global _struct_i3Hi
    if _struct_i3Hi is None:
        _struct_i3Hi = struct.Struct("<i3Hi")
    return _struct_i3Hi
