# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_v_state/msg_v_state.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class msg_v_state(genpy.Message):
  _md5sum = "aa6af63a1ba367c32483e9b79096ee80"
  _type = "msg_v_state/msg_v_state"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header   header         # ROS time header
uint8    gps_status
int32    gps_week
float64  gps_time
float64  longitude            
float64  latitude
float64  altitude
float64  x
float64  y
float64  z
float32  heading_angle
float32  yaw_angle
float32  yaw_rate
float32  pitch_angle
float32  pitch_rate
float32  roll_angle
float32  roll_rate
float32  spd_east
float32  spd_north
float32  spd_up
float32  spd 
float32  spd_lon
float32  spd_lat
float32  acce
float32  acce_lon
float32  acce_lat
char static_check                 # 0:no commend; 1: checking; 2: pass check; 4: check failed
uint8 auto_status_mode		   	   # 自动驾驶模式: 0,手动;1,自动
uint8 auto_status_ready		   # 自动驾驶状态准备：0,未就绪;1,就绪
uint8 auto_status_intervene		   # 自动驾驶状态下有刹车介入：0,无介入;1,有介入
float32 speed			           # 底层提供的车速
float64 steering_angle		   # 实际车轮转角
uint8 steer_control_status	           # 转向控制器状态：0, 待机； 1,自动驾驶模式;4,手动模式;5,驾驶员介入模式
float64 steering_spd
float32 wheel_angle
float32 target_steering_angle
float32 trq
float32 target_trq
float32 thr_angle			   # 实际油门开度
uint8 gear_num			           # 实际档位：0,P;1,R;2,D;3,N
uint8 emerg_state			   # 紧急制动状态
float32 braking_dece		           # 制动减速度
float64 fuel_num			   # 燃油状态（剩余油量）
uint8 park_brk			           # 驻车制动状态： 0, 无驻车制动;1, 在驻车制动中
float32 carrier_angle		           # 货舱举升角度
uint8 turn_light			   # 转向灯状态
uint8 dipped_light			   # 远、近光灯状态
uint8 marker_light			   # 示廓灯/前雾灯状态
uint8 brake_light			   # 刹车灯状态
uint8 emer_light			   # 紧急信号灯状态
uint8 backup_light 		           # 倒车灯信号
uint8 position_light		           # 位置灯信号
uint8 carrire_warm_light		   # 举升警告灯信号
uint8 illumination_light		   # 照明灯信号
uint8 trumpet			           # 喇叭信号
uint8 pto_status                    #取力器使能状态
uint8 brim_state                    #帽檐举升状态
bool[] clean_status              # 传感器状态
bool switch_status		  #自动驾驶开关状态：0：关闭 1：打开

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','gps_status','gps_week','gps_time','longitude','latitude','altitude','x','y','z','heading_angle','yaw_angle','yaw_rate','pitch_angle','pitch_rate','roll_angle','roll_rate','spd_east','spd_north','spd_up','spd','spd_lon','spd_lat','acce','acce_lon','acce_lat','static_check','auto_status_mode','auto_status_ready','auto_status_intervene','speed','steering_angle','steer_control_status','steering_spd','wheel_angle','target_steering_angle','trq','target_trq','thr_angle','gear_num','emerg_state','braking_dece','fuel_num','park_brk','carrier_angle','turn_light','dipped_light','marker_light','brake_light','emer_light','backup_light','position_light','carrire_warm_light','illumination_light','trumpet','pto_status','brim_state','clean_status','switch_status']
  _slot_types = ['std_msgs/Header','uint8','int32','float64','float64','float64','float64','float64','float64','float64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','char','uint8','uint8','uint8','float32','float64','uint8','float64','float32','float32','float32','float32','float32','uint8','uint8','float32','float64','uint8','float32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','bool[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gps_status,gps_week,gps_time,longitude,latitude,altitude,x,y,z,heading_angle,yaw_angle,yaw_rate,pitch_angle,pitch_rate,roll_angle,roll_rate,spd_east,spd_north,spd_up,spd,spd_lon,spd_lat,acce,acce_lon,acce_lat,static_check,auto_status_mode,auto_status_ready,auto_status_intervene,speed,steering_angle,steer_control_status,steering_spd,wheel_angle,target_steering_angle,trq,target_trq,thr_angle,gear_num,emerg_state,braking_dece,fuel_num,park_brk,carrier_angle,turn_light,dipped_light,marker_light,brake_light,emer_light,backup_light,position_light,carrire_warm_light,illumination_light,trumpet,pto_status,brim_state,clean_status,switch_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_v_state, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gps_status is None:
        self.gps_status = 0
      if self.gps_week is None:
        self.gps_week = 0
      if self.gps_time is None:
        self.gps_time = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.heading_angle is None:
        self.heading_angle = 0.
      if self.yaw_angle is None:
        self.yaw_angle = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.pitch_angle is None:
        self.pitch_angle = 0.
      if self.pitch_rate is None:
        self.pitch_rate = 0.
      if self.roll_angle is None:
        self.roll_angle = 0.
      if self.roll_rate is None:
        self.roll_rate = 0.
      if self.spd_east is None:
        self.spd_east = 0.
      if self.spd_north is None:
        self.spd_north = 0.
      if self.spd_up is None:
        self.spd_up = 0.
      if self.spd is None:
        self.spd = 0.
      if self.spd_lon is None:
        self.spd_lon = 0.
      if self.spd_lat is None:
        self.spd_lat = 0.
      if self.acce is None:
        self.acce = 0.
      if self.acce_lon is None:
        self.acce_lon = 0.
      if self.acce_lat is None:
        self.acce_lat = 0.
      if self.static_check is None:
        self.static_check = 0
      if self.auto_status_mode is None:
        self.auto_status_mode = 0
      if self.auto_status_ready is None:
        self.auto_status_ready = 0
      if self.auto_status_intervene is None:
        self.auto_status_intervene = 0
      if self.speed is None:
        self.speed = 0.
      if self.steering_angle is None:
        self.steering_angle = 0.
      if self.steer_control_status is None:
        self.steer_control_status = 0
      if self.steering_spd is None:
        self.steering_spd = 0.
      if self.wheel_angle is None:
        self.wheel_angle = 0.
      if self.target_steering_angle is None:
        self.target_steering_angle = 0.
      if self.trq is None:
        self.trq = 0.
      if self.target_trq is None:
        self.target_trq = 0.
      if self.thr_angle is None:
        self.thr_angle = 0.
      if self.gear_num is None:
        self.gear_num = 0
      if self.emerg_state is None:
        self.emerg_state = 0
      if self.braking_dece is None:
        self.braking_dece = 0.
      if self.fuel_num is None:
        self.fuel_num = 0.
      if self.park_brk is None:
        self.park_brk = 0
      if self.carrier_angle is None:
        self.carrier_angle = 0.
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.brake_light is None:
        self.brake_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.backup_light is None:
        self.backup_light = 0
      if self.position_light is None:
        self.position_light = 0
      if self.carrire_warm_light is None:
        self.carrire_warm_light = 0
      if self.illumination_light is None:
        self.illumination_light = 0
      if self.trumpet is None:
        self.trumpet = 0
      if self.pto_status is None:
        self.pto_status = 0
      if self.brim_state is None:
        self.brim_state = 0
      if self.clean_status is None:
        self.clean_status = []
      if self.switch_status is None:
        self.switch_status = False
    else:
      self.header = std_msgs.msg.Header()
      self.gps_status = 0
      self.gps_week = 0
      self.gps_time = 0.
      self.longitude = 0.
      self.latitude = 0.
      self.altitude = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.heading_angle = 0.
      self.yaw_angle = 0.
      self.yaw_rate = 0.
      self.pitch_angle = 0.
      self.pitch_rate = 0.
      self.roll_angle = 0.
      self.roll_rate = 0.
      self.spd_east = 0.
      self.spd_north = 0.
      self.spd_up = 0.
      self.spd = 0.
      self.spd_lon = 0.
      self.spd_lat = 0.
      self.acce = 0.
      self.acce_lon = 0.
      self.acce_lat = 0.
      self.static_check = 0
      self.auto_status_mode = 0
      self.auto_status_ready = 0
      self.auto_status_intervene = 0
      self.speed = 0.
      self.steering_angle = 0.
      self.steer_control_status = 0
      self.steering_spd = 0.
      self.wheel_angle = 0.
      self.target_steering_angle = 0.
      self.trq = 0.
      self.target_trq = 0.
      self.thr_angle = 0.
      self.gear_num = 0
      self.emerg_state = 0
      self.braking_dece = 0.
      self.fuel_num = 0.
      self.park_brk = 0
      self.carrier_angle = 0.
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.brake_light = 0
      self.emer_light = 0
      self.backup_light = 0
      self.position_light = 0
      self.carrire_warm_light = 0
      self.illumination_light = 0
      self.trumpet = 0
      self.pto_status = 0
      self.brim_state = 0
      self.clean_status = []
      self.switch_status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi7d16f4BfdBd5f2BfdBf12B().pack(_x.gps_status, _x.gps_week, _x.gps_time, _x.longitude, _x.latitude, _x.altitude, _x.x, _x.y, _x.z, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.pitch_rate, _x.roll_angle, _x.roll_rate, _x.spd_east, _x.spd_north, _x.spd_up, _x.spd, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.static_check, _x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle, _x.steer_control_status, _x.steering_spd, _x.wheel_angle, _x.target_steering_angle, _x.trq, _x.target_trq, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet, _x.pto_status, _x.brim_state))
      length = len(self.clean_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.clean_status))
      _x = self.switch_status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 201
      (_x.gps_status, _x.gps_week, _x.gps_time, _x.longitude, _x.latitude, _x.altitude, _x.x, _x.y, _x.z, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.pitch_rate, _x.roll_angle, _x.roll_rate, _x.spd_east, _x.spd_north, _x.spd_up, _x.spd, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.static_check, _x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle, _x.steer_control_status, _x.steering_spd, _x.wheel_angle, _x.target_steering_angle, _x.trq, _x.target_trq, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet, _x.pto_status, _x.brim_state,) = _get_struct_Bi7d16f4BfdBd5f2BfdBf12B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.clean_status = s.unpack(str[start:end])
      self.clean_status = list(map(bool, self.clean_status))
      start = end
      end += 1
      (self.switch_status,) = _get_struct_B().unpack(str[start:end])
      self.switch_status = bool(self.switch_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi7d16f4BfdBd5f2BfdBf12B().pack(_x.gps_status, _x.gps_week, _x.gps_time, _x.longitude, _x.latitude, _x.altitude, _x.x, _x.y, _x.z, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.pitch_rate, _x.roll_angle, _x.roll_rate, _x.spd_east, _x.spd_north, _x.spd_up, _x.spd, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.static_check, _x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle, _x.steer_control_status, _x.steering_spd, _x.wheel_angle, _x.target_steering_angle, _x.trq, _x.target_trq, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet, _x.pto_status, _x.brim_state))
      length = len(self.clean_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.clean_status.tostring())
      _x = self.switch_status
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 201
      (_x.gps_status, _x.gps_week, _x.gps_time, _x.longitude, _x.latitude, _x.altitude, _x.x, _x.y, _x.z, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.pitch_rate, _x.roll_angle, _x.roll_rate, _x.spd_east, _x.spd_north, _x.spd_up, _x.spd, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.static_check, _x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle, _x.steer_control_status, _x.steering_spd, _x.wheel_angle, _x.target_steering_angle, _x.trq, _x.target_trq, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet, _x.pto_status, _x.brim_state,) = _get_struct_Bi7d16f4BfdBd5f2BfdBf12B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.clean_status = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.clean_status = list(map(bool, self.clean_status))
      start = end
      end += 1
      (self.switch_status,) = _get_struct_B().unpack(str[start:end])
      self.switch_status = bool(self.switch_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_Bi7d16f4BfdBd5f2BfdBf12B = None
def _get_struct_Bi7d16f4BfdBd5f2BfdBf12B():
    global _struct_Bi7d16f4BfdBd5f2BfdBf12B
    if _struct_Bi7d16f4BfdBd5f2BfdBf12B is None:
        _struct_Bi7d16f4BfdBd5f2BfdBf12B = struct.Struct("<Bi7d16f4BfdBd5f2BfdBf12B")
    return _struct_Bi7d16f4BfdBd5f2BfdBf12B
