(cl:in-package msg_global_planning-msg)
(cl:export '(TARGET_ID-VAL
          TARGET_ID
          WAY_POINT-VAL
          WAY_POINT
          REMOTE_SPD-VAL
          REMOTE_SPD
          REMOTE_STEERING-VAL
          REMOTE_STEERING
          REMOTE_PARKING-VAL
          REMOTE_PARKING
          TRAJ_ID-VAL
          TRAJ_ID
          GEAR_NUM-VAL
          GEAR_NUM
          CARRIER_CONTROL-VAL
          CARRIER_CONTROL
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          TRUMPET-VAL
          TRUMPET
          PATH_ARRAY-VAL
          PATH_ARRAY
))