(cl:in-package msg_obj-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          WIDTH-VAL
          WIDTH
          LENGTH-VAL
          LENGTH
          HEIGHT-VAL
          HEIGHT
          TRACK_STATE-VAL
          TRACK_STATE
          PREDICT_LENGTH-VAL
          PREDICT_LENGTH
          TYPE-VAL
          TYPE
          TYPE_AGE-VAL
          TYPE_AGE
          ORIENTATION-VAL
          ORIENTATION
          BBOX_YAW-VAL
          BBOX_YAW
          BBOX_PITCH-VAL
          BBOX_PITCH
          BBOX_ROLL-VAL
          BBOX_ROLL
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          COV-VAL
          COV
          TYPE_CERTAINTY-VAL
          TYPE_CERTAINTY
          OBJ_CERTAINTY-VAL
          OBJ_CERTAINTY
          SOURCE-VAL
          SOURCE
          CONTOUR_POINT-VAL
          CONTOUR_POINT
          ID-VAL
          ID
          ABSOLUTE_MOTION-VAL
          ABSOLUTE_MOTION
          RELATIVE_MOTION-VAL
          RELATIVE_MOTION
          ORIENTATION_RATE-VAL
          ORIENTATION_RATE
))