# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_v_prep/msg_v_prep.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class msg_v_prep(genpy.Message):
  _md5sum = "7290758742e9103ad10d343f24df155c"
  _type = "msg_v_prep/msg_v_prep"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 auto_status_mode		   	   # 自动驾驶模式: 0,手动;1,自动
uint8 auto_status_ready		   # 自动驾驶状态准备：0,未就绪;1,就绪
uint8 auto_status_intervene		   # 自动驾驶状态下有刹车介入：0,无介入;1,有介入
float32 speed			           # 底层提供的车速
float64 steering_angle_left		   # 实际车轮转角
float64 steering_angle_right	           # 实际车轮转角
uint8 steer_control_status	           # 转向控制器状态：0, 待机； 1,自动驾驶模式; 2~3保留;4,手动模式;5,驾驶员介入模式;6,警告模式；警告系统还在工作，有电助力，自动驾驶不执行; 7, 错误模式；错误模式，故障比较严重，系统停止工作；
float32 thr_angle			   # 实际油门开度
uint8 gear_num			           # 实际档位：0,P;1,R;2,D;3,N
uint8 emerg_state			   # 紧急制动状态
float32 braking_dece		           # 制动减速度
float64 fuel_num			   # 燃油状态（剩余油量）
uint8 park_brk			           # 驻车制动状态： 0, 无驻车制动;1, 在驻车制动中
float32 carrier_angle		           # 货舱举升角度
uint8 turn_light			   # 转向灯状态
uint8 dipped_light			   # 远、近光灯状态
uint8 marker_light			   # 示廓灯/前雾灯状态
uint8 brake_light			   # 刹车灯状态
uint8 emer_light			   # 紧急信号灯状态
uint8 backup_light 		           # 倒车灯信号
uint8 position_light		           # 位置灯信号
uint8 carrire_warm_light		   # 举升警告灯信号
uint8 illumination_light		   # 照明灯信号
uint8 trumpet			           # 喇叭信号








"""
  __slots__ = ['auto_status_mode','auto_status_ready','auto_status_intervene','speed','steering_angle_left','steering_angle_right','steer_control_status','thr_angle','gear_num','emerg_state','braking_dece','fuel_num','park_brk','carrier_angle','turn_light','dipped_light','marker_light','brake_light','emer_light','backup_light','position_light','carrire_warm_light','illumination_light','trumpet']
  _slot_types = ['uint8','uint8','uint8','float32','float64','float64','uint8','float32','uint8','uint8','float32','float64','uint8','float32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       auto_status_mode,auto_status_ready,auto_status_intervene,speed,steering_angle_left,steering_angle_right,steer_control_status,thr_angle,gear_num,emerg_state,braking_dece,fuel_num,park_brk,carrier_angle,turn_light,dipped_light,marker_light,brake_light,emer_light,backup_light,position_light,carrire_warm_light,illumination_light,trumpet

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_v_prep, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.auto_status_mode is None:
        self.auto_status_mode = 0
      if self.auto_status_ready is None:
        self.auto_status_ready = 0
      if self.auto_status_intervene is None:
        self.auto_status_intervene = 0
      if self.speed is None:
        self.speed = 0.
      if self.steering_angle_left is None:
        self.steering_angle_left = 0.
      if self.steering_angle_right is None:
        self.steering_angle_right = 0.
      if self.steer_control_status is None:
        self.steer_control_status = 0
      if self.thr_angle is None:
        self.thr_angle = 0.
      if self.gear_num is None:
        self.gear_num = 0
      if self.emerg_state is None:
        self.emerg_state = 0
      if self.braking_dece is None:
        self.braking_dece = 0.
      if self.fuel_num is None:
        self.fuel_num = 0.
      if self.park_brk is None:
        self.park_brk = 0
      if self.carrier_angle is None:
        self.carrier_angle = 0.
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.brake_light is None:
        self.brake_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.backup_light is None:
        self.backup_light = 0
      if self.position_light is None:
        self.position_light = 0
      if self.carrire_warm_light is None:
        self.carrire_warm_light = 0
      if self.illumination_light is None:
        self.illumination_light = 0
      if self.trumpet is None:
        self.trumpet = 0
    else:
      self.auto_status_mode = 0
      self.auto_status_ready = 0
      self.auto_status_intervene = 0
      self.speed = 0.
      self.steering_angle_left = 0.
      self.steering_angle_right = 0.
      self.steer_control_status = 0
      self.thr_angle = 0.
      self.gear_num = 0
      self.emerg_state = 0
      self.braking_dece = 0.
      self.fuel_num = 0.
      self.park_brk = 0
      self.carrier_angle = 0.
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.brake_light = 0
      self.emer_light = 0
      self.backup_light = 0
      self.position_light = 0
      self.carrire_warm_light = 0
      self.illumination_light = 0
      self.trumpet = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3Bf2dBf2BfdBf10B().pack(_x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle_left, _x.steering_angle_right, _x.steer_control_status, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 57
      (_x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle_left, _x.steering_angle_right, _x.steer_control_status, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet,) = _get_struct_3Bf2dBf2BfdBf10B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3Bf2dBf2BfdBf10B().pack(_x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle_left, _x.steering_angle_right, _x.steer_control_status, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 57
      (_x.auto_status_mode, _x.auto_status_ready, _x.auto_status_intervene, _x.speed, _x.steering_angle_left, _x.steering_angle_right, _x.steer_control_status, _x.thr_angle, _x.gear_num, _x.emerg_state, _x.braking_dece, _x.fuel_num, _x.park_brk, _x.carrier_angle, _x.turn_light, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.illumination_light, _x.trumpet,) = _get_struct_3Bf2dBf2BfdBf10B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3Bf2dBf2BfdBf10B = None
def _get_struct_3Bf2dBf2BfdBf10B():
    global _struct_3Bf2dBf2BfdBf10B
    if _struct_3Bf2dBf2BfdBf10B is None:
        _struct_3Bf2dBf2BfdBf10B = struct.Struct("<3Bf2dBf2BfdBf10B")
    return _struct_3Bf2dBf2BfdBf10B
