# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_v_prep/msg_diagn_v_prep.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_common.msg
import msg_obj.msg
import msg_safety_diagn.msg

class msg_diagn_v_prep(genpy.Message):
  _md5sum = "52a665b88860c4a92dcb2fd94f5446ee"
  _type = "msg_v_prep/msg_diagn_v_prep"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 diagn_num 
msg_safety_diagn/DiagnDataStruct[] diagn_data

================================================================================
MSG: msg_safety_diagn/DiagnDataStruct
int32 equip_num 
int32 diagn_type
msg_obj/Obj[] obj_state

================================================================================
MSG: msg_obj/Obj
float64 x #单位m
float64 y #单位m
float64 z #单位m
float32 vx #单位m/s
float32 vy #单位m/s
float32 vz #单位m/s
float32 width #宽度，单位m
float32 length #长度，单位m
float32 height #高度，单位m
#float64 yaw_angle #横摆脚，角度信息，单位为度
uint8 track_state #跟踪状态,0：删除或无效；1：新的；2：测量的；3：预测的；4：待删除；5：待跟踪
uint8 predict_length #预测时长， 单位s
int32 type #障碍物类型, 0:未知；1：汽车；2：卡车；3：行人；4：摩托车；5自行车；6：大障碍物；7：小障碍物； 8：矿坑； 9：灰尘
uint32 type_age #障碍物类型时间长度，单位s
float32 orientation #障碍物形状方位角，单位度，
float32 bbox_yaw
float32 bbox_pitch
float32 bbox_roll
float32 ax #x轴加速度，单位m/s^2
float32 ay #y轴加速度，单位m/s^2
float32 az #z轴加速度，单位m/s^2
msg_common/Covariance cov     #协方差
uint8 type_certainty #障碍物类型确信度 0-100
uint8 obj_certainty #障碍物存在确信度, 0:无效；1：小于0.25；2：小于0.5;3：小于0.75;4：小于0.9;5：小于0.99;6：小于0.999
int8 source #数据来源编号，预设的传感器编号
msg_common/GridPoint[] contour_point #obj对象包含的点信息
uint32 id #跟踪之后给出的最终obj的id
uint8 absolute_motion #绝对的运动状态，0：未知; 1：静止；2：运动
uint8 relative_motion #相对车辆的运动状态，0：静止；1:迎面而来；2：远去；3：横越；4:未知
float32 orientation_rate #方向角速度

================================================================================
MSG: msg_common/Covariance
float32[] value #矩阵值
int8 row #协方差行
int8 col #协方差列
================================================================================
MSG: msg_common/GridPoint
float64 x
float64 y
float64 z
float32 length
float32 width
float32 height"""
  __slots__ = ['diagn_num','diagn_data']
  _slot_types = ['int32','msg_safety_diagn/DiagnDataStruct[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       diagn_num,diagn_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_diagn_v_prep, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.diagn_num is None:
        self.diagn_num = 0
      if self.diagn_data is None:
        self.diagn_data = []
    else:
      self.diagn_num = 0
      self.diagn_data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.diagn_num
      buff.write(_get_struct_i().pack(_x))
      length = len(self.diagn_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.diagn_data:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.equip_num, _x.diagn_type))
        length = len(val1.obj_state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.obj_state:
          _x = val2
          buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
          _v1 = val2.cov
          length = len(_v1.value)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(struct.Struct(pattern).pack(*_v1.value))
          _x = _v1
          buff.write(_get_struct_2b().pack(_x.row, _x.col))
          _x = val2
          buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
          length = len(val2.contour_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.contour_point:
            _x = val3
            buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
          _x = val2
          buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.diagn_data is None:
        self.diagn_data = None
      end = 0
      start = end
      end += 4
      (self.diagn_num,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.diagn_data = []
      for i in range(0, length):
        val1 = msg_safety_diagn.msg.DiagnDataStruct()
        _x = val1
        start = end
        end += 8
        (_x.equip_num, _x.diagn_type,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.obj_state = []
        for i in range(0, length):
          val2 = msg_obj.msg.Obj()
          _x = val2
          start = end
          end += 86
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
          _v2 = val2.cov
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          _v2.value = s.unpack(str[start:end])
          _x = _v2
          start = end
          end += 2
          (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
          _x = val2
          start = end
          end += 3
          (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.contour_point = []
          for i in range(0, length):
            val3 = msg_common.msg.GridPoint()
            _x = val3
            start = end
            end += 36
            (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
            val2.contour_point.append(val3)
          _x = val2
          start = end
          end += 10
          (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
          val1.obj_state.append(val2)
        self.diagn_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.diagn_num
      buff.write(_get_struct_i().pack(_x))
      length = len(self.diagn_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.diagn_data:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.equip_num, _x.diagn_type))
        length = len(val1.obj_state)
        buff.write(_struct_I.pack(length))
        for val2 in val1.obj_state:
          _x = val2
          buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
          _v3 = val2.cov
          length = len(_v3.value)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(_v3.value.tostring())
          _x = _v3
          buff.write(_get_struct_2b().pack(_x.row, _x.col))
          _x = val2
          buff.write(_get_struct_2Bb().pack(_x.type_certainty, _x.obj_certainty, _x.source))
          length = len(val2.contour_point)
          buff.write(_struct_I.pack(length))
          for val3 in val2.contour_point:
            _x = val3
            buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
          _x = val2
          buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.diagn_data is None:
        self.diagn_data = None
      end = 0
      start = end
      end += 4
      (self.diagn_num,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.diagn_data = []
      for i in range(0, length):
        val1 = msg_safety_diagn.msg.DiagnDataStruct()
        _x = val1
        start = end
        end += 8
        (_x.equip_num, _x.diagn_type,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.obj_state = []
        for i in range(0, length):
          val2 = msg_obj.msg.Obj()
          _x = val2
          start = end
          end += 86
          (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
          _v4 = val2.cov
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          _v4.value = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
          _x = _v4
          start = end
          end += 2
          (_x.row, _x.col,) = _get_struct_2b().unpack(str[start:end])
          _x = val2
          start = end
          end += 3
          (_x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2Bb().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          val2.contour_point = []
          for i in range(0, length):
            val3 = msg_common.msg.GridPoint()
            _x = val3
            start = end
            end += 36
            (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
            val2.contour_point.append(val3)
          _x = val2
          start = end
          end += 10
          (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
          val1.obj_state.append(val2)
        self.diagn_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bb = None
def _get_struct_2Bb():
    global _struct_2Bb
    if _struct_2Bb is None:
        _struct_2Bb = struct.Struct("<2Bb")
    return _struct_2Bb
_struct_2b = None
def _get_struct_2b():
    global _struct_2b
    if _struct_2b is None:
        _struct_2b = struct.Struct("<2b")
    return _struct_2b
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_3d3f = None
def _get_struct_3d3f():
    global _struct_3d3f
    if _struct_3d3f is None:
        _struct_3d3f = struct.Struct("<3d3f")
    return _struct_3d3f
_struct_3d6f2BiI7f = None
def _get_struct_3d6f2BiI7f():
    global _struct_3d6f2BiI7f
    if _struct_3d6f2BiI7f is None:
        _struct_3d6f2BiI7f = struct.Struct("<3d6f2BiI7f")
    return _struct_3d6f2BiI7f
_struct_I2Bf = None
def _get_struct_I2Bf():
    global _struct_I2Bf
    if _struct_I2Bf is None:
        _struct_I2Bf = struct.Struct("<I2Bf")
    return _struct_I2Bf
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
