// Generated by gencpp from file msg_info_router/msg_info_router.msg
// DO NOT EDIT!


#ifndef MSG_INFO_ROUTER_MESSAGE_MSG_INFO_ROUTER_H
#define MSG_INFO_ROUTER_MESSAGE_MSG_INFO_ROUTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_common/WayPoint.h>
#include <msg_info_router/Point.h>

namespace msg_info_router
{
template <class ContainerAllocator>
struct msg_info_router_
{
  typedef msg_info_router_<ContainerAllocator> Type;

  msg_info_router_()
    : mode(0)
    , task_type(0)
    , task_num(0)
    , segments_num(0)
    , cur_segments_num(0)
    , state_type(0)
    , path_point()
    , stop_point()
    , is_update_map(false)
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0.0)
    , remote_stopengine(0)
    , remote_service_brake(0)
    , remote_park_brake(0)
    , remote_load_brake(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , fog_light(0)
    , brake_light(0)
    , emer_light(0)
    , wiper_sign(0)
    , trumpet(0)  {
    }
  msg_info_router_(const ContainerAllocator& _alloc)
    : mode(0)
    , task_type(0)
    , task_num(0)
    , segments_num(0)
    , cur_segments_num(0)
    , state_type(0)
    , path_point(_alloc)
    , stop_point(_alloc)
    , is_update_map(false)
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0.0)
    , remote_stopengine(0)
    , remote_service_brake(0)
    , remote_park_brake(0)
    , remote_load_brake(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , fog_light(0)
    , brake_light(0)
    , emer_light(0)
    , wiper_sign(0)
    , trumpet(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint16_t _task_type_type;
  _task_type_type task_type;

   typedef uint16_t _task_num_type;
  _task_num_type task_num;

   typedef uint16_t _segments_num_type;
  _segments_num_type segments_num;

   typedef uint16_t _cur_segments_num_type;
  _cur_segments_num_type cur_segments_num;

   typedef uint16_t _state_type_type;
  _state_type_type state_type;

   typedef std::vector< ::msg_common::WayPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_common::WayPoint_<ContainerAllocator> >> _path_point_type;
  _path_point_type path_point;

   typedef  ::msg_info_router::Point_<ContainerAllocator>  _stop_point_type;
  _stop_point_type stop_point;

   typedef uint8_t _is_update_map_type;
  _is_update_map_type is_update_map;

   typedef float _remote_spd_type;
  _remote_spd_type remote_spd;

   typedef float _remote_steering_type;
  _remote_steering_type remote_steering;

   typedef float _remote_parking_type;
  _remote_parking_type remote_parking;

   typedef uint8_t _remote_stopengine_type;
  _remote_stopengine_type remote_stopengine;

   typedef uint8_t _remote_service_brake_type;
  _remote_service_brake_type remote_service_brake;

   typedef uint8_t _remote_park_brake_type;
  _remote_park_brake_type remote_park_brake;

   typedef uint8_t _remote_load_brake_type;
  _remote_load_brake_type remote_load_brake;

   typedef uint8_t _gear_num_type;
  _gear_num_type gear_num;

   typedef uint8_t _carrier_control_type;
  _carrier_control_type carrier_control;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _fog_light_type;
  _fog_light_type fog_light;

   typedef uint8_t _brake_light_type;
  _brake_light_type brake_light;

   typedef uint8_t _emer_light_type;
  _emer_light_type emer_light;

   typedef uint8_t _wiper_sign_type;
  _wiper_sign_type wiper_sign;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;





  typedef boost::shared_ptr< ::msg_info_router::msg_info_router_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_info_router::msg_info_router_<ContainerAllocator> const> ConstPtr;

}; // struct msg_info_router_

typedef ::msg_info_router::msg_info_router_<std::allocator<void> > msg_info_router;

typedef boost::shared_ptr< ::msg_info_router::msg_info_router > msg_info_routerPtr;
typedef boost::shared_ptr< ::msg_info_router::msg_info_router const> msg_info_routerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_info_router::msg_info_router_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_info_router::msg_info_router_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_info_router::msg_info_router_<ContainerAllocator1> & lhs, const ::msg_info_router::msg_info_router_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.task_type == rhs.task_type &&
    lhs.task_num == rhs.task_num &&
    lhs.segments_num == rhs.segments_num &&
    lhs.cur_segments_num == rhs.cur_segments_num &&
    lhs.state_type == rhs.state_type &&
    lhs.path_point == rhs.path_point &&
    lhs.stop_point == rhs.stop_point &&
    lhs.is_update_map == rhs.is_update_map &&
    lhs.remote_spd == rhs.remote_spd &&
    lhs.remote_steering == rhs.remote_steering &&
    lhs.remote_parking == rhs.remote_parking &&
    lhs.remote_stopengine == rhs.remote_stopengine &&
    lhs.remote_service_brake == rhs.remote_service_brake &&
    lhs.remote_park_brake == rhs.remote_park_brake &&
    lhs.remote_load_brake == rhs.remote_load_brake &&
    lhs.gear_num == rhs.gear_num &&
    lhs.carrier_control == rhs.carrier_control &&
    lhs.turn_light == rhs.turn_light &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.fog_light == rhs.fog_light &&
    lhs.brake_light == rhs.brake_light &&
    lhs.emer_light == rhs.emer_light &&
    lhs.wiper_sign == rhs.wiper_sign &&
    lhs.trumpet == rhs.trumpet;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_info_router::msg_info_router_<ContainerAllocator1> & lhs, const ::msg_info_router::msg_info_router_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_info_router

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_info_router::msg_info_router_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_info_router::msg_info_router_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_info_router::msg_info_router_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_info_router::msg_info_router_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_info_router::msg_info_router_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_info_router::msg_info_router_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_info_router::msg_info_router_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48626aa112e3a63e18582859d48dcf2e";
  }

  static const char* value(const ::msg_info_router::msg_info_router_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48626aa112e3a63eULL;
  static const uint64_t static_value2 = 0x18582859d48dcf2eULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_info_router::msg_info_router_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_info_router/msg_info_router";
  }

  static const char* value(const ::msg_info_router::msg_info_router_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_info_router::msg_info_router_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode 	#当前模式  	0:驾驶员驾驶(手动); 1:自动驾驶授权（地面自动驾驶）; 2:遥控\n"
"uint16 task_type	#当前任务  	0:保留; 1:前往装载点; 2:前往装载区候车区; 3:前往卸载点; 4:前往卸载候车区; 5:前往停车场停车点; 6:前往停车候车区\n"
"uint16 task_num	#任务编号  \n"
"uint16 segments_num	#全局路径分段数\n"
"uint16 cur_segments_num	#当前段数\n"
"uint16 state_type 	#状态类型  	0:保留; 1:自检; 2:启动发动机; 3:静态测试; 4:轨迹跟随; 5:排队停车; 6:跟车模式; 7:后台轨迹跟随; 8:卸载模式; 9:装载模式; 10:安全停车; 11:关闭发动机; 12:紧急停车; 13:待机；14:装载完成；\n"
"msg_common/WayPoint[] path_point	#轨迹点信息\n"
"Point stop_point		        #目标停车点\n"
"bool is_update_map		      #地图是否更新\n"
"float32 remote_spd		      #期望车速\n"
"float32 remote_steering	    #方向盘转角\n"
"float32 remote_parking		  #紧急停车指令\n"
"uint8 remote_stopengine	    #发动机停止信号\n"
"uint8 remote_service_brake 	#行车制动信号\n"
"uint8 remote_park_brake 	  #停车制动信号\n"
"uint8 remote_load_brake 	  #装载制动信号\n"
"uint8 gear_num    		  #期望档位\n"
"uint8 carrier_control  	#货舱控制信号\n"
"uint8 turn_light  		  #转向灯信号\n"
"uint8 dipped_light  		#远近光灯信号\n"
"uint8 marker_light  		#示廓灯信号\n"
"uint8 fog_light  		    #前雾灯信号\n"
"uint8 brake_light  		  #刹车灯信号\n"
"uint8 emer_light  		  #紧急灯信号\n"
"uint8 wiper_sign		    #雨刮控制信号\n"
"uint8 trumpet   		    #喇叭信号\n"
"\n"
"================================================================================\n"
"MSG: msg_common/WayPoint\n"
"float64 x			#路径x坐标\n"
"float64 y			#路径y坐标\n"
"float64 z			#路径z坐标\n"
"float64 left			#距左边界值\n"
"float64 right			#距右边界值\n"
"float32 heading_angle		#路径的方向\n"
"float32 curvature		#曲率\n"
"float32 speed			#路径的速度\n"
"float32 distance		#路点与路径起点沿路径的距离\n"
"float32 slope			#坡度信息\n"
"uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)\n"
"float32 speed_limit	        #速度上限\n"
"uint8 direction			#0表示前进，1表示后退\n"
"uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点\n"
"float64 t			#时间\n"
"string area_name		#区域名称	\n"
"string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	\n"
"\n"
"================================================================================\n"
"MSG: msg_info_router/Point\n"
"float64 x   		#大地坐标系x轴坐标\n"
"float64 y   		#大地坐标系y轴坐标\n"
"float32 heading_angle  	#航行角\n"
;
  }

  static const char* value(const ::msg_info_router::msg_info_router_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_info_router::msg_info_router_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.task_type);
      stream.next(m.task_num);
      stream.next(m.segments_num);
      stream.next(m.cur_segments_num);
      stream.next(m.state_type);
      stream.next(m.path_point);
      stream.next(m.stop_point);
      stream.next(m.is_update_map);
      stream.next(m.remote_spd);
      stream.next(m.remote_steering);
      stream.next(m.remote_parking);
      stream.next(m.remote_stopengine);
      stream.next(m.remote_service_brake);
      stream.next(m.remote_park_brake);
      stream.next(m.remote_load_brake);
      stream.next(m.gear_num);
      stream.next(m.carrier_control);
      stream.next(m.turn_light);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.fog_light);
      stream.next(m.brake_light);
      stream.next(m.emer_light);
      stream.next(m.wiper_sign);
      stream.next(m.trumpet);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_info_router_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_info_router::msg_info_router_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_info_router::msg_info_router_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "task_type: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "task_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.task_num);
    s << indent << "segments_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.segments_num);
    s << indent << "cur_segments_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cur_segments_num);
    s << indent << "state_type: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.state_type);
    s << indent << "path_point[]" << std::endl;
    for (size_t i = 0; i < v.path_point.size(); ++i)
    {
      s << indent << "  path_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_common::WayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.path_point[i]);
    }
    s << indent << "stop_point: ";
    s << std::endl;
    Printer< ::msg_info_router::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.stop_point);
    s << indent << "is_update_map: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_update_map);
    s << indent << "remote_spd: ";
    Printer<float>::stream(s, indent + "  ", v.remote_spd);
    s << indent << "remote_steering: ";
    Printer<float>::stream(s, indent + "  ", v.remote_steering);
    s << indent << "remote_parking: ";
    Printer<float>::stream(s, indent + "  ", v.remote_parking);
    s << indent << "remote_stopengine: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_stopengine);
    s << indent << "remote_service_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_service_brake);
    s << indent << "remote_park_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_park_brake);
    s << indent << "remote_load_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_load_brake);
    s << indent << "gear_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "carrier_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrier_control);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "fog_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fog_light);
    s << indent << "brake_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_light);
    s << indent << "emer_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emer_light);
    s << indent << "wiper_sign: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wiper_sign);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_INFO_ROUTER_MESSAGE_MSG_INFO_ROUTER_H
