// Generated by gencpp from file msg_info_router/Point.msg
// DO NOT EDIT!


#ifndef MSG_INFO_ROUTER_MESSAGE_POINT_H
#define MSG_INFO_ROUTER_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_info_router
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : x(0.0)
    , y(0.0)
    , heading_angle(0.0)  {
    }
  Point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , heading_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef float _heading_angle_type;
  _heading_angle_type heading_angle;





  typedef boost::shared_ptr< ::msg_info_router::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_info_router::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::msg_info_router::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::msg_info_router::Point > PointPtr;
typedef boost::shared_ptr< ::msg_info_router::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_info_router::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_info_router::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_info_router::Point_<ContainerAllocator1> & lhs, const ::msg_info_router::Point_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.heading_angle == rhs.heading_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_info_router::Point_<ContainerAllocator1> & lhs, const ::msg_info_router::Point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_info_router

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_info_router::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_info_router::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_info_router::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_info_router::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_info_router::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_info_router::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_info_router::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8abab9841cc486c43b9cf8142b306d7";
  }

  static const char* value(const ::msg_info_router::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8abab9841cc486cULL;
  static const uint64_t static_value2 = 0x43b9cf8142b306d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_info_router::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_info_router/Point";
  }

  static const char* value(const ::msg_info_router::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_info_router::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x   		#大地坐标系x轴坐标\n"
"float64 y   		#大地坐标系y轴坐标\n"
"float32 heading_angle  	#航行角\n"
;
  }

  static const char* value(const ::msg_info_router::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_info_router::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.heading_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_info_router::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_info_router::Point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "heading_angle: ";
    Printer<float>::stream(s, indent + "  ", v.heading_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_INFO_ROUTER_MESSAGE_POINT_H
