# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_common/WayPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WayPoint(genpy.Message):
  _md5sum = "14ccf02ddc37a7bf62cf9c7f57bc1b66"
  _type = "msg_common/WayPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x			#路径x坐标
float64 y			#路径y坐标
float64 z			#路径z坐标
float64 left			#距左边界值
float64 right			#距右边界值
float32 heading_angle		#路径的方向
float32 curvature		#曲率
float32 speed			#路径的速度
float32 distance		#路点与路径起点沿路径的距离
float32 slope			#坡度信息
uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)
float32 speed_limit	        #速度上限
uint8 direction			#0表示前进，1表示后退
uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点
float64 t			#时间
string area_name		#区域名称	
string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	
"""
  __slots__ = ['x','y','z','left','right','heading_angle','curvature','speed','distance','slope','attribute','speed_limit','direction','waypointattr','t','area_name','onareaid']
  _slot_types = ['float64','float64','float64','float64','float64','float32','float32','float32','float32','float32','uint32','float32','uint8','uint8','float64','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,left,right,heading_angle,curvature,speed,distance,slope,attribute,speed_limit,direction,waypointattr,t,area_name,onareaid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WayPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.left is None:
        self.left = 0.
      if self.right is None:
        self.right = 0.
      if self.heading_angle is None:
        self.heading_angle = 0.
      if self.curvature is None:
        self.curvature = 0.
      if self.speed is None:
        self.speed = 0.
      if self.distance is None:
        self.distance = 0.
      if self.slope is None:
        self.slope = 0.
      if self.attribute is None:
        self.attribute = 0
      if self.speed_limit is None:
        self.speed_limit = 0.
      if self.direction is None:
        self.direction = 0
      if self.waypointattr is None:
        self.waypointattr = 0
      if self.t is None:
        self.t = 0.
      if self.area_name is None:
        self.area_name = ''
      if self.onareaid is None:
        self.onareaid = ''
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.left = 0.
      self.right = 0.
      self.heading_angle = 0.
      self.curvature = 0.
      self.speed = 0.
      self.distance = 0.
      self.slope = 0.
      self.attribute = 0
      self.speed_limit = 0.
      self.direction = 0
      self.waypointattr = 0
      self.t = 0.
      self.area_name = ''
      self.onareaid = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
      _x = self.area_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.onareaid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 78
      (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.area_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.area_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.onareaid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.onareaid = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
      _x = self.area_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.onareaid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 78
      (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.area_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.area_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.onareaid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.onareaid = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d5fIf2Bd = None
def _get_struct_5d5fIf2Bd():
    global _struct_5d5fIf2Bd
    if _struct_5d5fIf2Bd is None:
        _struct_5d5fIf2Bd = struct.Struct("<5d5fIf2Bd")
    return _struct_5d5fIf2Bd
