// Generated by gencpp from file msg_perception_safety_status/msg_perception_safety_status.msg
// DO NOT EDIT!


#ifndef MSG_PERCEPTION_SAFETY_STATUS_MESSAGE_MSG_PERCEPTION_SAFETY_STATUS_H
#define MSG_PERCEPTION_SAFETY_STATUS_MESSAGE_MSG_PERCEPTION_SAFETY_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <msg_perception_safety_status/SensorErrorInfo.h>

namespace msg_perception_safety_status
{
template <class ContainerAllocator>
struct msg_perception_safety_status_
{
  typedef msg_perception_safety_status_<ContainerAllocator> Type;

  msg_perception_safety_status_()
    : header()
    , error_status(0)
    , sensor_error_info()  {
    }
  msg_perception_safety_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , error_status(0)
    , sensor_error_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _error_status_type;
  _error_status_type error_status;

   typedef std::vector< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >> _sensor_error_info_type;
  _sensor_error_info_type sensor_error_info;





  typedef boost::shared_ptr< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> const> ConstPtr;

}; // struct msg_perception_safety_status_

typedef ::msg_perception_safety_status::msg_perception_safety_status_<std::allocator<void> > msg_perception_safety_status;

typedef boost::shared_ptr< ::msg_perception_safety_status::msg_perception_safety_status > msg_perception_safety_statusPtr;
typedef boost::shared_ptr< ::msg_perception_safety_status::msg_perception_safety_status const> msg_perception_safety_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator1> & lhs, const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.error_status == rhs.error_status &&
    lhs.sensor_error_info == rhs.sensor_error_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator1> & lhs, const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_perception_safety_status

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0734a6e0d665e44932d6c5009065586";
  }

  static const char* value(const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0734a6e0d665e44ULL;
  static const uint64_t static_value2 = 0x932d6c5009065586ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_perception_safety_status/msg_perception_safety_status";
  }

  static const char* value(const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header              #frame_id为节点名称\n"
"uint8 error_status         #0：正常(心跳信号) n：故障信息个数\n"
"SensorErrorInfo[] sensor_error_info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: msg_perception_safety_status/SensorErrorInfo\n"
"int32   sensor_type  # 1:激光 2:相机 3:毫米波 4:感知融合节点【只有程序故障】\n"
"int32   sensor_id    # 激光雷达按100/101/102 相机按200/201 毫米波按300/301/302 \n"
"string  sensor_name  # 传感器名称，按品牌或厂家；如激光雷达按 \"ouster\" \"leishen\"\n"
"int32   sensor_position  # 安装位置 1:front 2:back 3:left 4:right 5:front_left 6:front_right 7:back_left 8:back_right\n"
"int32   sensor_main    # 0: 非主传感器  1: 主传感器\n"
"uint8   sensor_error_status   # 0：正常(心跳信号) 1：异常\n"
"int32   sensor_error_code     # 故障编码如下:\n"
"# 101:  传感器硬件故障，没有原始数据输出\n"
"# 102:  传感器程序故障，没有目标数据输出\n"
"# 103:  传感器表面存在异物遮挡（灰尘泥沙等） --需要清洗 \n"
"# 104:  传感器表面存在水渍 --需要吹风\n"
"# 105:  传感器数据存在损坏现象 --指的是摄像头画面存在异常情况\n"
;
  }

  static const char* value(const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.error_status);
      stream.next(m.sensor_error_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_perception_safety_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_perception_safety_status::msg_perception_safety_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "error_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_status);
    s << indent << "sensor_error_info[]" << std::endl;
    for (size_t i = 0; i < v.sensor_error_info.size(); ++i)
    {
      s << indent << "  sensor_error_info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.sensor_error_info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PERCEPTION_SAFETY_STATUS_MESSAGE_MSG_PERCEPTION_SAFETY_STATUS_H
