// Generated by gencpp from file msg_perception_safety_status/SensorErrorInfo.msg
// DO NOT EDIT!


#ifndef MSG_PERCEPTION_SAFETY_STATUS_MESSAGE_SENSORERRORINFO_H
#define MSG_PERCEPTION_SAFETY_STATUS_MESSAGE_SENSORERRORINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_perception_safety_status
{
template <class ContainerAllocator>
struct SensorErrorInfo_
{
  typedef SensorErrorInfo_<ContainerAllocator> Type;

  SensorErrorInfo_()
    : sensor_type(0)
    , sensor_id(0)
    , sensor_name()
    , sensor_position(0)
    , sensor_main(0)
    , sensor_error_status(0)
    , sensor_error_code(0)  {
    }
  SensorErrorInfo_(const ContainerAllocator& _alloc)
    : sensor_type(0)
    , sensor_id(0)
    , sensor_name(_alloc)
    , sensor_position(0)
    , sensor_main(0)
    , sensor_error_status(0)
    , sensor_error_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _sensor_type_type;
  _sensor_type_type sensor_type;

   typedef int32_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sensor_name_type;
  _sensor_name_type sensor_name;

   typedef int32_t _sensor_position_type;
  _sensor_position_type sensor_position;

   typedef int32_t _sensor_main_type;
  _sensor_main_type sensor_main;

   typedef uint8_t _sensor_error_status_type;
  _sensor_error_status_type sensor_error_status;

   typedef int32_t _sensor_error_code_type;
  _sensor_error_code_type sensor_error_code;





  typedef boost::shared_ptr< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SensorErrorInfo_

typedef ::msg_perception_safety_status::SensorErrorInfo_<std::allocator<void> > SensorErrorInfo;

typedef boost::shared_ptr< ::msg_perception_safety_status::SensorErrorInfo > SensorErrorInfoPtr;
typedef boost::shared_ptr< ::msg_perception_safety_status::SensorErrorInfo const> SensorErrorInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator1> & lhs, const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator2> & rhs)
{
  return lhs.sensor_type == rhs.sensor_type &&
    lhs.sensor_id == rhs.sensor_id &&
    lhs.sensor_name == rhs.sensor_name &&
    lhs.sensor_position == rhs.sensor_position &&
    lhs.sensor_main == rhs.sensor_main &&
    lhs.sensor_error_status == rhs.sensor_error_status &&
    lhs.sensor_error_code == rhs.sensor_error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator1> & lhs, const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_perception_safety_status

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d982ad46e4ba93bdfb185ecf31af296c";
  }

  static const char* value(const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd982ad46e4ba93bdULL;
  static const uint64_t static_value2 = 0xfb185ecf31af296cULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_perception_safety_status/SensorErrorInfo";
  }

  static const char* value(const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   sensor_type  # 1:激光 2:相机 3:毫米波 4:感知融合节点【只有程序故障】\n"
"int32   sensor_id    # 激光雷达按100/101/102 相机按200/201 毫米波按300/301/302 \n"
"string  sensor_name  # 传感器名称，按品牌或厂家；如激光雷达按 \"ouster\" \"leishen\"\n"
"int32   sensor_position  # 安装位置 1:front 2:back 3:left 4:right 5:front_left 6:front_right 7:back_left 8:back_right\n"
"int32   sensor_main    # 0: 非主传感器  1: 主传感器\n"
"uint8   sensor_error_status   # 0：正常(心跳信号) 1：异常\n"
"int32   sensor_error_code     # 故障编码如下:\n"
"# 101:  传感器硬件故障，没有原始数据输出\n"
"# 102:  传感器程序故障，没有目标数据输出\n"
"# 103:  传感器表面存在异物遮挡（灰尘泥沙等） --需要清洗 \n"
"# 104:  传感器表面存在水渍 --需要吹风\n"
"# 105:  传感器数据存在损坏现象 --指的是摄像头画面存在异常情况\n"
;
  }

  static const char* value(const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_type);
      stream.next(m.sensor_id);
      stream.next(m.sensor_name);
      stream.next(m.sensor_position);
      stream.next(m.sensor_main);
      stream.next(m.sensor_error_status);
      stream.next(m.sensor_error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorErrorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_perception_safety_status::SensorErrorInfo_<ContainerAllocator>& v)
  {
    s << indent << "sensor_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_type);
    s << indent << "sensor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "sensor_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sensor_name);
    s << indent << "sensor_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_position);
    s << indent << "sensor_main: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_main);
    s << indent << "sensor_error_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_error_status);
    s << indent << "sensor_error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PERCEPTION_SAFETY_STATUS_MESSAGE_SENSORERRORINFO_H
