(cl:in-package msg_local_planning-msg)
(cl:export '(TARGET_ID-VAL
          TARGET_ID
          TRAJ_ID-VAL
          TRAJ_ID
          WAY_POINT-VAL
          WAY_POINT
          REMOTE_SPD-VAL
          REMOTE_SPD
          REMOTE_STEERING-VAL
          REMOTE_STEERING
          REMOTE_PARKING-VAL
          REMOTE_PARKING
          REMOTE_STOPENGINE-VAL
          REMOTE_STOPENGINE
          REMOTE_SERVICE_BRAKE-VAL
          REMOTE_SERVICE_BRAKE
          REMOTE_PARK_BRAKE-VAL
          REMOTE_PARK_BRAKE
          REMOTE_LOAD_BRAKE-VAL
          REMOTE_LOAD_BRAKE
          GEAR_NUM-VAL
          GEAR_NUM
          CARRIER_CONTROL-VAL
          CARRIER_CONTROL
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          TRUMPET-VAL
          TRUMPET
))