(cl:in-package msg_local_planning-msg)
(cl:export '(DRIVING_MODE-VAL
          DRIVING_MODE
          CONTROL_MODE-VAL
          CONTROL_MODE
          GEAR_NUM-VAL
          GEAR_NUM
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          ILLUMINATION_LIGHT-VAL
          ILLUMINATION_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          BACKUP_LIGHT-VAL
          BACKUP_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          CARRIRE_WARM_LIGHT-VAL
          CARRIRE_WARM_LIGHT
          TRUMPET-VAL
          TRUMPET
          CARRIER_CONTROL-VAL
          CARRIER_CONTROL
          PARK_BRK-VAL
          PARK_BRK
          WAY_POINT-VAL
          WAY_POINT
          REMOTE_SPD-VAL
          REMOTE_SPD
          REMOTE_STEERING-VAL
          REMOTE_STEERING
          REMOTE_PARKING-VAL
          REMOTE_PARKING
          BRIM_CONTROL-VAL
          BRIM_CONTROL
          CARRIRE_ENABLE-VAL
          CARRIRE_ENABLE
          IS_CLEAN-VAL
          IS_CLEAN
))