(cl:in-package msg_v_prep-msg)
(cl:export '(AUTO_STATUS_MODE-VAL
          AUTO_STATUS_MODE
          AUTO_STATUS_READY-VAL
          AUTO_STATUS_READY
          AUTO_STATUS_INTERVENE-VAL
          AUTO_STATUS_INTERVENE
          SPEED-VAL
          SPEED
          STEERING_ANGLE_LEFT-VAL
          STEERING_ANGLE_LEFT
          STEERING_ANGLE_RIGHT-VAL
          STEERING_ANGLE_RIGHT
          STEER_CONTROL_STATUS-VAL
          STEER_CONTROL_STATUS
          THR_ANGLE-VAL
          THR_ANGLE
          GEAR_NUM-VAL
          GEAR_NUM
          EMERG_STATE-VAL
          EMERG_STATE
          BRAKING_DECE-VAL
          BRAKING_DECE
          FUEL_NUM-VAL
          FUEL_NUM
          PARK_BRK-VAL
          PARK_BRK
          CARRIER_ANGLE-VAL
          CARRIER_ANGLE
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          BACKUP_LIGHT-VAL
          BACKUP_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          CARRIRE_WARM_LIGHT-VAL
          CARRIRE_WARM_LIGHT
          ILLUMINATION_LIGHT-VAL
          ILLUMINATION_LIGHT
          TRUMPET-VAL
          TRUMPET
))