// Generated by gencpp from file msg_v_state/msg_v_state.msg
// DO NOT EDIT!


#ifndef MSG_V_STATE_MESSAGE_MSG_V_STATE_H
#define MSG_V_STATE_MESSAGE_MSG_V_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msg_v_state
{
template <class ContainerAllocator>
struct msg_v_state_
{
  typedef msg_v_state_<ContainerAllocator> Type;

  msg_v_state_()
    : header()
    , gps_status(0)
    , gps_week(0)
    , gps_time(0.0)
    , longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , heading_angle(0.0)
    , yaw_angle(0.0)
    , yaw_rate(0.0)
    , pitch_angle(0.0)
    , pitch_rate(0.0)
    , roll_angle(0.0)
    , roll_rate(0.0)
    , spd_east(0.0)
    , spd_north(0.0)
    , spd_up(0.0)
    , spd(0.0)
    , spd_lon(0.0)
    , spd_lat(0.0)
    , acce(0.0)
    , acce_lon(0.0)
    , acce_lat(0.0)
    , static_check(0)
    , auto_status_mode(0)
    , auto_status_ready(0)
    , auto_status_intervene(0)
    , speed(0.0)
    , steering_angle(0.0)
    , steer_control_status(0)
    , steering_spd(0.0)
    , wheel_angle(0.0)
    , target_steering_angle(0.0)
    , trq(0.0)
    , target_trq(0.0)
    , thr_angle(0.0)
    , gear_num(0)
    , emerg_state(0)
    , braking_dece(0.0)
    , fuel_num(0.0)
    , park_brk(0)
    , carrier_angle(0.0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , brake_light(0)
    , emer_light(0)
    , backup_light(0)
    , position_light(0)
    , carrire_warm_light(0)
    , illumination_light(0)
    , trumpet(0)
    , pto_status(0)
    , brim_state(0)
    , clean_status()
    , switch_status(false)  {
    }
  msg_v_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps_status(0)
    , gps_week(0)
    , gps_time(0.0)
    , longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , heading_angle(0.0)
    , yaw_angle(0.0)
    , yaw_rate(0.0)
    , pitch_angle(0.0)
    , pitch_rate(0.0)
    , roll_angle(0.0)
    , roll_rate(0.0)
    , spd_east(0.0)
    , spd_north(0.0)
    , spd_up(0.0)
    , spd(0.0)
    , spd_lon(0.0)
    , spd_lat(0.0)
    , acce(0.0)
    , acce_lon(0.0)
    , acce_lat(0.0)
    , static_check(0)
    , auto_status_mode(0)
    , auto_status_ready(0)
    , auto_status_intervene(0)
    , speed(0.0)
    , steering_angle(0.0)
    , steer_control_status(0)
    , steering_spd(0.0)
    , wheel_angle(0.0)
    , target_steering_angle(0.0)
    , trq(0.0)
    , target_trq(0.0)
    , thr_angle(0.0)
    , gear_num(0)
    , emerg_state(0)
    , braking_dece(0.0)
    , fuel_num(0.0)
    , park_brk(0)
    , carrier_angle(0.0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , brake_light(0)
    , emer_light(0)
    , backup_light(0)
    , position_light(0)
    , carrire_warm_light(0)
    , illumination_light(0)
    , trumpet(0)
    , pto_status(0)
    , brim_state(0)
    , clean_status(_alloc)
    , switch_status(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _gps_status_type;
  _gps_status_type gps_status;

   typedef int32_t _gps_week_type;
  _gps_week_type gps_week;

   typedef double _gps_time_type;
  _gps_time_type gps_time;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef float _heading_angle_type;
  _heading_angle_type heading_angle;

   typedef float _yaw_angle_type;
  _yaw_angle_type yaw_angle;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _pitch_angle_type;
  _pitch_angle_type pitch_angle;

   typedef float _pitch_rate_type;
  _pitch_rate_type pitch_rate;

   typedef float _roll_angle_type;
  _roll_angle_type roll_angle;

   typedef float _roll_rate_type;
  _roll_rate_type roll_rate;

   typedef float _spd_east_type;
  _spd_east_type spd_east;

   typedef float _spd_north_type;
  _spd_north_type spd_north;

   typedef float _spd_up_type;
  _spd_up_type spd_up;

   typedef float _spd_type;
  _spd_type spd;

   typedef float _spd_lon_type;
  _spd_lon_type spd_lon;

   typedef float _spd_lat_type;
  _spd_lat_type spd_lat;

   typedef float _acce_type;
  _acce_type acce;

   typedef float _acce_lon_type;
  _acce_lon_type acce_lon;

   typedef float _acce_lat_type;
  _acce_lat_type acce_lat;

   typedef uint8_t _static_check_type;
  _static_check_type static_check;

   typedef uint8_t _auto_status_mode_type;
  _auto_status_mode_type auto_status_mode;

   typedef uint8_t _auto_status_ready_type;
  _auto_status_ready_type auto_status_ready;

   typedef uint8_t _auto_status_intervene_type;
  _auto_status_intervene_type auto_status_intervene;

   typedef float _speed_type;
  _speed_type speed;

   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef uint8_t _steer_control_status_type;
  _steer_control_status_type steer_control_status;

   typedef double _steering_spd_type;
  _steering_spd_type steering_spd;

   typedef float _wheel_angle_type;
  _wheel_angle_type wheel_angle;

   typedef float _target_steering_angle_type;
  _target_steering_angle_type target_steering_angle;

   typedef float _trq_type;
  _trq_type trq;

   typedef float _target_trq_type;
  _target_trq_type target_trq;

   typedef float _thr_angle_type;
  _thr_angle_type thr_angle;

   typedef uint8_t _gear_num_type;
  _gear_num_type gear_num;

   typedef uint8_t _emerg_state_type;
  _emerg_state_type emerg_state;

   typedef float _braking_dece_type;
  _braking_dece_type braking_dece;

   typedef double _fuel_num_type;
  _fuel_num_type fuel_num;

   typedef uint8_t _park_brk_type;
  _park_brk_type park_brk;

   typedef float _carrier_angle_type;
  _carrier_angle_type carrier_angle;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _brake_light_type;
  _brake_light_type brake_light;

   typedef uint8_t _emer_light_type;
  _emer_light_type emer_light;

   typedef uint8_t _backup_light_type;
  _backup_light_type backup_light;

   typedef uint8_t _position_light_type;
  _position_light_type position_light;

   typedef uint8_t _carrire_warm_light_type;
  _carrire_warm_light_type carrire_warm_light;

   typedef uint8_t _illumination_light_type;
  _illumination_light_type illumination_light;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;

   typedef uint8_t _pto_status_type;
  _pto_status_type pto_status;

   typedef uint8_t _brim_state_type;
  _brim_state_type brim_state;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _clean_status_type;
  _clean_status_type clean_status;

   typedef uint8_t _switch_status_type;
  _switch_status_type switch_status;





  typedef boost::shared_ptr< ::msg_v_state::msg_v_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_v_state::msg_v_state_<ContainerAllocator> const> ConstPtr;

}; // struct msg_v_state_

typedef ::msg_v_state::msg_v_state_<std::allocator<void> > msg_v_state;

typedef boost::shared_ptr< ::msg_v_state::msg_v_state > msg_v_statePtr;
typedef boost::shared_ptr< ::msg_v_state::msg_v_state const> msg_v_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_v_state::msg_v_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_v_state::msg_v_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_v_state::msg_v_state_<ContainerAllocator1> & lhs, const ::msg_v_state::msg_v_state_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gps_status == rhs.gps_status &&
    lhs.gps_week == rhs.gps_week &&
    lhs.gps_time == rhs.gps_time &&
    lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude &&
    lhs.altitude == rhs.altitude &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.heading_angle == rhs.heading_angle &&
    lhs.yaw_angle == rhs.yaw_angle &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.pitch_angle == rhs.pitch_angle &&
    lhs.pitch_rate == rhs.pitch_rate &&
    lhs.roll_angle == rhs.roll_angle &&
    lhs.roll_rate == rhs.roll_rate &&
    lhs.spd_east == rhs.spd_east &&
    lhs.spd_north == rhs.spd_north &&
    lhs.spd_up == rhs.spd_up &&
    lhs.spd == rhs.spd &&
    lhs.spd_lon == rhs.spd_lon &&
    lhs.spd_lat == rhs.spd_lat &&
    lhs.acce == rhs.acce &&
    lhs.acce_lon == rhs.acce_lon &&
    lhs.acce_lat == rhs.acce_lat &&
    lhs.static_check == rhs.static_check &&
    lhs.auto_status_mode == rhs.auto_status_mode &&
    lhs.auto_status_ready == rhs.auto_status_ready &&
    lhs.auto_status_intervene == rhs.auto_status_intervene &&
    lhs.speed == rhs.speed &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.steer_control_status == rhs.steer_control_status &&
    lhs.steering_spd == rhs.steering_spd &&
    lhs.wheel_angle == rhs.wheel_angle &&
    lhs.target_steering_angle == rhs.target_steering_angle &&
    lhs.trq == rhs.trq &&
    lhs.target_trq == rhs.target_trq &&
    lhs.thr_angle == rhs.thr_angle &&
    lhs.gear_num == rhs.gear_num &&
    lhs.emerg_state == rhs.emerg_state &&
    lhs.braking_dece == rhs.braking_dece &&
    lhs.fuel_num == rhs.fuel_num &&
    lhs.park_brk == rhs.park_brk &&
    lhs.carrier_angle == rhs.carrier_angle &&
    lhs.turn_light == rhs.turn_light &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.brake_light == rhs.brake_light &&
    lhs.emer_light == rhs.emer_light &&
    lhs.backup_light == rhs.backup_light &&
    lhs.position_light == rhs.position_light &&
    lhs.carrire_warm_light == rhs.carrire_warm_light &&
    lhs.illumination_light == rhs.illumination_light &&
    lhs.trumpet == rhs.trumpet &&
    lhs.pto_status == rhs.pto_status &&
    lhs.brim_state == rhs.brim_state &&
    lhs.clean_status == rhs.clean_status &&
    lhs.switch_status == rhs.switch_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_v_state::msg_v_state_<ContainerAllocator1> & lhs, const ::msg_v_state::msg_v_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_v_state

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_state::msg_v_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_state::msg_v_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_state::msg_v_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_state::msg_v_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_state::msg_v_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_state::msg_v_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_v_state::msg_v_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa6af63a1ba367c32483e9b79096ee80";
  }

  static const char* value(const ::msg_v_state::msg_v_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa6af63a1ba367c3ULL;
  static const uint64_t static_value2 = 0x2483e9b79096ee80ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_v_state::msg_v_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_v_state/msg_v_state";
  }

  static const char* value(const ::msg_v_state::msg_v_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_v_state::msg_v_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header         # ROS time header\n"
"uint8    gps_status\n"
"int32    gps_week\n"
"float64  gps_time\n"
"float64  longitude            \n"
"float64  latitude\n"
"float64  altitude\n"
"float64  x\n"
"float64  y\n"
"float64  z\n"
"float32  heading_angle\n"
"float32  yaw_angle\n"
"float32  yaw_rate\n"
"float32  pitch_angle\n"
"float32  pitch_rate\n"
"float32  roll_angle\n"
"float32  roll_rate\n"
"float32  spd_east\n"
"float32  spd_north\n"
"float32  spd_up\n"
"float32  spd \n"
"float32  spd_lon\n"
"float32  spd_lat\n"
"float32  acce\n"
"float32  acce_lon\n"
"float32  acce_lat\n"
"char static_check                 # 0:no commend; 1: checking; 2: pass check; 4: check failed\n"
"uint8 auto_status_mode		   	   # 自动驾驶模式: 0,手动;1,自动\n"
"uint8 auto_status_ready		   # 自动驾驶状态准备：0,未就绪;1,就绪\n"
"uint8 auto_status_intervene		   # 自动驾驶状态下有刹车介入：0,无介入;1,有介入\n"
"float32 speed			           # 底层提供的车速\n"
"float64 steering_angle		   # 实际车轮转角\n"
"uint8 steer_control_status	           # 转向控制器状态：0, 待机； 1,自动驾驶模式;4,手动模式;5,驾驶员介入模式\n"
"float64 steering_spd\n"
"float32 wheel_angle\n"
"float32 target_steering_angle\n"
"float32 trq\n"
"float32 target_trq\n"
"float32 thr_angle			   # 实际油门开度\n"
"uint8 gear_num			           # 实际档位：0,P;1,R;2,D;3,N\n"
"uint8 emerg_state			   # 紧急制动状态\n"
"float32 braking_dece		           # 制动减速度\n"
"float64 fuel_num			   # 燃油状态（剩余油量）\n"
"uint8 park_brk			           # 驻车制动状态： 0, 无驻车制动;1, 在驻车制动中\n"
"float32 carrier_angle		           # 货舱举升角度\n"
"uint8 turn_light			   # 转向灯状态\n"
"uint8 dipped_light			   # 远、近光灯状态\n"
"uint8 marker_light			   # 示廓灯/前雾灯状态\n"
"uint8 brake_light			   # 刹车灯状态\n"
"uint8 emer_light			   # 紧急信号灯状态\n"
"uint8 backup_light 		           # 倒车灯信号\n"
"uint8 position_light		           # 位置灯信号\n"
"uint8 carrire_warm_light		   # 举升警告灯信号\n"
"uint8 illumination_light		   # 照明灯信号\n"
"uint8 trumpet			           # 喇叭信号\n"
"uint8 pto_status                    #取力器使能状态\n"
"uint8 brim_state                    #帽檐举升状态\n"
"bool[] clean_status              # 传感器状态\n"
"bool switch_status		  #自动驾驶开关状态：0：关闭 1：打开\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msg_v_state::msg_v_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_v_state::msg_v_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps_status);
      stream.next(m.gps_week);
      stream.next(m.gps_time);
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.altitude);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.heading_angle);
      stream.next(m.yaw_angle);
      stream.next(m.yaw_rate);
      stream.next(m.pitch_angle);
      stream.next(m.pitch_rate);
      stream.next(m.roll_angle);
      stream.next(m.roll_rate);
      stream.next(m.spd_east);
      stream.next(m.spd_north);
      stream.next(m.spd_up);
      stream.next(m.spd);
      stream.next(m.spd_lon);
      stream.next(m.spd_lat);
      stream.next(m.acce);
      stream.next(m.acce_lon);
      stream.next(m.acce_lat);
      stream.next(m.static_check);
      stream.next(m.auto_status_mode);
      stream.next(m.auto_status_ready);
      stream.next(m.auto_status_intervene);
      stream.next(m.speed);
      stream.next(m.steering_angle);
      stream.next(m.steer_control_status);
      stream.next(m.steering_spd);
      stream.next(m.wheel_angle);
      stream.next(m.target_steering_angle);
      stream.next(m.trq);
      stream.next(m.target_trq);
      stream.next(m.thr_angle);
      stream.next(m.gear_num);
      stream.next(m.emerg_state);
      stream.next(m.braking_dece);
      stream.next(m.fuel_num);
      stream.next(m.park_brk);
      stream.next(m.carrier_angle);
      stream.next(m.turn_light);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.brake_light);
      stream.next(m.emer_light);
      stream.next(m.backup_light);
      stream.next(m.position_light);
      stream.next(m.carrire_warm_light);
      stream.next(m.illumination_light);
      stream.next(m.trumpet);
      stream.next(m.pto_status);
      stream.next(m.brim_state);
      stream.next(m.clean_status);
      stream.next(m.switch_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_v_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_v_state::msg_v_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_v_state::msg_v_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gps_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_status);
    s << indent << "gps_week: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gps_week);
    s << indent << "gps_time: ";
    Printer<double>::stream(s, indent + "  ", v.gps_time);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "heading_angle: ";
    Printer<float>::stream(s, indent + "  ", v.heading_angle);
    s << indent << "yaw_angle: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_angle);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "pitch_angle: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_angle);
    s << indent << "pitch_rate: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_rate);
    s << indent << "roll_angle: ";
    Printer<float>::stream(s, indent + "  ", v.roll_angle);
    s << indent << "roll_rate: ";
    Printer<float>::stream(s, indent + "  ", v.roll_rate);
    s << indent << "spd_east: ";
    Printer<float>::stream(s, indent + "  ", v.spd_east);
    s << indent << "spd_north: ";
    Printer<float>::stream(s, indent + "  ", v.spd_north);
    s << indent << "spd_up: ";
    Printer<float>::stream(s, indent + "  ", v.spd_up);
    s << indent << "spd: ";
    Printer<float>::stream(s, indent + "  ", v.spd);
    s << indent << "spd_lon: ";
    Printer<float>::stream(s, indent + "  ", v.spd_lon);
    s << indent << "spd_lat: ";
    Printer<float>::stream(s, indent + "  ", v.spd_lat);
    s << indent << "acce: ";
    Printer<float>::stream(s, indent + "  ", v.acce);
    s << indent << "acce_lon: ";
    Printer<float>::stream(s, indent + "  ", v.acce_lon);
    s << indent << "acce_lat: ";
    Printer<float>::stream(s, indent + "  ", v.acce_lat);
    s << indent << "static_check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.static_check);
    s << indent << "auto_status_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_status_mode);
    s << indent << "auto_status_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_status_ready);
    s << indent << "auto_status_intervene: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_status_intervene);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
    s << indent << "steer_control_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.steer_control_status);
    s << indent << "steering_spd: ";
    Printer<double>::stream(s, indent + "  ", v.steering_spd);
    s << indent << "wheel_angle: ";
    Printer<float>::stream(s, indent + "  ", v.wheel_angle);
    s << indent << "target_steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.target_steering_angle);
    s << indent << "trq: ";
    Printer<float>::stream(s, indent + "  ", v.trq);
    s << indent << "target_trq: ";
    Printer<float>::stream(s, indent + "  ", v.target_trq);
    s << indent << "thr_angle: ";
    Printer<float>::stream(s, indent + "  ", v.thr_angle);
    s << indent << "gear_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "emerg_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emerg_state);
    s << indent << "braking_dece: ";
    Printer<float>::stream(s, indent + "  ", v.braking_dece);
    s << indent << "fuel_num: ";
    Printer<double>::stream(s, indent + "  ", v.fuel_num);
    s << indent << "park_brk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.park_brk);
    s << indent << "carrier_angle: ";
    Printer<float>::stream(s, indent + "  ", v.carrier_angle);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "brake_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_light);
    s << indent << "emer_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emer_light);
    s << indent << "backup_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.backup_light);
    s << indent << "position_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_light);
    s << indent << "carrire_warm_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrire_warm_light);
    s << indent << "illumination_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.illumination_light);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
    s << indent << "pto_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pto_status);
    s << indent << "brim_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brim_state);
    s << indent << "clean_status[]" << std::endl;
    for (size_t i = 0; i < v.clean_status.size(); ++i)
    {
      s << indent << "  clean_status[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.clean_status[i]);
    }
    s << indent << "switch_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_V_STATE_MESSAGE_MSG_V_STATE_H
