// Generated by gencpp from file msg_v_control/msg_v_control.msg
// DO NOT EDIT!


#ifndef MSG_V_CONTROL_MESSAGE_MSG_V_CONTROL_H
#define MSG_V_CONTROL_MESSAGE_MSG_V_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_v_control
{
template <class ContainerAllocator>
struct msg_v_control_
{
  typedef msg_v_control_<ContainerAllocator> Type;

  msg_v_control_()
    : static_check(0)
    , steering_angle(0.0)
    , steering_spd(0.0)
    , thr_angle(0)
    , brake_pressure(0.0)
    , brk_current(0.0)
    , flag(0)
    , engine_ctr(0)
    , park_brk(0)
    , load_brk(0)
    , carrier_control(0)
    , dumpbed_ctr(0.0)
    , turn_light(0)
    , gear_num(0)
    , gear_cmd(0)
    , gear_flag(0)
    , gear_cleardriver(0)
    , dipped_light(0)
    , marker_light(0)
    , brake_light(0)
    , emer_light(0)
    , trumpet(0)
    , state_light(0)
    , rest_off_ctr(0)
    , lube_ctr(0)
    , auto_cmd(0)
    , override_cmd(0)
    , light_ctr(0)  {
    }
  msg_v_control_(const ContainerAllocator& _alloc)
    : static_check(0)
    , steering_angle(0.0)
    , steering_spd(0.0)
    , thr_angle(0)
    , brake_pressure(0.0)
    , brk_current(0.0)
    , flag(0)
    , engine_ctr(0)
    , park_brk(0)
    , load_brk(0)
    , carrier_control(0)
    , dumpbed_ctr(0.0)
    , turn_light(0)
    , gear_num(0)
    , gear_cmd(0)
    , gear_flag(0)
    , gear_cleardriver(0)
    , dipped_light(0)
    , marker_light(0)
    , brake_light(0)
    , emer_light(0)
    , trumpet(0)
    , state_light(0)
    , rest_off_ctr(0)
    , lube_ctr(0)
    , auto_cmd(0)
    , override_cmd(0)
    , light_ctr(0)  {
  (void)_alloc;
    }



   typedef uint8_t _static_check_type;
  _static_check_type static_check;

   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef double _steering_spd_type;
  _steering_spd_type steering_spd;

   typedef int32_t _thr_angle_type;
  _thr_angle_type thr_angle;

   typedef float _brake_pressure_type;
  _brake_pressure_type brake_pressure;

   typedef float _brk_current_type;
  _brk_current_type brk_current;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef uint8_t _engine_ctr_type;
  _engine_ctr_type engine_ctr;

   typedef uint8_t _park_brk_type;
  _park_brk_type park_brk;

   typedef uint8_t _load_brk_type;
  _load_brk_type load_brk;

   typedef uint8_t _carrier_control_type;
  _carrier_control_type carrier_control;

   typedef float _dumpbed_ctr_type;
  _dumpbed_ctr_type dumpbed_ctr;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef int32_t _gear_num_type;
  _gear_num_type gear_num;

   typedef int32_t _gear_cmd_type;
  _gear_cmd_type gear_cmd;

   typedef int32_t _gear_flag_type;
  _gear_flag_type gear_flag;

   typedef int32_t _gear_cleardriver_type;
  _gear_cleardriver_type gear_cleardriver;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _brake_light_type;
  _brake_light_type brake_light;

   typedef uint8_t _emer_light_type;
  _emer_light_type emer_light;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;

   typedef uint8_t _state_light_type;
  _state_light_type state_light;

   typedef uint8_t _rest_off_ctr_type;
  _rest_off_ctr_type rest_off_ctr;

   typedef uint8_t _lube_ctr_type;
  _lube_ctr_type lube_ctr;

   typedef uint8_t _auto_cmd_type;
  _auto_cmd_type auto_cmd;

   typedef uint8_t _override_cmd_type;
  _override_cmd_type override_cmd;

   typedef uint8_t _light_ctr_type;
  _light_ctr_type light_ctr;





  typedef boost::shared_ptr< ::msg_v_control::msg_v_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_v_control::msg_v_control_<ContainerAllocator> const> ConstPtr;

}; // struct msg_v_control_

typedef ::msg_v_control::msg_v_control_<std::allocator<void> > msg_v_control;

typedef boost::shared_ptr< ::msg_v_control::msg_v_control > msg_v_controlPtr;
typedef boost::shared_ptr< ::msg_v_control::msg_v_control const> msg_v_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_v_control::msg_v_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_v_control::msg_v_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_v_control::msg_v_control_<ContainerAllocator1> & lhs, const ::msg_v_control::msg_v_control_<ContainerAllocator2> & rhs)
{
  return lhs.static_check == rhs.static_check &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.steering_spd == rhs.steering_spd &&
    lhs.thr_angle == rhs.thr_angle &&
    lhs.brake_pressure == rhs.brake_pressure &&
    lhs.brk_current == rhs.brk_current &&
    lhs.flag == rhs.flag &&
    lhs.engine_ctr == rhs.engine_ctr &&
    lhs.park_brk == rhs.park_brk &&
    lhs.load_brk == rhs.load_brk &&
    lhs.carrier_control == rhs.carrier_control &&
    lhs.dumpbed_ctr == rhs.dumpbed_ctr &&
    lhs.turn_light == rhs.turn_light &&
    lhs.gear_num == rhs.gear_num &&
    lhs.gear_cmd == rhs.gear_cmd &&
    lhs.gear_flag == rhs.gear_flag &&
    lhs.gear_cleardriver == rhs.gear_cleardriver &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.brake_light == rhs.brake_light &&
    lhs.emer_light == rhs.emer_light &&
    lhs.trumpet == rhs.trumpet &&
    lhs.state_light == rhs.state_light &&
    lhs.rest_off_ctr == rhs.rest_off_ctr &&
    lhs.lube_ctr == rhs.lube_ctr &&
    lhs.auto_cmd == rhs.auto_cmd &&
    lhs.override_cmd == rhs.override_cmd &&
    lhs.light_ctr == rhs.light_ctr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_v_control::msg_v_control_<ContainerAllocator1> & lhs, const ::msg_v_control::msg_v_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_v_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_control::msg_v_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_control::msg_v_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_control::msg_v_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_control::msg_v_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_control::msg_v_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_control::msg_v_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_v_control::msg_v_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22edec3cff924e8fcb908dbc10ac7aff";
  }

  static const char* value(const ::msg_v_control::msg_v_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22edec3cff924e8fULL;
  static const uint64_t static_value2 = 0xcb908dbc10ac7affULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_v_control::msg_v_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_v_control/msg_v_control";
  }

  static const char* value(const ::msg_v_control::msg_v_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_v_control::msg_v_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char static_check                 # 0:no commend; 1: checking; 2: pass check; 4: check failed\n"
"float64 steering_angle            # Steering angle. Unit: deg.\n"
"float64 steering_spd              # Steering speed. Unit: deg/s.\n"
"int32 thr_angle                   # Throttle angle. Unit: %.\n"
"float32 brake_pressure            # Brake pressure. Unit: MPa.\n"
"float32 brk_current               # Unit: %.\n"
"char   flag                       # Drive: 1; Brake: 2; Emergency brake: 3.\n"
"char   engine_ctr                 # No operation: 0; turn off: 1; start: 2.\n"
"char   park_brk                   # Turn off: 0; start: 1.\n"
"char   load_brk                   # Turn off: 0; start: 1.\n"
"char   carrier_control            # Rising: 0; keep: 1; floating: 2; decline: 3;\n"
"float32 dumpbed_ctr               # dumpbed level, %\n"
"char   turn_light                 # Turn off: 0; turn on the right: 1; turn on the left: 2;\n"
"int32  gear_num\n"
"int32  gear_cmd\n"
"int32  gear_flag\n"
"int32  gear_cleardriver\n"
"char   dipped_light               # Turn off: 0; turn on the near light: 1; turn on the high beam: 2;\n"
"char   marker_light               # Turn off: 0; turn on: 1;\n"
"char   brake_light                # Turn off: 0; turn on: 1;\n"
"char   emer_light                 # Turn off: 0; turn on: 1;\n"
"char   trumpet                    # Turn off: 0; turn on: 1;\n"
"char   state_light                # Under power state: 0; silent mode: 1; automatic driving mode: 2; remote control mode: 3; Manual driving mode: 4;\n"
"char   rest_off_ctr               # Turn off: 1; turn on: 0;\n"
"char   lube_ctr                   # Turn off: 0; turn on: 1;\n"
"char   auto_cmd                   # Manual: 0; Auto: 1;\n"
"char   override_cmd               # Off: 0; On: 1;\n"
"char   light_ctr                  # Off: 0; Red: 1; Yellow: 2; Blue: 4;\n"
;
  }

  static const char* value(const ::msg_v_control::msg_v_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_v_control::msg_v_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.static_check);
      stream.next(m.steering_angle);
      stream.next(m.steering_spd);
      stream.next(m.thr_angle);
      stream.next(m.brake_pressure);
      stream.next(m.brk_current);
      stream.next(m.flag);
      stream.next(m.engine_ctr);
      stream.next(m.park_brk);
      stream.next(m.load_brk);
      stream.next(m.carrier_control);
      stream.next(m.dumpbed_ctr);
      stream.next(m.turn_light);
      stream.next(m.gear_num);
      stream.next(m.gear_cmd);
      stream.next(m.gear_flag);
      stream.next(m.gear_cleardriver);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.brake_light);
      stream.next(m.emer_light);
      stream.next(m.trumpet);
      stream.next(m.state_light);
      stream.next(m.rest_off_ctr);
      stream.next(m.lube_ctr);
      stream.next(m.auto_cmd);
      stream.next(m.override_cmd);
      stream.next(m.light_ctr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_v_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_v_control::msg_v_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_v_control::msg_v_control_<ContainerAllocator>& v)
  {
    s << indent << "static_check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.static_check);
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
    s << indent << "steering_spd: ";
    Printer<double>::stream(s, indent + "  ", v.steering_spd);
    s << indent << "thr_angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.thr_angle);
    s << indent << "brake_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.brake_pressure);
    s << indent << "brk_current: ";
    Printer<float>::stream(s, indent + "  ", v.brk_current);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "engine_ctr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engine_ctr);
    s << indent << "park_brk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.park_brk);
    s << indent << "load_brk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.load_brk);
    s << indent << "carrier_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrier_control);
    s << indent << "dumpbed_ctr: ";
    Printer<float>::stream(s, indent + "  ", v.dumpbed_ctr);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "gear_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "gear_cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear_cmd);
    s << indent << "gear_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear_flag);
    s << indent << "gear_cleardriver: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear_cleardriver);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "brake_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_light);
    s << indent << "emer_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emer_light);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
    s << indent << "state_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state_light);
    s << indent << "rest_off_ctr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rest_off_ctr);
    s << indent << "lube_ctr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lube_ctr);
    s << indent << "auto_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto_cmd);
    s << indent << "override_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.override_cmd);
    s << indent << "light_ctr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.light_ctr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_V_CONTROL_MESSAGE_MSG_V_CONTROL_H
