# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_perception_safety_status/msg_perception_safety_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_perception_safety_status.msg
import std_msgs.msg

class msg_perception_safety_status(genpy.Message):
  _md5sum = "e0734a6e0d665e44932d6c5009065586"
  _type = "msg_perception_safety_status/msg_perception_safety_status"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header              #frame_id为节点名称
uint8 error_status         #0：正常(心跳信号) n：故障信息个数
SensorErrorInfo[] sensor_error_info

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: msg_perception_safety_status/SensorErrorInfo
int32   sensor_type  # 1:激光 2:相机 3:毫米波 4:感知融合节点【只有程序故障】
int32   sensor_id    # 激光雷达按100/101/102 相机按200/201 毫米波按300/301/302 
string  sensor_name  # 传感器名称，按品牌或厂家；如激光雷达按 "ouster" "leishen"
int32   sensor_position  # 安装位置 1:front 2:back 3:left 4:right 5:front_left 6:front_right 7:back_left 8:back_right
int32   sensor_main    # 0: 非主传感器  1: 主传感器
uint8   sensor_error_status   # 0：正常(心跳信号) 1：异常
int32   sensor_error_code     # 故障编码如下:
# 101:  传感器硬件故障，没有原始数据输出
# 102:  传感器程序故障，没有目标数据输出
# 103:  传感器表面存在异物遮挡（灰尘泥沙等） --需要清洗 
# 104:  传感器表面存在水渍 --需要吹风
# 105:  传感器数据存在损坏现象 --指的是摄像头画面存在异常情况
"""
  __slots__ = ['header','error_status','sensor_error_info']
  _slot_types = ['std_msgs/Header','uint8','msg_perception_safety_status/SensorErrorInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,error_status,sensor_error_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_perception_safety_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.error_status is None:
        self.error_status = 0
      if self.sensor_error_info is None:
        self.sensor_error_info = []
    else:
      self.header = std_msgs.msg.Header()
      self.error_status = 0
      self.sensor_error_info = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.error_status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.sensor_error_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.sensor_error_info:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.sensor_type, _x.sensor_id))
        _x = val1.sensor_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2iBi().pack(_x.sensor_position, _x.sensor_main, _x.sensor_error_status, _x.sensor_error_code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sensor_error_info is None:
        self.sensor_error_info = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.error_status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sensor_error_info = []
      for i in range(0, length):
        val1 = msg_perception_safety_status.msg.SensorErrorInfo()
        _x = val1
        start = end
        end += 8
        (_x.sensor_type, _x.sensor_id,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.sensor_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.sensor_name = str[start:end]
        _x = val1
        start = end
        end += 13
        (_x.sensor_position, _x.sensor_main, _x.sensor_error_status, _x.sensor_error_code,) = _get_struct_2iBi().unpack(str[start:end])
        self.sensor_error_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.error_status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.sensor_error_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.sensor_error_info:
        _x = val1
        buff.write(_get_struct_2i().pack(_x.sensor_type, _x.sensor_id))
        _x = val1.sensor_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2iBi().pack(_x.sensor_position, _x.sensor_main, _x.sensor_error_status, _x.sensor_error_code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sensor_error_info is None:
        self.sensor_error_info = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.error_status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sensor_error_info = []
      for i in range(0, length):
        val1 = msg_perception_safety_status.msg.SensorErrorInfo()
        _x = val1
        start = end
        end += 8
        (_x.sensor_type, _x.sensor_id,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.sensor_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.sensor_name = str[start:end]
        _x = val1
        start = end
        end += 13
        (_x.sensor_position, _x.sensor_main, _x.sensor_error_status, _x.sensor_error_code,) = _get_struct_2iBi().unpack(str[start:end])
        self.sensor_error_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_2iBi = None
def _get_struct_2iBi():
    global _struct_2iBi
    if _struct_2iBi is None:
        _struct_2iBi = struct.Struct("<2iBi")
    return _struct_2iBi
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
