// Generated by gencpp from file msg_common/GridPoint.msg
// DO NOT EDIT!


#ifndef MSG_COMMON_MESSAGE_GRIDPOINT_H
#define MSG_COMMON_MESSAGE_GRIDPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_common
{
template <class ContainerAllocator>
struct GridPoint_
{
  typedef GridPoint_<ContainerAllocator> Type;

  GridPoint_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , length(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  GridPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , length(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::msg_common::GridPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_common::GridPoint_<ContainerAllocator> const> ConstPtr;

}; // struct GridPoint_

typedef ::msg_common::GridPoint_<std::allocator<void> > GridPoint;

typedef boost::shared_ptr< ::msg_common::GridPoint > GridPointPtr;
typedef boost::shared_ptr< ::msg_common::GridPoint const> GridPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_common::GridPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_common::GridPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_common::GridPoint_<ContainerAllocator1> & lhs, const ::msg_common::GridPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_common::GridPoint_<ContainerAllocator1> & lhs, const ::msg_common::GridPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_common::GridPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_common::GridPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_common::GridPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_common::GridPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_common::GridPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_common::GridPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_common::GridPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da3e3e4a9ff49b9481ad892ff001f2e8";
  }

  static const char* value(const ::msg_common::GridPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda3e3e4a9ff49b94ULL;
  static const uint64_t static_value2 = 0x81ad892ff001f2e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_common::GridPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_common/GridPoint";
  }

  static const char* value(const ::msg_common::GridPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_common::GridPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
;
  }

  static const char* value(const ::msg_common::GridPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_common::GridPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_common::GridPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_common::GridPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_COMMON_MESSAGE_GRIDPOINT_H
