// Generated by gencpp from file msg_common/obstacle_pt.msg
// DO NOT EDIT!


#ifndef MSG_COMMON_MESSAGE_OBSTACLE_PT_H
#define MSG_COMMON_MESSAGE_OBSTACLE_PT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_common
{
template <class ContainerAllocator>
struct obstacle_pt_
{
  typedef obstacle_pt_<ContainerAllocator> Type;

  obstacle_pt_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  obstacle_pt_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::msg_common::obstacle_pt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_common::obstacle_pt_<ContainerAllocator> const> ConstPtr;

}; // struct obstacle_pt_

typedef ::msg_common::obstacle_pt_<std::allocator<void> > obstacle_pt;

typedef boost::shared_ptr< ::msg_common::obstacle_pt > obstacle_ptPtr;
typedef boost::shared_ptr< ::msg_common::obstacle_pt const> obstacle_ptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_common::obstacle_pt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_common::obstacle_pt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_common::obstacle_pt_<ContainerAllocator1> & lhs, const ::msg_common::obstacle_pt_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_common::obstacle_pt_<ContainerAllocator1> & lhs, const ::msg_common::obstacle_pt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_common::obstacle_pt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_common::obstacle_pt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_common::obstacle_pt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_common::obstacle_pt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_common::obstacle_pt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_common::obstacle_pt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_common::obstacle_pt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::msg_common::obstacle_pt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_common::obstacle_pt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_common/obstacle_pt";
  }

  static const char* value(const ::msg_common::obstacle_pt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_common::obstacle_pt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::msg_common::obstacle_pt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_common::obstacle_pt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacle_pt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_common::obstacle_pt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_common::obstacle_pt_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_COMMON_MESSAGE_OBSTACLE_PT_H
