// Generated by gencpp from file msg_common/WayPoint.msg
// DO NOT EDIT!


#ifndef MSG_COMMON_MESSAGE_WAYPOINT_H
#define MSG_COMMON_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_common
{
template <class ContainerAllocator>
struct WayPoint_
{
  typedef WayPoint_<ContainerAllocator> Type;

  WayPoint_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , left(0.0)
    , right(0.0)
    , heading_angle(0.0)
    , curvature(0.0)
    , speed(0.0)
    , distance(0.0)
    , slope(0.0)
    , attribute(0)
    , speed_limit(0.0)
    , direction(0)
    , waypointattr(0)
    , t(0.0)
    , area_name()
    , onareaid()  {
    }
  WayPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , left(0.0)
    , right(0.0)
    , heading_angle(0.0)
    , curvature(0.0)
    , speed(0.0)
    , distance(0.0)
    , slope(0.0)
    , attribute(0)
    , speed_limit(0.0)
    , direction(0)
    , waypointattr(0)
    , t(0.0)
    , area_name(_alloc)
    , onareaid(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;

   typedef float _heading_angle_type;
  _heading_angle_type heading_angle;

   typedef float _curvature_type;
  _curvature_type curvature;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _slope_type;
  _slope_type slope;

   typedef uint32_t _attribute_type;
  _attribute_type attribute;

   typedef float _speed_limit_type;
  _speed_limit_type speed_limit;

   typedef uint8_t _direction_type;
  _direction_type direction;

   typedef uint8_t _waypointattr_type;
  _waypointattr_type waypointattr;

   typedef double _t_type;
  _t_type t;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _area_name_type;
  _area_name_type area_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _onareaid_type;
  _onareaid_type onareaid;





  typedef boost::shared_ptr< ::msg_common::WayPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_common::WayPoint_<ContainerAllocator> const> ConstPtr;

}; // struct WayPoint_

typedef ::msg_common::WayPoint_<std::allocator<void> > WayPoint;

typedef boost::shared_ptr< ::msg_common::WayPoint > WayPointPtr;
typedef boost::shared_ptr< ::msg_common::WayPoint const> WayPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_common::WayPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_common::WayPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_common::WayPoint_<ContainerAllocator1> & lhs, const ::msg_common::WayPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.heading_angle == rhs.heading_angle &&
    lhs.curvature == rhs.curvature &&
    lhs.speed == rhs.speed &&
    lhs.distance == rhs.distance &&
    lhs.slope == rhs.slope &&
    lhs.attribute == rhs.attribute &&
    lhs.speed_limit == rhs.speed_limit &&
    lhs.direction == rhs.direction &&
    lhs.waypointattr == rhs.waypointattr &&
    lhs.t == rhs.t &&
    lhs.area_name == rhs.area_name &&
    lhs.onareaid == rhs.onareaid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_common::WayPoint_<ContainerAllocator1> & lhs, const ::msg_common::WayPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_common::WayPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_common::WayPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_common::WayPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_common::WayPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_common::WayPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_common::WayPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_common::WayPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14ccf02ddc37a7bf62cf9c7f57bc1b66";
  }

  static const char* value(const ::msg_common::WayPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14ccf02ddc37a7bfULL;
  static const uint64_t static_value2 = 0x62cf9c7f57bc1b66ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_common::WayPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_common/WayPoint";
  }

  static const char* value(const ::msg_common::WayPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_common::WayPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x			#路径x坐标\n"
"float64 y			#路径y坐标\n"
"float64 z			#路径z坐标\n"
"float64 left			#距左边界值\n"
"float64 right			#距右边界值\n"
"float32 heading_angle		#路径的方向\n"
"float32 curvature		#曲率\n"
"float32 speed			#路径的速度\n"
"float32 distance		#路点与路径起点沿路径的距离\n"
"float32 slope			#坡度信息\n"
"uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)\n"
"float32 speed_limit	        #速度上限\n"
"uint8 direction			#0表示前进，1表示后退\n"
"uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点\n"
"float64 t			#时间\n"
"string area_name		#区域名称	\n"
"string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	\n"
;
  }

  static const char* value(const ::msg_common::WayPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_common::WayPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.heading_angle);
      stream.next(m.curvature);
      stream.next(m.speed);
      stream.next(m.distance);
      stream.next(m.slope);
      stream.next(m.attribute);
      stream.next(m.speed_limit);
      stream.next(m.direction);
      stream.next(m.waypointattr);
      stream.next(m.t);
      stream.next(m.area_name);
      stream.next(m.onareaid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_common::WayPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_common::WayPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
    s << indent << "heading_angle: ";
    Printer<float>::stream(s, indent + "  ", v.heading_angle);
    s << indent << "curvature: ";
    Printer<float>::stream(s, indent + "  ", v.curvature);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "slope: ";
    Printer<float>::stream(s, indent + "  ", v.slope);
    s << indent << "attribute: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.attribute);
    s << indent << "speed_limit: ";
    Printer<float>::stream(s, indent + "  ", v.speed_limit);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "waypointattr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.waypointattr);
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
    s << indent << "area_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.area_name);
    s << indent << "onareaid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.onareaid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_COMMON_MESSAGE_WAYPOINT_H
