// Generated by gencpp from file msg_map_collect/msg_map_collect.msg
// DO NOT EDIT!


#ifndef MSG_MAP_COLLECT_MESSAGE_MSG_MAP_COLLECT_H
#define MSG_MAP_COLLECT_MESSAGE_MSG_MAP_COLLECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_map_collect
{
template <class ContainerAllocator>
struct msg_map_collect_
{
  typedef msg_map_collect_<ContainerAllocator> Type;

  msg_map_collect_()
    : utm_x(0.0)
    , utm_y(0.0)
    , utm_z(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , yaw_angle(0.0)
    , velocity(0.0)
    , curvature(0.0)
    , reverse(0.0)  {
    }
  msg_map_collect_(const ContainerAllocator& _alloc)
    : utm_x(0.0)
    , utm_y(0.0)
    , utm_z(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , yaw_angle(0.0)
    , velocity(0.0)
    , curvature(0.0)
    , reverse(0.0)  {
  (void)_alloc;
    }



   typedef double _utm_x_type;
  _utm_x_type utm_x;

   typedef double _utm_y_type;
  _utm_y_type utm_y;

   typedef double _utm_z_type;
  _utm_z_type utm_z;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _yaw_angle_type;
  _yaw_angle_type yaw_angle;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _curvature_type;
  _curvature_type curvature;

   typedef double _reverse_type;
  _reverse_type reverse;





  typedef boost::shared_ptr< ::msg_map_collect::msg_map_collect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_map_collect::msg_map_collect_<ContainerAllocator> const> ConstPtr;

}; // struct msg_map_collect_

typedef ::msg_map_collect::msg_map_collect_<std::allocator<void> > msg_map_collect;

typedef boost::shared_ptr< ::msg_map_collect::msg_map_collect > msg_map_collectPtr;
typedef boost::shared_ptr< ::msg_map_collect::msg_map_collect const> msg_map_collectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_map_collect::msg_map_collect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_map_collect::msg_map_collect_<ContainerAllocator1> & lhs, const ::msg_map_collect::msg_map_collect_<ContainerAllocator2> & rhs)
{
  return lhs.utm_x == rhs.utm_x &&
    lhs.utm_y == rhs.utm_y &&
    lhs.utm_z == rhs.utm_z &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.yaw_angle == rhs.yaw_angle &&
    lhs.velocity == rhs.velocity &&
    lhs.curvature == rhs.curvature &&
    lhs.reverse == rhs.reverse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_map_collect::msg_map_collect_<ContainerAllocator1> & lhs, const ::msg_map_collect::msg_map_collect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_map_collect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_map_collect::msg_map_collect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_map_collect::msg_map_collect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_map_collect::msg_map_collect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d779b4b9939c4c408181869ed8126f52";
  }

  static const char* value(const ::msg_map_collect::msg_map_collect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd779b4b9939c4c40ULL;
  static const uint64_t static_value2 = 0x8181869ed8126f52ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_map_collect/msg_map_collect";
  }

  static const char* value(const ::msg_map_collect::msg_map_collect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 utm_x		#大地坐标系x坐标\n"
"float64 utm_y		#大地坐标系y坐标\n"
"float64 utm_z		#大地坐标系z坐标\n"
"float64 latitude	#纬度\n"
"float64 longitude	#经度\n"
"float64 yaw_angle	#偏航角\n"
"float64 velocity	#车辆速度\n"
"float64 curvature	#曲率\n"
"float64 reverse		#倒档  0前进  1倒车\n"
;
  }

  static const char* value(const ::msg_map_collect::msg_map_collect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.utm_x);
      stream.next(m.utm_y);
      stream.next(m.utm_z);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.yaw_angle);
      stream.next(m.velocity);
      stream.next(m.curvature);
      stream.next(m.reverse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_map_collect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_map_collect::msg_map_collect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_map_collect::msg_map_collect_<ContainerAllocator>& v)
  {
    s << indent << "utm_x: ";
    Printer<double>::stream(s, indent + "  ", v.utm_x);
    s << indent << "utm_y: ";
    Printer<double>::stream(s, indent + "  ", v.utm_y);
    s << indent << "utm_z: ";
    Printer<double>::stream(s, indent + "  ", v.utm_z);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "yaw_angle: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_angle);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "curvature: ";
    Printer<double>::stream(s, indent + "  ", v.curvature);
    s << indent << "reverse: ";
    Printer<double>::stream(s, indent + "  ", v.reverse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_MAP_COLLECT_MESSAGE_MSG_MAP_COLLECT_H
