(cl:in-package msg_lidar_shape-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          VALID-VAL
          VALID
          ABSOLUTE_MOTION-VAL
          ABSOLUTE_MOTION
          SPACE_FRAME-VAL
          SPACE_FRAME
          POSE-VAL
          POSE
          DIMENSIONS-VAL
          DIMENSIONS
          VARIANCE-VAL
          VARIANCE
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          POINTCLOUD-VAL
          POINTCLOUD
          LINE_LIST-VAL
          LINE_LIST
          CONVEX_HULL-VAL
          CONVEX_HULL
          CANDIDATE_TRAJECTORIES-VAL
          CANDIDATE_TRAJECTORIES
          POSE_RELIABLE-VAL
          POSE_RELIABLE
          VELOCITY_RELIABLE-VAL
          VELOCITY_RELIABLE
          ACCELERATION_RELIABLE-VAL
          ACCELERATION_RELIABLE
          IMAGE_FRAME-VAL
          IMAGE_FRAME
          X-VAL
          X
          Y-VAL
          Y
          X_BOTTOM_LEFT-VAL
          X_BOTTOM_LEFT
          Y_BOTTOM_LEFT-VAL
          Y_BOTTOM_LEFT
          X_BOTTOM_CENT-VAL
          X_BOTTOM_CENT
          Y_BOTTOM_CENT-VAL
          Y_BOTTOM_CENT
          X_BOTTOM_RIGHT-VAL
          X_BOTTOM_RIGHT
          Y_BOTTOM_RIGHT-VAL
          Y_BOTTOM_RIGHT
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          ANGLE-VAL
          ANGLE
          ROI_IMAGE-VAL
          ROI_IMAGE
          INDICATOR_STATE-VAL
          INDICATOR_STATE
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          USER_DEFINED_INFO-VAL
          USER_DEFINED_INFO
))