// Generated by gencpp from file msg_global_planning/msg_report_version.msg
// DO NOT EDIT!


#ifndef MSG_GLOBAL_PLANNING_MESSAGE_MSG_REPORT_VERSION_H
#define MSG_GLOBAL_PLANNING_MESSAGE_MSG_REPORT_VERSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_global_planning
{
template <class ContainerAllocator>
struct msg_report_version_
{
  typedef msg_report_version_<ContainerAllocator> Type;

  msg_report_version_()
    : str_version()  {
    }
  msg_report_version_(const ContainerAllocator& _alloc)
    : str_version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str_version_type;
  _str_version_type str_version;





  typedef boost::shared_ptr< ::msg_global_planning::msg_report_version_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_global_planning::msg_report_version_<ContainerAllocator> const> ConstPtr;

}; // struct msg_report_version_

typedef ::msg_global_planning::msg_report_version_<std::allocator<void> > msg_report_version;

typedef boost::shared_ptr< ::msg_global_planning::msg_report_version > msg_report_versionPtr;
typedef boost::shared_ptr< ::msg_global_planning::msg_report_version const> msg_report_versionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_global_planning::msg_report_version_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_global_planning::msg_report_version_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_global_planning::msg_report_version_<ContainerAllocator1> & lhs, const ::msg_global_planning::msg_report_version_<ContainerAllocator2> & rhs)
{
  return lhs.str_version == rhs.str_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_global_planning::msg_report_version_<ContainerAllocator1> & lhs, const ::msg_global_planning::msg_report_version_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_global_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_global_planning::msg_report_version_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_global_planning::msg_report_version_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_global_planning::msg_report_version_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9772dfc007d61d46df9ffce2fef4d876";
  }

  static const char* value(const ::msg_global_planning::msg_report_version_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9772dfc007d61d46ULL;
  static const uint64_t static_value2 = 0xdf9ffce2fef4d876ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_global_planning/msg_report_version";
  }

  static const char* value(const ::msg_global_planning::msg_report_version_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string   str_version 	#地图版本\n"
;
  }

  static const char* value(const ::msg_global_planning::msg_report_version_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_report_version_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_global_planning::msg_report_version_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_global_planning::msg_report_version_<ContainerAllocator>& v)
  {
    s << indent << "str_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GLOBAL_PLANNING_MESSAGE_MSG_REPORT_VERSION_H
