// Generated by gencpp from file msg_global_planning/msg_global_planning.msg
// DO NOT EDIT!


#ifndef MSG_GLOBAL_PLANNING_MESSAGE_MSG_GLOBAL_PLANNING_H
#define MSG_GLOBAL_PLANNING_MESSAGE_MSG_GLOBAL_PLANNING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_common/WayPoint.h>

namespace msg_global_planning
{
template <class ContainerAllocator>
struct msg_global_planning_
{
  typedef msg_global_planning_<ContainerAllocator> Type;

  msg_global_planning_()
    : target_id(0)
    , way_point()
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0.0)
    , traj_id(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , emer_light(0)
    , trumpet(0)
    , path_array()  {
    }
  msg_global_planning_(const ContainerAllocator& _alloc)
    : target_id(0)
    , way_point(_alloc)
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0.0)
    , traj_id(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , emer_light(0)
    , trumpet(0)
    , path_array(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _target_id_type;
  _target_id_type target_id;

   typedef std::vector< ::msg_common::WayPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_common::WayPoint_<ContainerAllocator> >> _way_point_type;
  _way_point_type way_point;

   typedef float _remote_spd_type;
  _remote_spd_type remote_spd;

   typedef float _remote_steering_type;
  _remote_steering_type remote_steering;

   typedef float _remote_parking_type;
  _remote_parking_type remote_parking;

   typedef uint32_t _traj_id_type;
  _traj_id_type traj_id;

   typedef uint8_t _gear_num_type;
  _gear_num_type gear_num;

   typedef uint8_t _carrier_control_type;
  _carrier_control_type carrier_control;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _emer_light_type;
  _emer_light_type emer_light;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _path_array_type;
  _path_array_type path_array;





  typedef boost::shared_ptr< ::msg_global_planning::msg_global_planning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_global_planning::msg_global_planning_<ContainerAllocator> const> ConstPtr;

}; // struct msg_global_planning_

typedef ::msg_global_planning::msg_global_planning_<std::allocator<void> > msg_global_planning;

typedef boost::shared_ptr< ::msg_global_planning::msg_global_planning > msg_global_planningPtr;
typedef boost::shared_ptr< ::msg_global_planning::msg_global_planning const> msg_global_planningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_global_planning::msg_global_planning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_global_planning::msg_global_planning_<ContainerAllocator1> & lhs, const ::msg_global_planning::msg_global_planning_<ContainerAllocator2> & rhs)
{
  return lhs.target_id == rhs.target_id &&
    lhs.way_point == rhs.way_point &&
    lhs.remote_spd == rhs.remote_spd &&
    lhs.remote_steering == rhs.remote_steering &&
    lhs.remote_parking == rhs.remote_parking &&
    lhs.traj_id == rhs.traj_id &&
    lhs.gear_num == rhs.gear_num &&
    lhs.carrier_control == rhs.carrier_control &&
    lhs.turn_light == rhs.turn_light &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.emer_light == rhs.emer_light &&
    lhs.trumpet == rhs.trumpet &&
    lhs.path_array == rhs.path_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_global_planning::msg_global_planning_<ContainerAllocator1> & lhs, const ::msg_global_planning::msg_global_planning_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_global_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_global_planning::msg_global_planning_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_global_planning::msg_global_planning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_global_planning::msg_global_planning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "795e276f86cc7924b4ca1a4fae9f02fc";
  }

  static const char* value(const ::msg_global_planning::msg_global_planning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x795e276f86cc7924ULL;
  static const uint64_t static_value2 = 0xb4ca1a4fae9f02fcULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_global_planning/msg_global_planning";
  }

  static const char* value(const ::msg_global_planning::msg_global_planning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 target_id	        #target_id\n"
"msg_common/WayPoint[] way_point		#路径\n"
"float32 remote_spd\n"
"float32 remote_steering\n"
"float32 remote_parking\n"
"uint32 traj_id\n"
"uint8 gear_num 			#档位\n"
"uint8 carrier_control		#货舱控制信号\n"
"uint8 turn_light		#转向灯信号\n"
"uint8 dipped_light		#近光灯信号\n"
"uint8 marker_light		#示廓灯信号\n"
"uint8 emer_light		#紧急信号灯信号\n"
"uint8 trumpet			#喇叭信号\n"
"string[] path_array		#路由路径，成员为区域名 \n"
"\n"
"\n"
"================================================================================\n"
"MSG: msg_common/WayPoint\n"
"float64 x			#路径x坐标\n"
"float64 y			#路径y坐标\n"
"float64 z			#路径z坐标\n"
"float64 left			#距左边界值\n"
"float64 right			#距右边界值\n"
"float32 heading_angle		#路径的方向\n"
"float32 curvature		#曲率\n"
"float32 speed			#路径的速度\n"
"float32 distance		#路点与路径起点沿路径的距离\n"
"float32 slope			#坡度信息\n"
"uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)\n"
"float32 speed_limit	        #速度上限\n"
"uint8 direction			#0表示前进，1表示后退\n"
"uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点\n"
"float64 t			#时间\n"
"string area_name		#区域名称	\n"
"string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	\n"
;
  }

  static const char* value(const ::msg_global_planning::msg_global_planning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_id);
      stream.next(m.way_point);
      stream.next(m.remote_spd);
      stream.next(m.remote_steering);
      stream.next(m.remote_parking);
      stream.next(m.traj_id);
      stream.next(m.gear_num);
      stream.next(m.carrier_control);
      stream.next(m.turn_light);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.emer_light);
      stream.next(m.trumpet);
      stream.next(m.path_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_global_planning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_global_planning::msg_global_planning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_global_planning::msg_global_planning_<ContainerAllocator>& v)
  {
    s << indent << "target_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_id);
    s << indent << "way_point[]" << std::endl;
    for (size_t i = 0; i < v.way_point.size(); ++i)
    {
      s << indent << "  way_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_common::WayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.way_point[i]);
    }
    s << indent << "remote_spd: ";
    Printer<float>::stream(s, indent + "  ", v.remote_spd);
    s << indent << "remote_steering: ";
    Printer<float>::stream(s, indent + "  ", v.remote_steering);
    s << indent << "remote_parking: ";
    Printer<float>::stream(s, indent + "  ", v.remote_parking);
    s << indent << "traj_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "gear_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "carrier_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrier_control);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "emer_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emer_light);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
    s << indent << "path_array[]" << std::endl;
    for (size_t i = 0; i < v.path_array.size(); ++i)
    {
      s << indent << "  path_array[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.path_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GLOBAL_PLANNING_MESSAGE_MSG_GLOBAL_PLANNING_H
