(cl:in-package msg_v_control-msg)
(cl:export '(STATIC_CHECK-VAL
          STATIC_CHECK
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          STEERING_SPD-VAL
          STEERING_SPD
          THR_ANGLE-VAL
          THR_ANGLE
          BRAKE_PRESSURE-VAL
          BRAKE_PRESSURE
          BRK_CURRENT-VAL
          BRK_CURRENT
          FLAG-VAL
          FLAG
          ENGINE_CTR-VAL
          ENGINE_CTR
          PARK_BRK-VAL
          PARK_BRK
          LOAD_BRK-VAL
          LOAD_BRK
          CARRIER_CONTROL-VAL
          CARRIER_CONTROL
          DUMPBED_CTR-VAL
          DUMPBED_CTR
          TURN_LIGHT-VAL
          TURN_LIGHT
          GEAR_NUM-VAL
          GEAR_NUM
          GEAR_CMD-VAL
          GEAR_CMD
          GEAR_FLAG-VAL
          GEAR_FLAG
          GEAR_CLEARDRIVER-VAL
          GEAR_CLEARDRIVER
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          TRUMPET-VAL
          TRUMPET
          STATE_LIGHT-VAL
          STATE_LIGHT
          REST_OFF_CTR-VAL
          REST_OFF_CTR
          LUBE_CTR-VAL
          LUBE_CTR
          AUTO_CMD-VAL
          AUTO_CMD
          OVERRIDE_CMD-VAL
          OVERRIDE_CMD
          LIGHT_CTR-VAL
          LIGHT_CTR
))