(cl:in-package msg_v_decision-msg)
(cl:export '(TASK_MODE-VAL
          TASK_MODE
          TARGET_ID-VAL
          TARGET_ID
          TASK_NUM-VAL
          TASK_NUM
          TASK_STATE-VAL
          TASK_STATE
          SYSTEM_STATE-VAL
          SYSTEM_STATE
          OBJ_FUSE-VAL
          OBJ_FUSE
          TARGET_OBSTACLE-VAL
          TARGET_OBSTACLE
          DIS2FRONT-VAL
          DIS2FRONT
          DISTANCE2VEHICLE-VAL
          DISTANCE2VEHICLE
          DISTANCE2OBSTACLE-VAL
          DISTANCE2OBSTACLE
          FAULT_INFO-VAL
          FAULT_INFO
          EVENT_REPORT-VAL
          EVENT_REPORT
          MODE-VAL
          MODE
          IS_UPDATE_MAP-VAL
          IS_UPDATE_MAP
          TRAJ_ID-VAL
          TRAJ_ID
          WAY_POINT-VAL
          WAY_POINT
          REMOTE_SPD-VAL
          REMOTE_SPD
          REMOTE_STEERING-VAL
          REMOTE_STEERING
          REMOTE_PARKING-VAL
          REMOTE_PARKING
          REMOTE_STOPENGINE-VAL
          REMOTE_STOPENGINE
          REMOTE_SERVICE_BRAKE-VAL
          REMOTE_SERVICE_BRAKE
          REMOTE_PARK_BRAKE-VAL
          REMOTE_PARK_BRAKE
          REMOTE_LOAD_BRAKE-VAL
          REMOTE_LOAD_BRAKE
          GEAR_NUM-VAL
          GEAR_NUM
          CARRIER_CONTROL-VAL
          CARRIER_CONTROL
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          TRUMPET-VAL
          TRUMPET
          IS_CLEAN-VAL
          IS_CLEAN
))