# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_map_collect/msg_map_collect.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class msg_map_collect(genpy.Message):
  _md5sum = "d779b4b9939c4c408181869ed8126f52"
  _type = "msg_map_collect/msg_map_collect"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 utm_x		#大地坐标系x坐标
float64 utm_y		#大地坐标系y坐标
float64 utm_z		#大地坐标系z坐标
float64 latitude	#纬度
float64 longitude	#经度
float64 yaw_angle	#偏航角
float64 velocity	#车辆速度
float64 curvature	#曲率
float64 reverse		#倒档  0前进  1倒车
"""
  __slots__ = ['utm_x','utm_y','utm_z','latitude','longitude','yaw_angle','velocity','curvature','reverse']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       utm_x,utm_y,utm_z,latitude,longitude,yaw_angle,velocity,curvature,reverse

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_map_collect, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.utm_x is None:
        self.utm_x = 0.
      if self.utm_y is None:
        self.utm_y = 0.
      if self.utm_z is None:
        self.utm_z = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.yaw_angle is None:
        self.yaw_angle = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.curvature is None:
        self.curvature = 0.
      if self.reverse is None:
        self.reverse = 0.
    else:
      self.utm_x = 0.
      self.utm_y = 0.
      self.utm_z = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.yaw_angle = 0.
      self.velocity = 0.
      self.curvature = 0.
      self.reverse = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.utm_x, _x.utm_y, _x.utm_z, _x.latitude, _x.longitude, _x.yaw_angle, _x.velocity, _x.curvature, _x.reverse))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.utm_x, _x.utm_y, _x.utm_z, _x.latitude, _x.longitude, _x.yaw_angle, _x.velocity, _x.curvature, _x.reverse,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.utm_x, _x.utm_y, _x.utm_z, _x.latitude, _x.longitude, _x.yaw_angle, _x.velocity, _x.curvature, _x.reverse))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.utm_x, _x.utm_y, _x.utm_z, _x.latitude, _x.longitude, _x.yaw_angle, _x.velocity, _x.curvature, _x.reverse,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
