# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_info_router/msg_info_router.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_common.msg
import msg_info_router.msg

class msg_info_router(genpy.Message):
  _md5sum = "48626aa112e3a63e18582859d48dcf2e"
  _type = "msg_info_router/msg_info_router"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 mode 	#当前模式  	0:驾驶员驾驶(手动); 1:自动驾驶授权（地面自动驾驶）; 2:遥控
uint16 task_type	#当前任务  	0:保留; 1:前往装载点; 2:前往装载区候车区; 3:前往卸载点; 4:前往卸载候车区; 5:前往停车场停车点; 6:前往停车候车区
uint16 task_num	#任务编号  
uint16 segments_num	#全局路径分段数
uint16 cur_segments_num	#当前段数
uint16 state_type 	#状态类型  	0:保留; 1:自检; 2:启动发动机; 3:静态测试; 4:轨迹跟随; 5:排队停车; 6:跟车模式; 7:后台轨迹跟随; 8:卸载模式; 9:装载模式; 10:安全停车; 11:关闭发动机; 12:紧急停车; 13:待机；14:装载完成；
msg_common/WayPoint[] path_point	#轨迹点信息
Point stop_point		        #目标停车点
bool is_update_map		      #地图是否更新
float32 remote_spd		      #期望车速
float32 remote_steering	    #方向盘转角
float32 remote_parking		  #紧急停车指令
uint8 remote_stopengine	    #发动机停止信号
uint8 remote_service_brake 	#行车制动信号
uint8 remote_park_brake 	  #停车制动信号
uint8 remote_load_brake 	  #装载制动信号
uint8 gear_num    		  #期望档位
uint8 carrier_control  	#货舱控制信号
uint8 turn_light  		  #转向灯信号
uint8 dipped_light  		#远近光灯信号
uint8 marker_light  		#示廓灯信号
uint8 fog_light  		    #前雾灯信号
uint8 brake_light  		  #刹车灯信号
uint8 emer_light  		  #紧急灯信号
uint8 wiper_sign		    #雨刮控制信号
uint8 trumpet   		    #喇叭信号

================================================================================
MSG: msg_common/WayPoint
float64 x			#路径x坐标
float64 y			#路径y坐标
float64 z			#路径z坐标
float64 left			#距左边界值
float64 right			#距右边界值
float32 heading_angle		#路径的方向
float32 curvature		#曲率
float32 speed			#路径的速度
float32 distance		#路点与路径起点沿路径的距离
float32 slope			#坡度信息
uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)
float32 speed_limit	        #速度上限
uint8 direction			#0表示前进，1表示后退
uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点
float64 t			#时间
string area_name		#区域名称	
string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	

================================================================================
MSG: msg_info_router/Point
float64 x   		#大地坐标系x轴坐标
float64 y   		#大地坐标系y轴坐标
float32 heading_angle  	#航行角
"""
  __slots__ = ['mode','task_type','task_num','segments_num','cur_segments_num','state_type','path_point','stop_point','is_update_map','remote_spd','remote_steering','remote_parking','remote_stopengine','remote_service_brake','remote_park_brake','remote_load_brake','gear_num','carrier_control','turn_light','dipped_light','marker_light','fog_light','brake_light','emer_light','wiper_sign','trumpet']
  _slot_types = ['uint8','uint16','uint16','uint16','uint16','uint16','msg_common/WayPoint[]','msg_info_router/Point','bool','float32','float32','float32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,task_type,task_num,segments_num,cur_segments_num,state_type,path_point,stop_point,is_update_map,remote_spd,remote_steering,remote_parking,remote_stopengine,remote_service_brake,remote_park_brake,remote_load_brake,gear_num,carrier_control,turn_light,dipped_light,marker_light,fog_light,brake_light,emer_light,wiper_sign,trumpet

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_info_router, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = 0
      if self.task_type is None:
        self.task_type = 0
      if self.task_num is None:
        self.task_num = 0
      if self.segments_num is None:
        self.segments_num = 0
      if self.cur_segments_num is None:
        self.cur_segments_num = 0
      if self.state_type is None:
        self.state_type = 0
      if self.path_point is None:
        self.path_point = []
      if self.stop_point is None:
        self.stop_point = msg_info_router.msg.Point()
      if self.is_update_map is None:
        self.is_update_map = False
      if self.remote_spd is None:
        self.remote_spd = 0.
      if self.remote_steering is None:
        self.remote_steering = 0.
      if self.remote_parking is None:
        self.remote_parking = 0.
      if self.remote_stopengine is None:
        self.remote_stopengine = 0
      if self.remote_service_brake is None:
        self.remote_service_brake = 0
      if self.remote_park_brake is None:
        self.remote_park_brake = 0
      if self.remote_load_brake is None:
        self.remote_load_brake = 0
      if self.gear_num is None:
        self.gear_num = 0
      if self.carrier_control is None:
        self.carrier_control = 0
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.fog_light is None:
        self.fog_light = 0
      if self.brake_light is None:
        self.brake_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.wiper_sign is None:
        self.wiper_sign = 0
      if self.trumpet is None:
        self.trumpet = 0
    else:
      self.mode = 0
      self.task_type = 0
      self.task_num = 0
      self.segments_num = 0
      self.cur_segments_num = 0
      self.state_type = 0
      self.path_point = []
      self.stop_point = msg_info_router.msg.Point()
      self.is_update_map = False
      self.remote_spd = 0.
      self.remote_steering = 0.
      self.remote_parking = 0.
      self.remote_stopengine = 0
      self.remote_service_brake = 0
      self.remote_park_brake = 0
      self.remote_load_brake = 0
      self.gear_num = 0
      self.carrier_control = 0
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.fog_light = 0
      self.brake_light = 0
      self.emer_light = 0
      self.wiper_sign = 0
      self.trumpet = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B5H().pack(_x.mode, _x.task_type, _x.task_num, _x.segments_num, _x.cur_segments_num, _x.state_type))
      length = len(self.path_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.path_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dfB3f14B().pack(_x.stop_point.x, _x.stop_point.y, _x.stop_point.heading_angle, _x.is_update_map, _x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.fog_light, _x.brake_light, _x.emer_light, _x.wiper_sign, _x.trumpet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.path_point is None:
        self.path_point = None
      if self.stop_point is None:
        self.stop_point = msg_info_router.msg.Point()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.mode, _x.task_type, _x.task_num, _x.segments_num, _x.cur_segments_num, _x.state_type,) = _get_struct_B5H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.path_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.path_point.append(val1)
      _x = self
      start = end
      end += 47
      (_x.stop_point.x, _x.stop_point.y, _x.stop_point.heading_angle, _x.is_update_map, _x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.fog_light, _x.brake_light, _x.emer_light, _x.wiper_sign, _x.trumpet,) = _get_struct_2dfB3f14B().unpack(str[start:end])
      self.is_update_map = bool(self.is_update_map)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B5H().pack(_x.mode, _x.task_type, _x.task_num, _x.segments_num, _x.cur_segments_num, _x.state_type))
      length = len(self.path_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.path_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dfB3f14B().pack(_x.stop_point.x, _x.stop_point.y, _x.stop_point.heading_angle, _x.is_update_map, _x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.fog_light, _x.brake_light, _x.emer_light, _x.wiper_sign, _x.trumpet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.path_point is None:
        self.path_point = None
      if self.stop_point is None:
        self.stop_point = msg_info_router.msg.Point()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.mode, _x.task_type, _x.task_num, _x.segments_num, _x.cur_segments_num, _x.state_type,) = _get_struct_B5H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.path_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.path_point.append(val1)
      _x = self
      start = end
      end += 47
      (_x.stop_point.x, _x.stop_point.y, _x.stop_point.heading_angle, _x.is_update_map, _x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.fog_light, _x.brake_light, _x.emer_light, _x.wiper_sign, _x.trumpet,) = _get_struct_2dfB3f14B().unpack(str[start:end])
      self.is_update_map = bool(self.is_update_map)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dfB3f14B = None
def _get_struct_2dfB3f14B():
    global _struct_2dfB3f14B
    if _struct_2dfB3f14B is None:
        _struct_2dfB3f14B = struct.Struct("<2dfB3f14B")
    return _struct_2dfB3f14B
_struct_5d5fIf2Bd = None
def _get_struct_5d5fIf2Bd():
    global _struct_5d5fIf2Bd
    if _struct_5d5fIf2Bd is None:
        _struct_5d5fIf2Bd = struct.Struct("<5d5fIf2Bd")
    return _struct_5d5fIf2Bd
_struct_B5H = None
def _get_struct_B5H():
    global _struct_B5H
    if _struct_B5H is None:
        _struct_B5H = struct.Struct("<B5H")
    return _struct_B5H
