# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_local_planning/msg_local_planning.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_common.msg

class msg_local_planning(genpy.Message):
  _md5sum = "be10eb2ba128758006e99f566fb3265b"
  _type = "msg_local_planning/msg_local_planning"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16  target_id  		#任务指令编号 0自检  1启动发动机  2静态测试 .....
uint32 traj_id
msg_common/WayPoint[] way_point  	#正常行驶模式规划的轨迹
float32 remote_spd	#遥控模式：期望速度	
float32 remote_steering	#遥控模式：方向盘转角	单位：deg 范围：-720 ~ 720（左转为正）
uint8 remote_parking	#遥控模式：驻车制动	0：无驻车制动1：驻车制动
uint8 remote_stopengine
uint8 remote_service_brake #行车制动
uint8 remote_park_brake #停车制动
uint8 remote_load_brake #装载制动
uint8 gear_num 			#档位
uint8 carrier_control		#货舱控制信号
uint8 turn_light		#转向灯信号
uint8 dipped_light		#近光灯信号
uint8 marker_light		#示廓灯信号
uint8 emer_light		#紧急信号灯信号
uint8 trumpet			#喇叭信号

================================================================================
MSG: msg_common/WayPoint
float64 x			#路径x坐标
float64 y			#路径y坐标
float64 z			#路径z坐标
float64 left			#距左边界值
float64 right			#距右边界值
float32 heading_angle		#路径的方向
float32 curvature		#曲率
float32 speed			#路径的速度
float32 distance		#路点与路径起点沿路径的距离
float32 slope			#坡度信息
uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)
float32 speed_limit	        #速度上限
uint8 direction			#0表示前进，1表示后退
uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点
float64 t			#时间
string area_name		#区域名称	
string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	
"""
  __slots__ = ['target_id','traj_id','way_point','remote_spd','remote_steering','remote_parking','remote_stopengine','remote_service_brake','remote_park_brake','remote_load_brake','gear_num','carrier_control','turn_light','dipped_light','marker_light','emer_light','trumpet']
  _slot_types = ['uint16','uint32','msg_common/WayPoint[]','float32','float32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_id,traj_id,way_point,remote_spd,remote_steering,remote_parking,remote_stopengine,remote_service_brake,remote_park_brake,remote_load_brake,gear_num,carrier_control,turn_light,dipped_light,marker_light,emer_light,trumpet

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_local_planning, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target_id is None:
        self.target_id = 0
      if self.traj_id is None:
        self.traj_id = 0
      if self.way_point is None:
        self.way_point = []
      if self.remote_spd is None:
        self.remote_spd = 0.
      if self.remote_steering is None:
        self.remote_steering = 0.
      if self.remote_parking is None:
        self.remote_parking = 0
      if self.remote_stopengine is None:
        self.remote_stopengine = 0
      if self.remote_service_brake is None:
        self.remote_service_brake = 0
      if self.remote_park_brake is None:
        self.remote_park_brake = 0
      if self.remote_load_brake is None:
        self.remote_load_brake = 0
      if self.gear_num is None:
        self.gear_num = 0
      if self.carrier_control is None:
        self.carrier_control = 0
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.trumpet is None:
        self.trumpet = 0
    else:
      self.target_id = 0
      self.traj_id = 0
      self.way_point = []
      self.remote_spd = 0.
      self.remote_steering = 0.
      self.remote_parking = 0
      self.remote_stopengine = 0
      self.remote_service_brake = 0
      self.remote_park_brake = 0
      self.remote_load_brake = 0
      self.gear_num = 0
      self.carrier_control = 0
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.emer_light = 0
      self.trumpet = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_HI().pack(_x.target_id, _x.traj_id))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f12B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.way_point is None:
        self.way_point = None
      end = 0
      _x = self
      start = end
      end += 6
      (_x.target_id, _x.traj_id,) = _get_struct_HI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.way_point.append(val1)
      _x = self
      start = end
      end += 20
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet,) = _get_struct_2f12B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_HI().pack(_x.target_id, _x.traj_id))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f12B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.way_point is None:
        self.way_point = None
      end = 0
      _x = self
      start = end
      end += 6
      (_x.target_id, _x.traj_id,) = _get_struct_HI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.way_point.append(val1)
      _x = self
      start = end
      end += 20
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.remote_stopengine, _x.remote_service_brake, _x.remote_park_brake, _x.remote_load_brake, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet,) = _get_struct_2f12B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f12B = None
def _get_struct_2f12B():
    global _struct_2f12B
    if _struct_2f12B is None:
        _struct_2f12B = struct.Struct("<2f12B")
    return _struct_2f12B
_struct_5d5fIf2Bd = None
def _get_struct_5d5fIf2Bd():
    global _struct_5d5fIf2Bd
    if _struct_5d5fIf2Bd is None:
        _struct_5d5fIf2Bd = struct.Struct("<5d5fIf2Bd")
    return _struct_5d5fIf2Bd
_struct_HI = None
def _get_struct_HI():
    global _struct_HI
    if _struct_HI is None:
        _struct_HI = struct.Struct("<HI")
    return _struct_HI
