# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_local_planning/msg_decision_path.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_local_planning.msg

class msg_decision_path(genpy.Message):
  _md5sum = "54b308deafb0ce6e10e7a93bbd478773"
  _type = "msg_local_planning/msg_decision_path"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 driving_mode                # 0：人工驾驶；1：自动驾驶
uint8 control_mode                # 控制模式
uint8 gear_num			          # 期望档位
uint8 turn_light		          # 转向灯信号
uint8 dipped_light		          # 远、近光灯信号
uint8 marker_light		          # 示廓灯信号/前雾灯
uint8 illumination_light	      # 照明灯信号
uint8 brake_light                 # 刹车灯信号
uint8 backup_light		          # 倒车灯信号
uint8 position_light		      # 位置灯信号
uint8 carrire_warm_light	      # 举升警告灯信号
uint8 trumpet			          # 喇叭信号
uint8 carrier_control	          # 货舱控制信号
uint8 park_brk			          # 驻车制动信号
Trajectory[] way_point
float32 remote_spd
float32 remote_steering
float32 remote_parking
uint8 brim_control	   # 帽沿控制信号
uint8 carrire_enable	   # 举升系统控制使能信号
bool[] is_clean

================================================================================
MSG: msg_local_planning/Trajectory
float64 x
float64 y
float64 z
float32 yaw
float32 curvature
float32 limiting_speed
uint8 protection_level
float32 speed
float32 distance
float32 left_distance
float32 right_distance
float32 slope
uint16 attribute
"""
  __slots__ = ['driving_mode','control_mode','gear_num','turn_light','dipped_light','marker_light','illumination_light','brake_light','backup_light','position_light','carrire_warm_light','trumpet','carrier_control','park_brk','way_point','remote_spd','remote_steering','remote_parking','brim_control','carrire_enable','is_clean']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','msg_local_planning/Trajectory[]','float32','float32','float32','uint8','uint8','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       driving_mode,control_mode,gear_num,turn_light,dipped_light,marker_light,illumination_light,brake_light,backup_light,position_light,carrire_warm_light,trumpet,carrier_control,park_brk,way_point,remote_spd,remote_steering,remote_parking,brim_control,carrire_enable,is_clean

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_decision_path, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.driving_mode is None:
        self.driving_mode = 0
      if self.control_mode is None:
        self.control_mode = 0
      if self.gear_num is None:
        self.gear_num = 0
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.illumination_light is None:
        self.illumination_light = 0
      if self.brake_light is None:
        self.brake_light = 0
      if self.backup_light is None:
        self.backup_light = 0
      if self.position_light is None:
        self.position_light = 0
      if self.carrire_warm_light is None:
        self.carrire_warm_light = 0
      if self.trumpet is None:
        self.trumpet = 0
      if self.carrier_control is None:
        self.carrier_control = 0
      if self.park_brk is None:
        self.park_brk = 0
      if self.way_point is None:
        self.way_point = []
      if self.remote_spd is None:
        self.remote_spd = 0.
      if self.remote_steering is None:
        self.remote_steering = 0.
      if self.remote_parking is None:
        self.remote_parking = 0.
      if self.brim_control is None:
        self.brim_control = 0
      if self.carrire_enable is None:
        self.carrire_enable = 0
      if self.is_clean is None:
        self.is_clean = []
    else:
      self.driving_mode = 0
      self.control_mode = 0
      self.gear_num = 0
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.illumination_light = 0
      self.brake_light = 0
      self.backup_light = 0
      self.position_light = 0
      self.carrire_warm_light = 0
      self.trumpet = 0
      self.carrier_control = 0
      self.park_brk = 0
      self.way_point = []
      self.remote_spd = 0.
      self.remote_steering = 0.
      self.remote_parking = 0.
      self.brim_control = 0
      self.carrire_enable = 0
      self.is_clean = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_14B().pack(_x.driving_mode, _x.control_mode, _x.gear_num, _x.turn_light, _x.dipped_light, _x.marker_light, _x.illumination_light, _x.brake_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.trumpet, _x.carrier_control, _x.park_brk))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_3d3fB5fH().pack(_x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.limiting_speed, _x.protection_level, _x.speed, _x.distance, _x.left_distance, _x.right_distance, _x.slope, _x.attribute))
      _x = self
      buff.write(_get_struct_3f2B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.brim_control, _x.carrire_enable))
      length = len(self.is_clean)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.is_clean))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.way_point is None:
        self.way_point = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.driving_mode, _x.control_mode, _x.gear_num, _x.turn_light, _x.dipped_light, _x.marker_light, _x.illumination_light, _x.brake_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.trumpet, _x.carrier_control, _x.park_brk,) = _get_struct_14B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_local_planning.msg.Trajectory()
        _x = val1
        start = end
        end += 59
        (_x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.limiting_speed, _x.protection_level, _x.speed, _x.distance, _x.left_distance, _x.right_distance, _x.slope, _x.attribute,) = _get_struct_3d3fB5fH().unpack(str[start:end])
        self.way_point.append(val1)
      _x = self
      start = end
      end += 14
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.brim_control, _x.carrire_enable,) = _get_struct_3f2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.is_clean = s.unpack(str[start:end])
      self.is_clean = list(map(bool, self.is_clean))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_14B().pack(_x.driving_mode, _x.control_mode, _x.gear_num, _x.turn_light, _x.dipped_light, _x.marker_light, _x.illumination_light, _x.brake_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.trumpet, _x.carrier_control, _x.park_brk))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_3d3fB5fH().pack(_x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.limiting_speed, _x.protection_level, _x.speed, _x.distance, _x.left_distance, _x.right_distance, _x.slope, _x.attribute))
      _x = self
      buff.write(_get_struct_3f2B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.brim_control, _x.carrire_enable))
      length = len(self.is_clean)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.is_clean.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.way_point is None:
        self.way_point = None
      end = 0
      _x = self
      start = end
      end += 14
      (_x.driving_mode, _x.control_mode, _x.gear_num, _x.turn_light, _x.dipped_light, _x.marker_light, _x.illumination_light, _x.brake_light, _x.backup_light, _x.position_light, _x.carrire_warm_light, _x.trumpet, _x.carrier_control, _x.park_brk,) = _get_struct_14B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_local_planning.msg.Trajectory()
        _x = val1
        start = end
        end += 59
        (_x.x, _x.y, _x.z, _x.yaw, _x.curvature, _x.limiting_speed, _x.protection_level, _x.speed, _x.distance, _x.left_distance, _x.right_distance, _x.slope, _x.attribute,) = _get_struct_3d3fB5fH().unpack(str[start:end])
        self.way_point.append(val1)
      _x = self
      start = end
      end += 14
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.brim_control, _x.carrire_enable,) = _get_struct_3f2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.is_clean = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.is_clean = list(map(bool, self.is_clean))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14B = None
def _get_struct_14B():
    global _struct_14B
    if _struct_14B is None:
        _struct_14B = struct.Struct("<14B")
    return _struct_14B
_struct_3d3fB5fH = None
def _get_struct_3d3fB5fH():
    global _struct_3d3fB5fH
    if _struct_3d3fB5fH is None:
        _struct_3d3fB5fH = struct.Struct("<3d3fB5fH")
    return _struct_3d3fB5fH
_struct_3f2B = None
def _get_struct_3f2B():
    global _struct_3f2B
    if _struct_3f2B is None:
        _struct_3f2B = struct.Struct("<3f2B")
    return _struct_3f2B
