// Generated by gencpp from file msg_local_planning/msg_local_planning.msg
// DO NOT EDIT!


#ifndef MSG_LOCAL_PLANNING_MESSAGE_MSG_LOCAL_PLANNING_H
#define MSG_LOCAL_PLANNING_MESSAGE_MSG_LOCAL_PLANNING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_common/WayPoint.h>

namespace msg_local_planning
{
template <class ContainerAllocator>
struct msg_local_planning_
{
  typedef msg_local_planning_<ContainerAllocator> Type;

  msg_local_planning_()
    : target_id(0)
    , traj_id(0)
    , way_point()
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0)
    , remote_stopengine(0)
    , remote_service_brake(0)
    , remote_park_brake(0)
    , remote_load_brake(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , emer_light(0)
    , trumpet(0)  {
    }
  msg_local_planning_(const ContainerAllocator& _alloc)
    : target_id(0)
    , traj_id(0)
    , way_point(_alloc)
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0)
    , remote_stopengine(0)
    , remote_service_brake(0)
    , remote_park_brake(0)
    , remote_load_brake(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , emer_light(0)
    , trumpet(0)  {
  (void)_alloc;
    }



   typedef uint16_t _target_id_type;
  _target_id_type target_id;

   typedef uint32_t _traj_id_type;
  _traj_id_type traj_id;

   typedef std::vector< ::msg_common::WayPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_common::WayPoint_<ContainerAllocator> >> _way_point_type;
  _way_point_type way_point;

   typedef float _remote_spd_type;
  _remote_spd_type remote_spd;

   typedef float _remote_steering_type;
  _remote_steering_type remote_steering;

   typedef uint8_t _remote_parking_type;
  _remote_parking_type remote_parking;

   typedef uint8_t _remote_stopengine_type;
  _remote_stopengine_type remote_stopengine;

   typedef uint8_t _remote_service_brake_type;
  _remote_service_brake_type remote_service_brake;

   typedef uint8_t _remote_park_brake_type;
  _remote_park_brake_type remote_park_brake;

   typedef uint8_t _remote_load_brake_type;
  _remote_load_brake_type remote_load_brake;

   typedef uint8_t _gear_num_type;
  _gear_num_type gear_num;

   typedef uint8_t _carrier_control_type;
  _carrier_control_type carrier_control;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _emer_light_type;
  _emer_light_type emer_light;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;





  typedef boost::shared_ptr< ::msg_local_planning::msg_local_planning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_local_planning::msg_local_planning_<ContainerAllocator> const> ConstPtr;

}; // struct msg_local_planning_

typedef ::msg_local_planning::msg_local_planning_<std::allocator<void> > msg_local_planning;

typedef boost::shared_ptr< ::msg_local_planning::msg_local_planning > msg_local_planningPtr;
typedef boost::shared_ptr< ::msg_local_planning::msg_local_planning const> msg_local_planningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_local_planning::msg_local_planning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_local_planning::msg_local_planning_<ContainerAllocator1> & lhs, const ::msg_local_planning::msg_local_planning_<ContainerAllocator2> & rhs)
{
  return lhs.target_id == rhs.target_id &&
    lhs.traj_id == rhs.traj_id &&
    lhs.way_point == rhs.way_point &&
    lhs.remote_spd == rhs.remote_spd &&
    lhs.remote_steering == rhs.remote_steering &&
    lhs.remote_parking == rhs.remote_parking &&
    lhs.remote_stopengine == rhs.remote_stopengine &&
    lhs.remote_service_brake == rhs.remote_service_brake &&
    lhs.remote_park_brake == rhs.remote_park_brake &&
    lhs.remote_load_brake == rhs.remote_load_brake &&
    lhs.gear_num == rhs.gear_num &&
    lhs.carrier_control == rhs.carrier_control &&
    lhs.turn_light == rhs.turn_light &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.emer_light == rhs.emer_light &&
    lhs.trumpet == rhs.trumpet;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_local_planning::msg_local_planning_<ContainerAllocator1> & lhs, const ::msg_local_planning::msg_local_planning_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_local_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_local_planning::msg_local_planning_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_local_planning::msg_local_planning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_local_planning::msg_local_planning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be10eb2ba128758006e99f566fb3265b";
  }

  static const char* value(const ::msg_local_planning::msg_local_planning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe10eb2ba1287580ULL;
  static const uint64_t static_value2 = 0x06e99f566fb3265bULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_local_planning/msg_local_planning";
  }

  static const char* value(const ::msg_local_planning::msg_local_planning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16  target_id  		#任务指令编号 0自检  1启动发动机  2静态测试 .....\n"
"uint32 traj_id\n"
"msg_common/WayPoint[] way_point  	#正常行驶模式规划的轨迹\n"
"float32 remote_spd	#遥控模式：期望速度	\n"
"float32 remote_steering	#遥控模式：方向盘转角	单位：deg 范围：-720 ~ 720（左转为正）\n"
"uint8 remote_parking	#遥控模式：驻车制动	0：无驻车制动1：驻车制动\n"
"uint8 remote_stopengine\n"
"uint8 remote_service_brake #行车制动\n"
"uint8 remote_park_brake #停车制动\n"
"uint8 remote_load_brake #装载制动\n"
"uint8 gear_num 			#档位\n"
"uint8 carrier_control		#货舱控制信号\n"
"uint8 turn_light		#转向灯信号\n"
"uint8 dipped_light		#近光灯信号\n"
"uint8 marker_light		#示廓灯信号\n"
"uint8 emer_light		#紧急信号灯信号\n"
"uint8 trumpet			#喇叭信号\n"
"\n"
"================================================================================\n"
"MSG: msg_common/WayPoint\n"
"float64 x			#路径x坐标\n"
"float64 y			#路径y坐标\n"
"float64 z			#路径z坐标\n"
"float64 left			#距左边界值\n"
"float64 right			#距右边界值\n"
"float32 heading_angle		#路径的方向\n"
"float32 curvature		#曲率\n"
"float32 speed			#路径的速度\n"
"float32 distance		#路点与路径起点沿路径的距离\n"
"float32 slope			#坡度信息\n"
"uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)\n"
"float32 speed_limit	        #速度上限\n"
"uint8 direction			#0表示前进，1表示后退\n"
"uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点\n"
"float64 t			#时间\n"
"string area_name		#区域名称	\n"
"string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	\n"
;
  }

  static const char* value(const ::msg_local_planning::msg_local_planning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_id);
      stream.next(m.traj_id);
      stream.next(m.way_point);
      stream.next(m.remote_spd);
      stream.next(m.remote_steering);
      stream.next(m.remote_parking);
      stream.next(m.remote_stopengine);
      stream.next(m.remote_service_brake);
      stream.next(m.remote_park_brake);
      stream.next(m.remote_load_brake);
      stream.next(m.gear_num);
      stream.next(m.carrier_control);
      stream.next(m.turn_light);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.emer_light);
      stream.next(m.trumpet);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_local_planning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_local_planning::msg_local_planning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_local_planning::msg_local_planning_<ContainerAllocator>& v)
  {
    s << indent << "target_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_id);
    s << indent << "traj_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "way_point[]" << std::endl;
    for (size_t i = 0; i < v.way_point.size(); ++i)
    {
      s << indent << "  way_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_common::WayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.way_point[i]);
    }
    s << indent << "remote_spd: ";
    Printer<float>::stream(s, indent + "  ", v.remote_spd);
    s << indent << "remote_steering: ";
    Printer<float>::stream(s, indent + "  ", v.remote_steering);
    s << indent << "remote_parking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_parking);
    s << indent << "remote_stopengine: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_stopengine);
    s << indent << "remote_service_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_service_brake);
    s << indent << "remote_park_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_park_brake);
    s << indent << "remote_load_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_load_brake);
    s << indent << "gear_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "carrier_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrier_control);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "emer_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emer_light);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_LOCAL_PLANNING_MESSAGE_MSG_LOCAL_PLANNING_H
