// Generated by gencpp from file msg_local_planning/msg_decision_path.msg
// DO NOT EDIT!


#ifndef MSG_LOCAL_PLANNING_MESSAGE_MSG_DECISION_PATH_H
#define MSG_LOCAL_PLANNING_MESSAGE_MSG_DECISION_PATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_local_planning/Trajectory.h>

namespace msg_local_planning
{
template <class ContainerAllocator>
struct msg_decision_path_
{
  typedef msg_decision_path_<ContainerAllocator> Type;

  msg_decision_path_()
    : driving_mode(0)
    , control_mode(0)
    , gear_num(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , illumination_light(0)
    , brake_light(0)
    , backup_light(0)
    , position_light(0)
    , carrire_warm_light(0)
    , trumpet(0)
    , carrier_control(0)
    , park_brk(0)
    , way_point()
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0.0)
    , brim_control(0)
    , carrire_enable(0)
    , is_clean()  {
    }
  msg_decision_path_(const ContainerAllocator& _alloc)
    : driving_mode(0)
    , control_mode(0)
    , gear_num(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , illumination_light(0)
    , brake_light(0)
    , backup_light(0)
    , position_light(0)
    , carrire_warm_light(0)
    , trumpet(0)
    , carrier_control(0)
    , park_brk(0)
    , way_point(_alloc)
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0.0)
    , brim_control(0)
    , carrire_enable(0)
    , is_clean(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _driving_mode_type;
  _driving_mode_type driving_mode;

   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef uint8_t _gear_num_type;
  _gear_num_type gear_num;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _illumination_light_type;
  _illumination_light_type illumination_light;

   typedef uint8_t _brake_light_type;
  _brake_light_type brake_light;

   typedef uint8_t _backup_light_type;
  _backup_light_type backup_light;

   typedef uint8_t _position_light_type;
  _position_light_type position_light;

   typedef uint8_t _carrire_warm_light_type;
  _carrire_warm_light_type carrire_warm_light;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;

   typedef uint8_t _carrier_control_type;
  _carrier_control_type carrier_control;

   typedef uint8_t _park_brk_type;
  _park_brk_type park_brk;

   typedef std::vector< ::msg_local_planning::Trajectory_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_local_planning::Trajectory_<ContainerAllocator> >> _way_point_type;
  _way_point_type way_point;

   typedef float _remote_spd_type;
  _remote_spd_type remote_spd;

   typedef float _remote_steering_type;
  _remote_steering_type remote_steering;

   typedef float _remote_parking_type;
  _remote_parking_type remote_parking;

   typedef uint8_t _brim_control_type;
  _brim_control_type brim_control;

   typedef uint8_t _carrire_enable_type;
  _carrire_enable_type carrire_enable;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _is_clean_type;
  _is_clean_type is_clean;





  typedef boost::shared_ptr< ::msg_local_planning::msg_decision_path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_local_planning::msg_decision_path_<ContainerAllocator> const> ConstPtr;

}; // struct msg_decision_path_

typedef ::msg_local_planning::msg_decision_path_<std::allocator<void> > msg_decision_path;

typedef boost::shared_ptr< ::msg_local_planning::msg_decision_path > msg_decision_pathPtr;
typedef boost::shared_ptr< ::msg_local_planning::msg_decision_path const> msg_decision_pathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_local_planning::msg_decision_path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_local_planning::msg_decision_path_<ContainerAllocator1> & lhs, const ::msg_local_planning::msg_decision_path_<ContainerAllocator2> & rhs)
{
  return lhs.driving_mode == rhs.driving_mode &&
    lhs.control_mode == rhs.control_mode &&
    lhs.gear_num == rhs.gear_num &&
    lhs.turn_light == rhs.turn_light &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.illumination_light == rhs.illumination_light &&
    lhs.brake_light == rhs.brake_light &&
    lhs.backup_light == rhs.backup_light &&
    lhs.position_light == rhs.position_light &&
    lhs.carrire_warm_light == rhs.carrire_warm_light &&
    lhs.trumpet == rhs.trumpet &&
    lhs.carrier_control == rhs.carrier_control &&
    lhs.park_brk == rhs.park_brk &&
    lhs.way_point == rhs.way_point &&
    lhs.remote_spd == rhs.remote_spd &&
    lhs.remote_steering == rhs.remote_steering &&
    lhs.remote_parking == rhs.remote_parking &&
    lhs.brim_control == rhs.brim_control &&
    lhs.carrire_enable == rhs.carrire_enable &&
    lhs.is_clean == rhs.is_clean;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_local_planning::msg_decision_path_<ContainerAllocator1> & lhs, const ::msg_local_planning::msg_decision_path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_local_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_local_planning::msg_decision_path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_local_planning::msg_decision_path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_local_planning::msg_decision_path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b308deafb0ce6e10e7a93bbd478773";
  }

  static const char* value(const ::msg_local_planning::msg_decision_path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b308deafb0ce6eULL;
  static const uint64_t static_value2 = 0x10e7a93bbd478773ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_local_planning/msg_decision_path";
  }

  static const char* value(const ::msg_local_planning::msg_decision_path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 driving_mode                # 0：人工驾驶；1：自动驾驶\n"
"uint8 control_mode                # 控制模式\n"
"uint8 gear_num			          # 期望档位\n"
"uint8 turn_light		          # 转向灯信号\n"
"uint8 dipped_light		          # 远、近光灯信号\n"
"uint8 marker_light		          # 示廓灯信号/前雾灯\n"
"uint8 illumination_light	      # 照明灯信号\n"
"uint8 brake_light                 # 刹车灯信号\n"
"uint8 backup_light		          # 倒车灯信号\n"
"uint8 position_light		      # 位置灯信号\n"
"uint8 carrire_warm_light	      # 举升警告灯信号\n"
"uint8 trumpet			          # 喇叭信号\n"
"uint8 carrier_control	          # 货舱控制信号\n"
"uint8 park_brk			          # 驻车制动信号\n"
"Trajectory[] way_point\n"
"float32 remote_spd\n"
"float32 remote_steering\n"
"float32 remote_parking\n"
"uint8 brim_control	   # 帽沿控制信号\n"
"uint8 carrire_enable	   # 举升系统控制使能信号\n"
"bool[] is_clean\n"
"\n"
"================================================================================\n"
"MSG: msg_local_planning/Trajectory\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float32 yaw\n"
"float32 curvature\n"
"float32 limiting_speed\n"
"uint8 protection_level\n"
"float32 speed\n"
"float32 distance\n"
"float32 left_distance\n"
"float32 right_distance\n"
"float32 slope\n"
"uint16 attribute\n"
;
  }

  static const char* value(const ::msg_local_planning::msg_decision_path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.driving_mode);
      stream.next(m.control_mode);
      stream.next(m.gear_num);
      stream.next(m.turn_light);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.illumination_light);
      stream.next(m.brake_light);
      stream.next(m.backup_light);
      stream.next(m.position_light);
      stream.next(m.carrire_warm_light);
      stream.next(m.trumpet);
      stream.next(m.carrier_control);
      stream.next(m.park_brk);
      stream.next(m.way_point);
      stream.next(m.remote_spd);
      stream.next(m.remote_steering);
      stream.next(m.remote_parking);
      stream.next(m.brim_control);
      stream.next(m.carrire_enable);
      stream.next(m.is_clean);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_decision_path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_local_planning::msg_decision_path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_local_planning::msg_decision_path_<ContainerAllocator>& v)
  {
    s << indent << "driving_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.driving_mode);
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "gear_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "illumination_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.illumination_light);
    s << indent << "brake_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_light);
    s << indent << "backup_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.backup_light);
    s << indent << "position_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_light);
    s << indent << "carrire_warm_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrire_warm_light);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
    s << indent << "carrier_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrier_control);
    s << indent << "park_brk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.park_brk);
    s << indent << "way_point[]" << std::endl;
    for (size_t i = 0; i < v.way_point.size(); ++i)
    {
      s << indent << "  way_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_local_planning::Trajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.way_point[i]);
    }
    s << indent << "remote_spd: ";
    Printer<float>::stream(s, indent + "  ", v.remote_spd);
    s << indent << "remote_steering: ";
    Printer<float>::stream(s, indent + "  ", v.remote_steering);
    s << indent << "remote_parking: ";
    Printer<float>::stream(s, indent + "  ", v.remote_parking);
    s << indent << "brim_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brim_control);
    s << indent << "carrire_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrire_enable);
    s << indent << "is_clean[]" << std::endl;
    for (size_t i = 0; i < v.is_clean.size(); ++i)
    {
      s << indent << "  is_clean[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.is_clean[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_LOCAL_PLANNING_MESSAGE_MSG_DECISION_PATH_H
