// Generated by gencpp from file msg_lidar_prep/LidarPoints.msg
// DO NOT EDIT!


#ifndef MSG_LIDAR_PREP_MESSAGE_LIDARPOINTS_H
#define MSG_LIDAR_PREP_MESSAGE_LIDARPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_lidar_prep
{
template <class ContainerAllocator>
struct LidarPoints_
{
  typedef LidarPoints_<ContainerAllocator> Type;

  LidarPoints_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , intensity(0.0)
    , angle(0.0)
    , ring(0)
    , flag(0)
    , distance(0.0)
    , type(0)  {
    }
  LidarPoints_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , intensity(0.0)
    , angle(0.0)
    , ring(0)
    , flag(0)
    , distance(0.0)
    , type(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _intensity_type;
  _intensity_type intensity;

   typedef float _angle_type;
  _angle_type angle;

   typedef int8_t _ring_type;
  _ring_type ring;

   typedef int8_t _flag_type;
  _flag_type flag;

   typedef float _distance_type;
  _distance_type distance;

   typedef int8_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> const> ConstPtr;

}; // struct LidarPoints_

typedef ::msg_lidar_prep::LidarPoints_<std::allocator<void> > LidarPoints;

typedef boost::shared_ptr< ::msg_lidar_prep::LidarPoints > LidarPointsPtr;
typedef boost::shared_ptr< ::msg_lidar_prep::LidarPoints const> LidarPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_lidar_prep::LidarPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_lidar_prep::LidarPoints_<ContainerAllocator1> & lhs, const ::msg_lidar_prep::LidarPoints_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.intensity == rhs.intensity &&
    lhs.angle == rhs.angle &&
    lhs.ring == rhs.ring &&
    lhs.flag == rhs.flag &&
    lhs.distance == rhs.distance &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_lidar_prep::LidarPoints_<ContainerAllocator1> & lhs, const ::msg_lidar_prep::LidarPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_lidar_prep

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e65170553e1e426bb3859ed22e97267";
  }

  static const char* value(const ::msg_lidar_prep::LidarPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e65170553e1e426ULL;
  static const uint64_t static_value2 = 0xbb3859ed22e97267ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_lidar_prep/LidarPoints";
  }

  static const char* value(const ::msg_lidar_prep::LidarPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x #点云x轴坐标，单位m \n"
"float32 y #点云y轴坐标， 单位m\n"
"float32 z #点云z轴坐标， 单为m\n"
"float32 intensity #激光反射强度信息，数值越大，强度越强\n"
"float32 angle #射线角度单位为度（角度）\n"
"int8 ring #射线编号\n"
"int8 flag  #雷达编号\n"
"float32 distance #点到激光雷达径向距离，单位m\n"
"int8 type #点所属类型，1：透过点（transparent poi）；2：大气；4：地面；8：灰层雨雾\n"
"\n"
;
  }

  static const char* value(const ::msg_lidar_prep::LidarPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.intensity);
      stream.next(m.angle);
      stream.next(m.ring);
      stream.next(m.flag);
      stream.next(m.distance);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_lidar_prep::LidarPoints_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "intensity: ";
    Printer<float>::stream(s, indent + "  ", v.intensity);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "ring: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ring);
    s << indent << "flag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_LIDAR_PREP_MESSAGE_LIDARPOINTS_H
