// Generated by gencpp from file msg_lidar_prep/msg_lidar_prep.msg
// DO NOT EDIT!


#ifndef MSG_LIDAR_PREP_MESSAGE_MSG_LIDAR_PREP_H
#define MSG_LIDAR_PREP_MESSAGE_MSG_LIDAR_PREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_lidar_prep/LidarPoints.h>

namespace msg_lidar_prep
{
template <class ContainerAllocator>
struct msg_lidar_prep_
{
  typedef msg_lidar_prep_<ContainerAllocator> Type;

  msg_lidar_prep_()
    : lidar_prep()  {
    }
  msg_lidar_prep_(const ContainerAllocator& _alloc)
    : lidar_prep(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >> _lidar_prep_type;
  _lidar_prep_type lidar_prep;





  typedef boost::shared_ptr< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> const> ConstPtr;

}; // struct msg_lidar_prep_

typedef ::msg_lidar_prep::msg_lidar_prep_<std::allocator<void> > msg_lidar_prep;

typedef boost::shared_ptr< ::msg_lidar_prep::msg_lidar_prep > msg_lidar_prepPtr;
typedef boost::shared_ptr< ::msg_lidar_prep::msg_lidar_prep const> msg_lidar_prepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator1> & lhs, const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator2> & rhs)
{
  return lhs.lidar_prep == rhs.lidar_prep;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator1> & lhs, const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_lidar_prep

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2143cd4a31c057ba90e03c61571c72c";
  }

  static const char* value(const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2143cd4a31c057bULL;
  static const uint64_t static_value2 = 0xa90e03c61571c72cULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_lidar_prep/msg_lidar_prep";
  }

  static const char* value(const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LidarPoints[] lidar_prep\n"
"\n"
"================================================================================\n"
"MSG: msg_lidar_prep/LidarPoints\n"
"float32 x #点云x轴坐标，单位m \n"
"float32 y #点云y轴坐标， 单位m\n"
"float32 z #点云z轴坐标， 单为m\n"
"float32 intensity #激光反射强度信息，数值越大，强度越强\n"
"float32 angle #射线角度单位为度（角度）\n"
"int8 ring #射线编号\n"
"int8 flag  #雷达编号\n"
"float32 distance #点到激光雷达径向距离，单位m\n"
"int8 type #点所属类型，1：透过点（transparent poi）；2：大气；4：地面；8：灰层雨雾\n"
"\n"
;
  }

  static const char* value(const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lidar_prep);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_lidar_prep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_lidar_prep::msg_lidar_prep_<ContainerAllocator>& v)
  {
    s << indent << "lidar_prep[]" << std::endl;
    for (size_t i = 0; i < v.lidar_prep.size(); ++i)
    {
      s << indent << "  lidar_prep[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_lidar_prep::LidarPoints_<ContainerAllocator> >::stream(s, indent + "    ", v.lidar_prep[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_LIDAR_PREP_MESSAGE_MSG_LIDAR_PREP_H
