# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_gnss_prep/msg_gnss_prep.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class msg_gnss_prep(genpy.Message):
  _md5sum = "e134d5a1a517850320e9c8189731570d"
  _type = "msg_gnss_prep/msg_gnss_prep"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 z
float64 latitude
float64 longitude
float64 height
float32 spd_east
float32 spd_north
float32 spd_down
float32 heading_angle
float32 yaw_angle
float32 yaw_rate
float32 pitch_angle
float32 roll_angle
float32 speed
float32 spd_lon
float32 spd_lat
float32 acce
float32 acce_lon
float32 acce_lat
uint8 flag
uint8 gps_status

"""
  __slots__ = ['x','y','z','latitude','longitude','height','spd_east','spd_north','spd_down','heading_angle','yaw_angle','yaw_rate','pitch_angle','roll_angle','speed','spd_lon','spd_lat','acce','acce_lon','acce_lat','flag','gps_status']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,latitude,longitude,height,spd_east,spd_north,spd_down,heading_angle,yaw_angle,yaw_rate,pitch_angle,roll_angle,speed,spd_lon,spd_lat,acce,acce_lon,acce_lat,flag,gps_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_gnss_prep, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.height is None:
        self.height = 0.
      if self.spd_east is None:
        self.spd_east = 0.
      if self.spd_north is None:
        self.spd_north = 0.
      if self.spd_down is None:
        self.spd_down = 0.
      if self.heading_angle is None:
        self.heading_angle = 0.
      if self.yaw_angle is None:
        self.yaw_angle = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.pitch_angle is None:
        self.pitch_angle = 0.
      if self.roll_angle is None:
        self.roll_angle = 0.
      if self.speed is None:
        self.speed = 0.
      if self.spd_lon is None:
        self.spd_lon = 0.
      if self.spd_lat is None:
        self.spd_lat = 0.
      if self.acce is None:
        self.acce = 0.
      if self.acce_lon is None:
        self.acce_lon = 0.
      if self.acce_lat is None:
        self.acce_lat = 0.
      if self.flag is None:
        self.flag = 0
      if self.gps_status is None:
        self.gps_status = 0
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.height = 0.
      self.spd_east = 0.
      self.spd_north = 0.
      self.spd_down = 0.
      self.heading_angle = 0.
      self.yaw_angle = 0.
      self.yaw_rate = 0.
      self.pitch_angle = 0.
      self.roll_angle = 0.
      self.speed = 0.
      self.spd_lon = 0.
      self.spd_lat = 0.
      self.acce = 0.
      self.acce_lon = 0.
      self.acce_lat = 0.
      self.flag = 0
      self.gps_status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d14f2B().pack(_x.x, _x.y, _x.z, _x.latitude, _x.longitude, _x.height, _x.spd_east, _x.spd_north, _x.spd_down, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.roll_angle, _x.speed, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.flag, _x.gps_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 106
      (_x.x, _x.y, _x.z, _x.latitude, _x.longitude, _x.height, _x.spd_east, _x.spd_north, _x.spd_down, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.roll_angle, _x.speed, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.flag, _x.gps_status,) = _get_struct_6d14f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d14f2B().pack(_x.x, _x.y, _x.z, _x.latitude, _x.longitude, _x.height, _x.spd_east, _x.spd_north, _x.spd_down, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.roll_angle, _x.speed, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.flag, _x.gps_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 106
      (_x.x, _x.y, _x.z, _x.latitude, _x.longitude, _x.height, _x.spd_east, _x.spd_north, _x.spd_down, _x.heading_angle, _x.yaw_angle, _x.yaw_rate, _x.pitch_angle, _x.roll_angle, _x.speed, _x.spd_lon, _x.spd_lat, _x.acce, _x.acce_lon, _x.acce_lat, _x.flag, _x.gps_status,) = _get_struct_6d14f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d14f2B = None
def _get_struct_6d14f2B():
    global _struct_6d14f2B
    if _struct_6d14f2B is None:
        _struct_6d14f2B = struct.Struct("<6d14f2B")
    return _struct_6d14f2B
