# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_lidar_prep/LidarPoints.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LidarPoints(genpy.Message):
  _md5sum = "7e65170553e1e426bb3859ed22e97267"
  _type = "msg_lidar_prep/LidarPoints"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x #点云x轴坐标，单位m 
float32 y #点云y轴坐标， 单位m
float32 z #点云z轴坐标， 单为m
float32 intensity #激光反射强度信息，数值越大，强度越强
float32 angle #射线角度单位为度（角度）
int8 ring #射线编号
int8 flag  #雷达编号
float32 distance #点到激光雷达径向距离，单位m
int8 type #点所属类型，1：透过点（transparent poi）；2：大气；4：地面；8：灰层雨雾

"""
  __slots__ = ['x','y','z','intensity','angle','ring','flag','distance','type']
  _slot_types = ['float32','float32','float32','float32','float32','int8','int8','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,intensity,angle,ring,flag,distance,type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LidarPoints, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.intensity is None:
        self.intensity = 0.
      if self.angle is None:
        self.angle = 0.
      if self.ring is None:
        self.ring = 0
      if self.flag is None:
        self.flag = 0
      if self.distance is None:
        self.distance = 0.
      if self.type is None:
        self.type = 0
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.intensity = 0.
      self.angle = 0.
      self.ring = 0
      self.flag = 0
      self.distance = 0.
      self.type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f2bfb().pack(_x.x, _x.y, _x.z, _x.intensity, _x.angle, _x.ring, _x.flag, _x.distance, _x.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.x, _x.y, _x.z, _x.intensity, _x.angle, _x.ring, _x.flag, _x.distance, _x.type,) = _get_struct_5f2bfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f2bfb().pack(_x.x, _x.y, _x.z, _x.intensity, _x.angle, _x.ring, _x.flag, _x.distance, _x.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.x, _x.y, _x.z, _x.intensity, _x.angle, _x.ring, _x.flag, _x.distance, _x.type,) = _get_struct_5f2bfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f2bfb = None
def _get_struct_5f2bfb():
    global _struct_5f2bfb
    if _struct_5f2bfb is None:
        _struct_5f2bfb = struct.Struct("<5f2bfb")
    return _struct_5f2bfb
