// Generated by gencpp from file msg_v_decision/msg_diagn_v_decision.msg
// DO NOT EDIT!


#ifndef MSG_V_DECISION_MESSAGE_MSG_DIAGN_V_DECISION_H
#define MSG_V_DECISION_MESSAGE_MSG_DIAGN_V_DECISION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_safety_diagn/DiagnDataStruct.h>

namespace msg_v_decision
{
template <class ContainerAllocator>
struct msg_diagn_v_decision_
{
  typedef msg_diagn_v_decision_<ContainerAllocator> Type;

  msg_diagn_v_decision_()
    : diagn_num(0)
    , diagn_data()  {
    }
  msg_diagn_v_decision_(const ContainerAllocator& _alloc)
    : diagn_num(0)
    , diagn_data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _diagn_num_type;
  _diagn_num_type diagn_num;

   typedef std::vector< ::msg_safety_diagn::DiagnDataStruct_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_safety_diagn::DiagnDataStruct_<ContainerAllocator> >> _diagn_data_type;
  _diagn_data_type diagn_data;





  typedef boost::shared_ptr< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> const> ConstPtr;

}; // struct msg_diagn_v_decision_

typedef ::msg_v_decision::msg_diagn_v_decision_<std::allocator<void> > msg_diagn_v_decision;

typedef boost::shared_ptr< ::msg_v_decision::msg_diagn_v_decision > msg_diagn_v_decisionPtr;
typedef boost::shared_ptr< ::msg_v_decision::msg_diagn_v_decision const> msg_diagn_v_decisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator1> & lhs, const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator2> & rhs)
{
  return lhs.diagn_num == rhs.diagn_num &&
    lhs.diagn_data == rhs.diagn_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator1> & lhs, const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_v_decision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52a665b88860c4a92dcb2fd94f5446ee";
  }

  static const char* value(const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52a665b88860c4a9ULL;
  static const uint64_t static_value2 = 0x2dcb2fd94f5446eeULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_v_decision/msg_diagn_v_decision";
  }

  static const char* value(const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 diagn_num \n"
"msg_safety_diagn/DiagnDataStruct[] diagn_data\n"
"\n"
"================================================================================\n"
"MSG: msg_safety_diagn/DiagnDataStruct\n"
"int32 equip_num \n"
"int32 diagn_type\n"
"msg_obj/Obj[] obj_state\n"
"\n"
"================================================================================\n"
"MSG: msg_obj/Obj\n"
"float64 x #单位m\n"
"float64 y #单位m\n"
"float64 z #单位m\n"
"float32 vx #单位m/s\n"
"float32 vy #单位m/s\n"
"float32 vz #单位m/s\n"
"float32 width #宽度，单位m\n"
"float32 length #长度，单位m\n"
"float32 height #高度，单位m\n"
"#float64 yaw_angle #横摆脚，角度信息，单位为度\n"
"uint8 track_state #跟踪状态,0：删除或无效；1：新的；2：测量的；3：预测的；4：待删除；5：待跟踪\n"
"uint8 predict_length #预测时长， 单位s\n"
"int32 type #障碍物类型, 0:未知；1：汽车；2：卡车；3：行人；4：摩托车；5自行车；6：大障碍物；7：小障碍物； 8：矿坑； 9：灰尘\n"
"uint32 type_age #障碍物类型时间长度，单位s\n"
"float32 orientation #障碍物形状方位角，单位度，\n"
"float32 bbox_yaw\n"
"float32 bbox_pitch\n"
"float32 bbox_roll\n"
"float32 ax #x轴加速度，单位m/s^2\n"
"float32 ay #y轴加速度，单位m/s^2\n"
"float32 az #z轴加速度，单位m/s^2\n"
"msg_common/Covariance cov     #协方差\n"
"uint8 type_certainty #障碍物类型确信度 0-100\n"
"uint8 obj_certainty #障碍物存在确信度, 0:无效；1：小于0.25；2：小于0.5;3：小于0.75;4：小于0.9;5：小于0.99;6：小于0.999\n"
"int8 source #数据来源编号，预设的传感器编号\n"
"msg_common/GridPoint[] contour_point #obj对象包含的点信息\n"
"uint32 id #跟踪之后给出的最终obj的id\n"
"uint8 absolute_motion #绝对的运动状态，0：未知; 1：静止；2：运动\n"
"uint8 relative_motion #相对车辆的运动状态，0：静止；1:迎面而来；2：远去；3：横越；4:未知\n"
"float32 orientation_rate #方向角速度\n"
"\n"
"================================================================================\n"
"MSG: msg_common/Covariance\n"
"float32[] value #矩阵值\n"
"int8 row #协方差行\n"
"int8 col #协方差列\n"
"================================================================================\n"
"MSG: msg_common/GridPoint\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
;
  }

  static const char* value(const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.diagn_num);
      stream.next(m.diagn_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_diagn_v_decision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_v_decision::msg_diagn_v_decision_<ContainerAllocator>& v)
  {
    s << indent << "diagn_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.diagn_num);
    s << indent << "diagn_data[]" << std::endl;
    for (size_t i = 0; i < v.diagn_data.size(); ++i)
    {
      s << indent << "  diagn_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_safety_diagn::DiagnDataStruct_<ContainerAllocator> >::stream(s, indent + "    ", v.diagn_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_V_DECISION_MESSAGE_MSG_DIAGN_V_DECISION_H
