// Generated by gencpp from file msg_v_decision/msg_v_decision.msg
// DO NOT EDIT!


#ifndef MSG_V_DECISION_MESSAGE_MSG_V_DECISION_H
#define MSG_V_DECISION_MESSAGE_MSG_V_DECISION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_obj/Obj.h>
#include <msg_obj/Obj.h>
#include <msg_safety_diagn/DiagnDataStruct.h>
#include <msg_common/WayPoint.h>

namespace msg_v_decision
{
template <class ContainerAllocator>
struct msg_v_decision_
{
  typedef msg_v_decision_<ContainerAllocator> Type;

  msg_v_decision_()
    : task_mode(0)
    , target_id(0)
    , task_num(0)
    , task_state(0)
    , system_state(0)
    , obj_fuse()
    , target_obstacle()
    , dis2front(0.0)
    , distance2vehicle(0.0)
    , distance2obstacle(0.0)
    , fault_info()
    , event_report(0)
    , mode(0)
    , is_update_map(0)
    , traj_id(0)
    , way_point()
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0)
    , remote_stopengine(0)
    , remote_service_brake(0)
    , remote_park_brake(0)
    , remote_load_brake(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , emer_light(0)
    , trumpet(0)
    , is_clean()  {
    }
  msg_v_decision_(const ContainerAllocator& _alloc)
    : task_mode(0)
    , target_id(0)
    , task_num(0)
    , task_state(0)
    , system_state(0)
    , obj_fuse(_alloc)
    , target_obstacle(_alloc)
    , dis2front(0.0)
    , distance2vehicle(0.0)
    , distance2obstacle(0.0)
    , fault_info(_alloc)
    , event_report(0)
    , mode(0)
    , is_update_map(0)
    , traj_id(0)
    , way_point(_alloc)
    , remote_spd(0.0)
    , remote_steering(0.0)
    , remote_parking(0)
    , remote_stopengine(0)
    , remote_service_brake(0)
    , remote_park_brake(0)
    , remote_load_brake(0)
    , gear_num(0)
    , carrier_control(0)
    , turn_light(0)
    , dipped_light(0)
    , marker_light(0)
    , emer_light(0)
    , trumpet(0)
    , is_clean(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _task_mode_type;
  _task_mode_type task_mode;

   typedef uint16_t _target_id_type;
  _target_id_type target_id;

   typedef uint16_t _task_num_type;
  _task_num_type task_num;

   typedef uint16_t _task_state_type;
  _task_state_type task_state;

   typedef int32_t _system_state_type;
  _system_state_type system_state;

   typedef std::vector< ::msg_obj::Obj_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_obj::Obj_<ContainerAllocator> >> _obj_fuse_type;
  _obj_fuse_type obj_fuse;

   typedef std::vector< ::msg_obj::Obj_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_obj::Obj_<ContainerAllocator> >> _target_obstacle_type;
  _target_obstacle_type target_obstacle;

   typedef float _dis2front_type;
  _dis2front_type dis2front;

   typedef float _distance2vehicle_type;
  _distance2vehicle_type distance2vehicle;

   typedef float _distance2obstacle_type;
  _distance2obstacle_type distance2obstacle;

   typedef std::vector< ::msg_safety_diagn::DiagnDataStruct_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_safety_diagn::DiagnDataStruct_<ContainerAllocator> >> _fault_info_type;
  _fault_info_type fault_info;

   typedef uint16_t _event_report_type;
  _event_report_type event_report;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _is_update_map_type;
  _is_update_map_type is_update_map;

   typedef uint32_t _traj_id_type;
  _traj_id_type traj_id;

   typedef std::vector< ::msg_common::WayPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_common::WayPoint_<ContainerAllocator> >> _way_point_type;
  _way_point_type way_point;

   typedef float _remote_spd_type;
  _remote_spd_type remote_spd;

   typedef float _remote_steering_type;
  _remote_steering_type remote_steering;

   typedef uint8_t _remote_parking_type;
  _remote_parking_type remote_parking;

   typedef uint8_t _remote_stopengine_type;
  _remote_stopengine_type remote_stopengine;

   typedef uint8_t _remote_service_brake_type;
  _remote_service_brake_type remote_service_brake;

   typedef uint8_t _remote_park_brake_type;
  _remote_park_brake_type remote_park_brake;

   typedef uint8_t _remote_load_brake_type;
  _remote_load_brake_type remote_load_brake;

   typedef uint8_t _gear_num_type;
  _gear_num_type gear_num;

   typedef uint8_t _carrier_control_type;
  _carrier_control_type carrier_control;

   typedef uint8_t _turn_light_type;
  _turn_light_type turn_light;

   typedef uint8_t _dipped_light_type;
  _dipped_light_type dipped_light;

   typedef uint8_t _marker_light_type;
  _marker_light_type marker_light;

   typedef uint8_t _emer_light_type;
  _emer_light_type emer_light;

   typedef uint8_t _trumpet_type;
  _trumpet_type trumpet;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _is_clean_type;
  _is_clean_type is_clean;





  typedef boost::shared_ptr< ::msg_v_decision::msg_v_decision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_v_decision::msg_v_decision_<ContainerAllocator> const> ConstPtr;

}; // struct msg_v_decision_

typedef ::msg_v_decision::msg_v_decision_<std::allocator<void> > msg_v_decision;

typedef boost::shared_ptr< ::msg_v_decision::msg_v_decision > msg_v_decisionPtr;
typedef boost::shared_ptr< ::msg_v_decision::msg_v_decision const> msg_v_decisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_v_decision::msg_v_decision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_v_decision::msg_v_decision_<ContainerAllocator1> & lhs, const ::msg_v_decision::msg_v_decision_<ContainerAllocator2> & rhs)
{
  return lhs.task_mode == rhs.task_mode &&
    lhs.target_id == rhs.target_id &&
    lhs.task_num == rhs.task_num &&
    lhs.task_state == rhs.task_state &&
    lhs.system_state == rhs.system_state &&
    lhs.obj_fuse == rhs.obj_fuse &&
    lhs.target_obstacle == rhs.target_obstacle &&
    lhs.dis2front == rhs.dis2front &&
    lhs.distance2vehicle == rhs.distance2vehicle &&
    lhs.distance2obstacle == rhs.distance2obstacle &&
    lhs.fault_info == rhs.fault_info &&
    lhs.event_report == rhs.event_report &&
    lhs.mode == rhs.mode &&
    lhs.is_update_map == rhs.is_update_map &&
    lhs.traj_id == rhs.traj_id &&
    lhs.way_point == rhs.way_point &&
    lhs.remote_spd == rhs.remote_spd &&
    lhs.remote_steering == rhs.remote_steering &&
    lhs.remote_parking == rhs.remote_parking &&
    lhs.remote_stopengine == rhs.remote_stopengine &&
    lhs.remote_service_brake == rhs.remote_service_brake &&
    lhs.remote_park_brake == rhs.remote_park_brake &&
    lhs.remote_load_brake == rhs.remote_load_brake &&
    lhs.gear_num == rhs.gear_num &&
    lhs.carrier_control == rhs.carrier_control &&
    lhs.turn_light == rhs.turn_light &&
    lhs.dipped_light == rhs.dipped_light &&
    lhs.marker_light == rhs.marker_light &&
    lhs.emer_light == rhs.emer_light &&
    lhs.trumpet == rhs.trumpet &&
    lhs.is_clean == rhs.is_clean;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_v_decision::msg_v_decision_<ContainerAllocator1> & lhs, const ::msg_v_decision::msg_v_decision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_v_decision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_decision::msg_v_decision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_decision::msg_v_decision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_decision::msg_v_decision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9972371d5850ca25138bae62dc721d39";
  }

  static const char* value(const ::msg_v_decision::msg_v_decision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9972371d5850ca25ULL;
  static const uint64_t static_value2 = 0x138bae62dc721d39ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_v_decision/msg_v_decision";
  }

  static const char* value(const ::msg_v_decision::msg_v_decision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 task_mode   #(任务类型)前往装载点:10001 前往装载区候车区:10002 前往卸载点:10003 前往卸载候车区:10004 前往停车场停车点:10005 前往停车候车区:10006 取消当前:10007 保持当前任务:10008\n"
"uint16 target_id #0保留  1自检  2启动发动机  3静态测试  4待机  5路径跟踪 6路口通行 7路口等待 8卸载...\n"
"uint16 task_num	#任务编号\n"
"uint16 task_state	#任务状态	0：保留  1：未就绪  2：执行中  3：完成/等待\n"
"int32 system_state #(矿卡当前模式状态) 自检:20001 启动发动机:20002 静态测试:20003 轨迹跟随:20004 排队停车:20005 跟车模式:20006 后台轨迹跟随:20007 卸载模式:20008 装载模式:20009 安全停车:20010 关闭发动机:20011 紧急停车:20012 待机:20013 装载完成:20014 后台绕障:20015\n"
"\n"
"msg_obj/Obj[] obj_fuse  	#障碍物信息结构体\n"
"msg_obj/Obj[] target_obstacle  #距离自车最近障碍物\n"
"float32 dis2front  		#自车与前车距离\n"
"float32 distance2vehicle	#车辆与全局路径的最小横向距离差值\n"
"float32 distance2obstacle	#目标障碍物最近点最小横向距离差值\n"
"\n"
"msg_safety_diagn/DiagnDataStruct[] fault_info   #故障信息结构体\n"
"uint16 event_report #1：车端请求后台局部路径规划 2:车端到达装载点 装载状态切换后触发装载请求事件 3:车端完成卸载任务后出发卸载完成事件\n"
"uint8 mode	#(矿卡当前执行的模式)手动：0    自动：1    远程遥控：2\n"
"uint8 is_update_map #地图更新情况:0:未更新 1:更新成功 2:拒绝更新\n"
"uint32 traj_id\n"
"msg_common/WayPoint[] way_point\n"
"float32 remote_spd\n"
"float32 remote_steering\n"
"uint8 remote_parking\n"
"uint8 remote_stopengine\n"
"uint8 remote_service_brake #行车制动\n"
"uint8 remote_park_brake #停车制动\n"
"uint8 remote_load_brake #装载制动\n"
"uint8 gear_num 		#档位\n"
"uint8 carrier_control		#货舱控制信号\n"
"uint8 turn_light		#转向灯信号\n"
"uint8 dipped_light		#近光灯信号\n"
"uint8 marker_light		#示廓灯信号\n"
"uint8 emer_light		#紧急信号灯信号\n"
"uint8 trumpet			#喇叭信号\n"
"bool[] is_clean\n"
"\n"
"================================================================================\n"
"MSG: msg_obj/Obj\n"
"float64 x #单位m\n"
"float64 y #单位m\n"
"float64 z #单位m\n"
"float32 vx #单位m/s\n"
"float32 vy #单位m/s\n"
"float32 vz #单位m/s\n"
"float32 width #宽度，单位m\n"
"float32 length #长度，单位m\n"
"float32 height #高度，单位m\n"
"#float64 yaw_angle #横摆脚，角度信息，单位为度\n"
"uint8 track_state #跟踪状态,0：删除或无效；1：新的；2：测量的；3：预测的；4：待删除；5：待跟踪\n"
"uint8 predict_length #预测时长， 单位s\n"
"int32 type #障碍物类型, 0:未知；1：汽车；2：卡车；3：行人；4：摩托车；5自行车；6：大障碍物；7：小障碍物； 8：矿坑； 9：灰尘\n"
"uint32 type_age #障碍物类型时间长度，单位s\n"
"float32 orientation #障碍物形状方位角，单位度，\n"
"float32 bbox_yaw\n"
"float32 bbox_pitch\n"
"float32 bbox_roll\n"
"float32 ax #x轴加速度，单位m/s^2\n"
"float32 ay #y轴加速度，单位m/s^2\n"
"float32 az #z轴加速度，单位m/s^2\n"
"msg_common/Covariance cov     #协方差\n"
"uint8 type_certainty #障碍物类型确信度 0-100\n"
"uint8 obj_certainty #障碍物存在确信度, 0:无效；1：小于0.25；2：小于0.5;3：小于0.75;4：小于0.9;5：小于0.99;6：小于0.999\n"
"int8 source #数据来源编号，预设的传感器编号\n"
"msg_common/GridPoint[] contour_point #obj对象包含的点信息\n"
"uint32 id #跟踪之后给出的最终obj的id\n"
"uint8 absolute_motion #绝对的运动状态，0：未知; 1：静止；2：运动\n"
"uint8 relative_motion #相对车辆的运动状态，0：静止；1:迎面而来；2：远去；3：横越；4:未知\n"
"float32 orientation_rate #方向角速度\n"
"\n"
"================================================================================\n"
"MSG: msg_common/Covariance\n"
"float32[] value #矩阵值\n"
"int8 row #协方差行\n"
"int8 col #协方差列\n"
"================================================================================\n"
"MSG: msg_common/GridPoint\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
"================================================================================\n"
"MSG: msg_safety_diagn/DiagnDataStruct\n"
"int32 equip_num \n"
"int32 diagn_type\n"
"msg_obj/Obj[] obj_state\n"
"\n"
"================================================================================\n"
"MSG: msg_common/WayPoint\n"
"float64 x			#路径x坐标\n"
"float64 y			#路径y坐标\n"
"float64 z			#路径z坐标\n"
"float64 left			#距左边界值\n"
"float64 right			#距右边界值\n"
"float32 heading_angle		#路径的方向\n"
"float32 curvature		#曲率\n"
"float32 speed			#路径的速度\n"
"float32 distance		#路点与路径起点沿路径的距离\n"
"float32 slope			#坡度信息\n"
"uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)\n"
"float32 speed_limit	        #速度上限\n"
"uint8 direction			#0表示前进，1表示后退\n"
"uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点\n"
"float64 t			#时间\n"
"string area_name		#区域名称	\n"
"string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	\n"
;
  }

  static const char* value(const ::msg_v_decision::msg_v_decision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_mode);
      stream.next(m.target_id);
      stream.next(m.task_num);
      stream.next(m.task_state);
      stream.next(m.system_state);
      stream.next(m.obj_fuse);
      stream.next(m.target_obstacle);
      stream.next(m.dis2front);
      stream.next(m.distance2vehicle);
      stream.next(m.distance2obstacle);
      stream.next(m.fault_info);
      stream.next(m.event_report);
      stream.next(m.mode);
      stream.next(m.is_update_map);
      stream.next(m.traj_id);
      stream.next(m.way_point);
      stream.next(m.remote_spd);
      stream.next(m.remote_steering);
      stream.next(m.remote_parking);
      stream.next(m.remote_stopengine);
      stream.next(m.remote_service_brake);
      stream.next(m.remote_park_brake);
      stream.next(m.remote_load_brake);
      stream.next(m.gear_num);
      stream.next(m.carrier_control);
      stream.next(m.turn_light);
      stream.next(m.dipped_light);
      stream.next(m.marker_light);
      stream.next(m.emer_light);
      stream.next(m.trumpet);
      stream.next(m.is_clean);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_v_decision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_v_decision::msg_v_decision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_v_decision::msg_v_decision_<ContainerAllocator>& v)
  {
    s << indent << "task_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_mode);
    s << indent << "target_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_id);
    s << indent << "task_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.task_num);
    s << indent << "task_state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.task_state);
    s << indent << "system_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.system_state);
    s << indent << "obj_fuse[]" << std::endl;
    for (size_t i = 0; i < v.obj_fuse.size(); ++i)
    {
      s << indent << "  obj_fuse[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_obj::Obj_<ContainerAllocator> >::stream(s, indent + "    ", v.obj_fuse[i]);
    }
    s << indent << "target_obstacle[]" << std::endl;
    for (size_t i = 0; i < v.target_obstacle.size(); ++i)
    {
      s << indent << "  target_obstacle[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_obj::Obj_<ContainerAllocator> >::stream(s, indent + "    ", v.target_obstacle[i]);
    }
    s << indent << "dis2front: ";
    Printer<float>::stream(s, indent + "  ", v.dis2front);
    s << indent << "distance2vehicle: ";
    Printer<float>::stream(s, indent + "  ", v.distance2vehicle);
    s << indent << "distance2obstacle: ";
    Printer<float>::stream(s, indent + "  ", v.distance2obstacle);
    s << indent << "fault_info[]" << std::endl;
    for (size_t i = 0; i < v.fault_info.size(); ++i)
    {
      s << indent << "  fault_info[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_safety_diagn::DiagnDataStruct_<ContainerAllocator> >::stream(s, indent + "    ", v.fault_info[i]);
    }
    s << indent << "event_report: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.event_report);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "is_update_map: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_update_map);
    s << indent << "traj_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "way_point[]" << std::endl;
    for (size_t i = 0; i < v.way_point.size(); ++i)
    {
      s << indent << "  way_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_common::WayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.way_point[i]);
    }
    s << indent << "remote_spd: ";
    Printer<float>::stream(s, indent + "  ", v.remote_spd);
    s << indent << "remote_steering: ";
    Printer<float>::stream(s, indent + "  ", v.remote_steering);
    s << indent << "remote_parking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_parking);
    s << indent << "remote_stopengine: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_stopengine);
    s << indent << "remote_service_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_service_brake);
    s << indent << "remote_park_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_park_brake);
    s << indent << "remote_load_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_load_brake);
    s << indent << "gear_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_num);
    s << indent << "carrier_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carrier_control);
    s << indent << "turn_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_light);
    s << indent << "dipped_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dipped_light);
    s << indent << "marker_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_light);
    s << indent << "emer_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emer_light);
    s << indent << "trumpet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trumpet);
    s << indent << "is_clean[]" << std::endl;
    for (size_t i = 0; i < v.is_clean.size(); ++i)
    {
      s << indent << "  is_clean[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.is_clean[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_V_DECISION_MESSAGE_MSG_V_DECISION_H
