// Generated by gencpp from file msg_v_decision/RqtplotMsg.msg
// DO NOT EDIT!


#ifndef MSG_V_DECISION_MESSAGE_RQTPLOTMSG_H
#define MSG_V_DECISION_MESSAGE_RQTPLOTMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_v_decision
{
template <class ContainerAllocator>
struct RqtplotMsg_
{
  typedef RqtplotMsg_<ContainerAllocator> Type;

  RqtplotMsg_()
    : selfspeed(0.0)
    , frontspeed(0.0)
    , dis2front(0.0)
    , desiredspeed(0.0)
    , global_speed(0.0)
    , dis2vehicle(0.0)
    , dis2obstacle(0.0)  {
    }
  RqtplotMsg_(const ContainerAllocator& _alloc)
    : selfspeed(0.0)
    , frontspeed(0.0)
    , dis2front(0.0)
    , desiredspeed(0.0)
    , global_speed(0.0)
    , dis2vehicle(0.0)
    , dis2obstacle(0.0)  {
  (void)_alloc;
    }



   typedef float _selfspeed_type;
  _selfspeed_type selfspeed;

   typedef float _frontspeed_type;
  _frontspeed_type frontspeed;

   typedef float _dis2front_type;
  _dis2front_type dis2front;

   typedef float _desiredspeed_type;
  _desiredspeed_type desiredspeed;

   typedef float _global_speed_type;
  _global_speed_type global_speed;

   typedef float _dis2vehicle_type;
  _dis2vehicle_type dis2vehicle;

   typedef float _dis2obstacle_type;
  _dis2obstacle_type dis2obstacle;





  typedef boost::shared_ptr< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RqtplotMsg_

typedef ::msg_v_decision::RqtplotMsg_<std::allocator<void> > RqtplotMsg;

typedef boost::shared_ptr< ::msg_v_decision::RqtplotMsg > RqtplotMsgPtr;
typedef boost::shared_ptr< ::msg_v_decision::RqtplotMsg const> RqtplotMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_v_decision::RqtplotMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_v_decision::RqtplotMsg_<ContainerAllocator1> & lhs, const ::msg_v_decision::RqtplotMsg_<ContainerAllocator2> & rhs)
{
  return lhs.selfspeed == rhs.selfspeed &&
    lhs.frontspeed == rhs.frontspeed &&
    lhs.dis2front == rhs.dis2front &&
    lhs.desiredspeed == rhs.desiredspeed &&
    lhs.global_speed == rhs.global_speed &&
    lhs.dis2vehicle == rhs.dis2vehicle &&
    lhs.dis2obstacle == rhs.dis2obstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_v_decision::RqtplotMsg_<ContainerAllocator1> & lhs, const ::msg_v_decision::RqtplotMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_v_decision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74b462951a3217bd8dcef08e73ccad53";
  }

  static const char* value(const ::msg_v_decision::RqtplotMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74b462951a3217bdULL;
  static const uint64_t static_value2 = 0x8dcef08e73ccad53ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_v_decision/RqtplotMsg";
  }

  static const char* value(const ::msg_v_decision::RqtplotMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 selfspeed    #自车速度 km/h\n"
"float32 frontspeed   #前车速度 km/h\n"
"float32 dis2front    #自车与前车距离 m\n"
"float32 desiredspeed #期望速度 km/h\n"
"float32 global_speed #全局速度 km/h\n"
"float32 dis2vehicle  #车辆与全局路径的最小横向距离差值\n"
"float32 dis2obstacle #目标障碍物最近点最小横向距离差值\n"
;
  }

  static const char* value(const ::msg_v_decision::RqtplotMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.selfspeed);
      stream.next(m.frontspeed);
      stream.next(m.dis2front);
      stream.next(m.desiredspeed);
      stream.next(m.global_speed);
      stream.next(m.dis2vehicle);
      stream.next(m.dis2obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RqtplotMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_v_decision::RqtplotMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_v_decision::RqtplotMsg_<ContainerAllocator>& v)
  {
    s << indent << "selfspeed: ";
    Printer<float>::stream(s, indent + "  ", v.selfspeed);
    s << indent << "frontspeed: ";
    Printer<float>::stream(s, indent + "  ", v.frontspeed);
    s << indent << "dis2front: ";
    Printer<float>::stream(s, indent + "  ", v.dis2front);
    s << indent << "desiredspeed: ";
    Printer<float>::stream(s, indent + "  ", v.desiredspeed);
    s << indent << "global_speed: ";
    Printer<float>::stream(s, indent + "  ", v.global_speed);
    s << indent << "dis2vehicle: ";
    Printer<float>::stream(s, indent + "  ", v.dis2vehicle);
    s << indent << "dis2obstacle: ";
    Printer<float>::stream(s, indent + "  ", v.dis2obstacle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_V_DECISION_MESSAGE_RQTPLOTMSG_H
