// Generated by gencpp from file msg_gnss_prep/msg_gnss_prep.msg
// DO NOT EDIT!


#ifndef MSG_GNSS_PREP_MESSAGE_MSG_GNSS_PREP_H
#define MSG_GNSS_PREP_MESSAGE_MSG_GNSS_PREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gnss_prep
{
template <class ContainerAllocator>
struct msg_gnss_prep_
{
  typedef msg_gnss_prep_<ContainerAllocator> Type;

  msg_gnss_prep_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , spd_east(0.0)
    , spd_north(0.0)
    , spd_down(0.0)
    , heading_angle(0.0)
    , yaw_angle(0.0)
    , yaw_rate(0.0)
    , pitch_angle(0.0)
    , roll_angle(0.0)
    , speed(0.0)
    , spd_lon(0.0)
    , spd_lat(0.0)
    , acce(0.0)
    , acce_lon(0.0)
    , acce_lat(0.0)
    , flag(0)
    , gps_status(0)  {
    }
  msg_gnss_prep_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , height(0.0)
    , spd_east(0.0)
    , spd_north(0.0)
    , spd_down(0.0)
    , heading_angle(0.0)
    , yaw_angle(0.0)
    , yaw_rate(0.0)
    , pitch_angle(0.0)
    , roll_angle(0.0)
    , speed(0.0)
    , spd_lon(0.0)
    , spd_lat(0.0)
    , acce(0.0)
    , acce_lon(0.0)
    , acce_lat(0.0)
    , flag(0)
    , gps_status(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_type;
  _height_type height;

   typedef float _spd_east_type;
  _spd_east_type spd_east;

   typedef float _spd_north_type;
  _spd_north_type spd_north;

   typedef float _spd_down_type;
  _spd_down_type spd_down;

   typedef float _heading_angle_type;
  _heading_angle_type heading_angle;

   typedef float _yaw_angle_type;
  _yaw_angle_type yaw_angle;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef float _pitch_angle_type;
  _pitch_angle_type pitch_angle;

   typedef float _roll_angle_type;
  _roll_angle_type roll_angle;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _spd_lon_type;
  _spd_lon_type spd_lon;

   typedef float _spd_lat_type;
  _spd_lat_type spd_lat;

   typedef float _acce_type;
  _acce_type acce;

   typedef float _acce_lon_type;
  _acce_lon_type acce_lon;

   typedef float _acce_lat_type;
  _acce_lat_type acce_lat;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef uint8_t _gps_status_type;
  _gps_status_type gps_status;





  typedef boost::shared_ptr< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> const> ConstPtr;

}; // struct msg_gnss_prep_

typedef ::msg_gnss_prep::msg_gnss_prep_<std::allocator<void> > msg_gnss_prep;

typedef boost::shared_ptr< ::msg_gnss_prep::msg_gnss_prep > msg_gnss_prepPtr;
typedef boost::shared_ptr< ::msg_gnss_prep::msg_gnss_prep const> msg_gnss_prepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator1> & lhs, const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.height == rhs.height &&
    lhs.spd_east == rhs.spd_east &&
    lhs.spd_north == rhs.spd_north &&
    lhs.spd_down == rhs.spd_down &&
    lhs.heading_angle == rhs.heading_angle &&
    lhs.yaw_angle == rhs.yaw_angle &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.pitch_angle == rhs.pitch_angle &&
    lhs.roll_angle == rhs.roll_angle &&
    lhs.speed == rhs.speed &&
    lhs.spd_lon == rhs.spd_lon &&
    lhs.spd_lat == rhs.spd_lat &&
    lhs.acce == rhs.acce &&
    lhs.acce_lon == rhs.acce_lon &&
    lhs.acce_lat == rhs.acce_lat &&
    lhs.flag == rhs.flag &&
    lhs.gps_status == rhs.gps_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator1> & lhs, const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gnss_prep

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e134d5a1a517850320e9c8189731570d";
  }

  static const char* value(const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe134d5a1a5178503ULL;
  static const uint64_t static_value2 = 0x20e9c8189731570dULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gnss_prep/msg_gnss_prep";
  }

  static const char* value(const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 height\n"
"float32 spd_east\n"
"float32 spd_north\n"
"float32 spd_down\n"
"float32 heading_angle\n"
"float32 yaw_angle\n"
"float32 yaw_rate\n"
"float32 pitch_angle\n"
"float32 roll_angle\n"
"float32 speed\n"
"float32 spd_lon\n"
"float32 spd_lat\n"
"float32 acce\n"
"float32 acce_lon\n"
"float32 acce_lat\n"
"uint8 flag\n"
"uint8 gps_status\n"
"\n"
;
  }

  static const char* value(const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
      stream.next(m.spd_east);
      stream.next(m.spd_north);
      stream.next(m.spd_down);
      stream.next(m.heading_angle);
      stream.next(m.yaw_angle);
      stream.next(m.yaw_rate);
      stream.next(m.pitch_angle);
      stream.next(m.roll_angle);
      stream.next(m.speed);
      stream.next(m.spd_lon);
      stream.next(m.spd_lat);
      stream.next(m.acce);
      stream.next(m.acce_lon);
      stream.next(m.acce_lat);
      stream.next(m.flag);
      stream.next(m.gps_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_gnss_prep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gnss_prep::msg_gnss_prep_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "spd_east: ";
    Printer<float>::stream(s, indent + "  ", v.spd_east);
    s << indent << "spd_north: ";
    Printer<float>::stream(s, indent + "  ", v.spd_north);
    s << indent << "spd_down: ";
    Printer<float>::stream(s, indent + "  ", v.spd_down);
    s << indent << "heading_angle: ";
    Printer<float>::stream(s, indent + "  ", v.heading_angle);
    s << indent << "yaw_angle: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_angle);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "pitch_angle: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_angle);
    s << indent << "roll_angle: ";
    Printer<float>::stream(s, indent + "  ", v.roll_angle);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "spd_lon: ";
    Printer<float>::stream(s, indent + "  ", v.spd_lon);
    s << indent << "spd_lat: ";
    Printer<float>::stream(s, indent + "  ", v.spd_lat);
    s << indent << "acce: ";
    Printer<float>::stream(s, indent + "  ", v.acce);
    s << indent << "acce_lon: ";
    Printer<float>::stream(s, indent + "  ", v.acce_lon);
    s << indent << "acce_lat: ";
    Printer<float>::stream(s, indent + "  ", v.acce_lat);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "gps_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GNSS_PREP_MESSAGE_MSG_GNSS_PREP_H
