# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_obj/Obj.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_common.msg

class Obj(genpy.Message):
  _md5sum = "eaf612e7800921f7863714bc6541d95c"
  _type = "msg_obj/Obj"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x #单位m
float64 y #单位m
float64 z #单位m
float32 vx #单位m/s
float32 vy #单位m/s
float32 vz #单位m/s
float32 width #宽度，单位m
float32 length #长度，单位m
float32 height #高度，单位m
#float64 yaw_angle #横摆脚，角度信息，单位为度
uint8 track_state #跟踪状态,0：删除或无效；1：新的；2：测量的；3：预测的；4：待删除；5：待跟踪
uint8 predict_length #预测时长， 单位s
int32 type #障碍物类型, 0:未知；1：汽车；2：卡车；3：行人；4：摩托车；5自行车；6：大障碍物；7：小障碍物； 8：矿坑； 9：灰尘
uint32 type_age #障碍物类型时间长度，单位s
float32 orientation #障碍物形状方位角，单位度，
float32 bbox_yaw
float32 bbox_pitch
float32 bbox_roll
float32 ax #x轴加速度，单位m/s^2
float32 ay #y轴加速度，单位m/s^2
float32 az #z轴加速度，单位m/s^2
msg_common/Covariance cov     #协方差
uint8 type_certainty #障碍物类型确信度 0-100
uint8 obj_certainty #障碍物存在确信度, 0:无效；1：小于0.25；2：小于0.5;3：小于0.75;4：小于0.9;5：小于0.99;6：小于0.999
int8 source #数据来源编号，预设的传感器编号
msg_common/GridPoint[] contour_point #obj对象包含的点信息
uint32 id #跟踪之后给出的最终obj的id
uint8 absolute_motion #绝对的运动状态，0：未知; 1：静止；2：运动
uint8 relative_motion #相对车辆的运动状态，0：静止；1:迎面而来；2：远去；3：横越；4:未知
float32 orientation_rate #方向角速度

================================================================================
MSG: msg_common/Covariance
float32[] value #矩阵值
int8 row #协方差行
int8 col #协方差列
================================================================================
MSG: msg_common/GridPoint
float64 x
float64 y
float64 z
float32 length
float32 width
float32 height"""
  __slots__ = ['x','y','z','vx','vy','vz','width','length','height','track_state','predict_length','type','type_age','orientation','bbox_yaw','bbox_pitch','bbox_roll','ax','ay','az','cov','type_certainty','obj_certainty','source','contour_point','id','absolute_motion','relative_motion','orientation_rate']
  _slot_types = ['float64','float64','float64','float32','float32','float32','float32','float32','float32','uint8','uint8','int32','uint32','float32','float32','float32','float32','float32','float32','float32','msg_common/Covariance','uint8','uint8','int8','msg_common/GridPoint[]','uint32','uint8','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,vx,vy,vz,width,length,height,track_state,predict_length,type,type_age,orientation,bbox_yaw,bbox_pitch,bbox_roll,ax,ay,az,cov,type_certainty,obj_certainty,source,contour_point,id,absolute_motion,relative_motion,orientation_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Obj, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.vz is None:
        self.vz = 0.
      if self.width is None:
        self.width = 0.
      if self.length is None:
        self.length = 0.
      if self.height is None:
        self.height = 0.
      if self.track_state is None:
        self.track_state = 0
      if self.predict_length is None:
        self.predict_length = 0
      if self.type is None:
        self.type = 0
      if self.type_age is None:
        self.type_age = 0
      if self.orientation is None:
        self.orientation = 0.
      if self.bbox_yaw is None:
        self.bbox_yaw = 0.
      if self.bbox_pitch is None:
        self.bbox_pitch = 0.
      if self.bbox_roll is None:
        self.bbox_roll = 0.
      if self.ax is None:
        self.ax = 0.
      if self.ay is None:
        self.ay = 0.
      if self.az is None:
        self.az = 0.
      if self.cov is None:
        self.cov = msg_common.msg.Covariance()
      if self.type_certainty is None:
        self.type_certainty = 0
      if self.obj_certainty is None:
        self.obj_certainty = 0
      if self.source is None:
        self.source = 0
      if self.contour_point is None:
        self.contour_point = []
      if self.id is None:
        self.id = 0
      if self.absolute_motion is None:
        self.absolute_motion = 0
      if self.relative_motion is None:
        self.relative_motion = 0
      if self.orientation_rate is None:
        self.orientation_rate = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.vx = 0.
      self.vy = 0.
      self.vz = 0.
      self.width = 0.
      self.length = 0.
      self.height = 0.
      self.track_state = 0
      self.predict_length = 0
      self.type = 0
      self.type_age = 0
      self.orientation = 0.
      self.bbox_yaw = 0.
      self.bbox_pitch = 0.
      self.bbox_roll = 0.
      self.ax = 0.
      self.ay = 0.
      self.az = 0.
      self.cov = msg_common.msg.Covariance()
      self.type_certainty = 0
      self.obj_certainty = 0
      self.source = 0
      self.contour_point = []
      self.id = 0
      self.absolute_motion = 0
      self.relative_motion = 0
      self.orientation_rate = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
      length = len(self.cov.value)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.cov.value))
      _x = self
      buff.write(_get_struct_2b2Bb().pack(_x.cov.row, _x.cov.col, _x.type_certainty, _x.obj_certainty, _x.source))
      length = len(self.contour_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.contour_point:
        _x = val1
        buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
      _x = self
      buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cov is None:
        self.cov = msg_common.msg.Covariance()
      if self.contour_point is None:
        self.contour_point = None
      end = 0
      _x = self
      start = end
      end += 86
      (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cov.value = s.unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.cov.row, _x.cov.col, _x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2b2Bb().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.contour_point = []
      for i in range(0, length):
        val1 = msg_common.msg.GridPoint()
        _x = val1
        start = end
        end += 36
        (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
        self.contour_point.append(val1)
      _x = self
      start = end
      end += 10
      (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d6f2BiI7f().pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az))
      length = len(self.cov.value)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.cov.value.tostring())
      _x = self
      buff.write(_get_struct_2b2Bb().pack(_x.cov.row, _x.cov.col, _x.type_certainty, _x.obj_certainty, _x.source))
      length = len(self.contour_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.contour_point:
        _x = val1
        buff.write(_get_struct_3d3f().pack(_x.x, _x.y, _x.z, _x.length, _x.width, _x.height))
      _x = self
      buff.write(_get_struct_I2Bf().pack(_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cov is None:
        self.cov = msg_common.msg.Covariance()
      if self.contour_point is None:
        self.contour_point = None
      end = 0
      _x = self
      start = end
      end += 86
      (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.width, _x.length, _x.height, _x.track_state, _x.predict_length, _x.type, _x.type_age, _x.orientation, _x.bbox_yaw, _x.bbox_pitch, _x.bbox_roll, _x.ax, _x.ay, _x.az,) = _get_struct_3d6f2BiI7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.cov.value = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 5
      (_x.cov.row, _x.cov.col, _x.type_certainty, _x.obj_certainty, _x.source,) = _get_struct_2b2Bb().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.contour_point = []
      for i in range(0, length):
        val1 = msg_common.msg.GridPoint()
        _x = val1
        start = end
        end += 36
        (_x.x, _x.y, _x.z, _x.length, _x.width, _x.height,) = _get_struct_3d3f().unpack(str[start:end])
        self.contour_point.append(val1)
      _x = self
      start = end
      end += 10
      (_x.id, _x.absolute_motion, _x.relative_motion, _x.orientation_rate,) = _get_struct_I2Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b2Bb = None
def _get_struct_2b2Bb():
    global _struct_2b2Bb
    if _struct_2b2Bb is None:
        _struct_2b2Bb = struct.Struct("<2b2Bb")
    return _struct_2b2Bb
_struct_3d3f = None
def _get_struct_3d3f():
    global _struct_3d3f
    if _struct_3d3f is None:
        _struct_3d3f = struct.Struct("<3d3f")
    return _struct_3d3f
_struct_3d6f2BiI7f = None
def _get_struct_3d6f2BiI7f():
    global _struct_3d6f2BiI7f
    if _struct_3d6f2BiI7f is None:
        _struct_3d6f2BiI7f = struct.Struct("<3d6f2BiI7f")
    return _struct_3d6f2BiI7f
_struct_I2Bf = None
def _get_struct_I2Bf():
    global _struct_I2Bf
    if _struct_I2Bf is None:
        _struct_I2Bf = struct.Struct("<I2Bf")
    return _struct_I2Bf
