(cl:in-package msg_v_state-msg)
(cl:export '(HEADER-VAL
          HEADER
          GPS_STATUS-VAL
          GPS_STATUS
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_TIME-VAL
          GPS_TIME
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          HEADING_ANGLE-VAL
          HEADING_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          YAW_RATE-VAL
          YAW_RATE
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          PITCH_RATE-VAL
          PITCH_RATE
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          ROLL_RATE-VAL
          ROLL_RATE
          SPD_EAST-VAL
          SPD_EAST
          SPD_NORTH-VAL
          SPD_NORTH
          SPD_UP-VAL
          SPD_UP
          SPD-VAL
          SPD
          SPD_LON-VAL
          SPD_LON
          SPD_LAT-VAL
          SPD_LAT
          ACCE-VAL
          ACCE
          ACCE_LON-VAL
          ACCE_LON
          ACCE_LAT-VAL
          ACCE_LAT
          STATIC_CHECK-VAL
          STATIC_CHECK
          AUTO_STATUS_MODE-VAL
          AUTO_STATUS_MODE
          AUTO_STATUS_READY-VAL
          AUTO_STATUS_READY
          AUTO_STATUS_INTERVENE-VAL
          AUTO_STATUS_INTERVENE
          SPEED-VAL
          SPEED
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          STEER_CONTROL_STATUS-VAL
          STEER_CONTROL_STATUS
          STEERING_SPD-VAL
          STEERING_SPD
          WHEEL_ANGLE-VAL
          WHEEL_ANGLE
          TARGET_STEERING_ANGLE-VAL
          TARGET_STEERING_ANGLE
          TRQ-VAL
          TRQ
          TARGET_TRQ-VAL
          TARGET_TRQ
          THR_ANGLE-VAL
          THR_ANGLE
          GEAR_NUM-VAL
          GEAR_NUM
          EMERG_STATE-VAL
          EMERG_STATE
          BRAKING_DECE-VAL
          BRAKING_DECE
          FUEL_NUM-VAL
          FUEL_NUM
          PARK_BRK-VAL
          PARK_BRK
          CARRIER_ANGLE-VAL
          CARRIER_ANGLE
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          BACKUP_LIGHT-VAL
          BACKUP_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          CARRIRE_WARM_LIGHT-VAL
          CARRIRE_WARM_LIGHT
          ILLUMINATION_LIGHT-VAL
          ILLUMINATION_LIGHT
          TRUMPET-VAL
          TRUMPET
          PTO_STATUS-VAL
          PTO_STATUS
          BRIM_STATE-VAL
          BRIM_STATE
          CLEAN_STATUS-VAL
          CLEAN_STATUS
          SWITCH_STATUS-VAL
          SWITCH_STATUS
))