// Generated by gencpp from file msg_imu_prep/msg_imu_prep.msg
// DO NOT EDIT!


#ifndef MSG_IMU_PREP_MESSAGE_MSG_IMU_PREP_H
#define MSG_IMU_PREP_MESSAGE_MSG_IMU_PREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_imu_prep
{
template <class ContainerAllocator>
struct msg_imu_prep_
{
  typedef msg_imu_prep_<ContainerAllocator> Type;

  msg_imu_prep_()
    : acce_x(0.0)
    , acce_y(0.0)
    , acce_z(0.0)
    , pals_x(0.0)
    , pals_y(0.0)
    , pals_z(0.0)  {
    }
  msg_imu_prep_(const ContainerAllocator& _alloc)
    : acce_x(0.0)
    , acce_y(0.0)
    , acce_z(0.0)
    , pals_x(0.0)
    , pals_y(0.0)
    , pals_z(0.0)  {
  (void)_alloc;
    }



   typedef float _acce_x_type;
  _acce_x_type acce_x;

   typedef float _acce_y_type;
  _acce_y_type acce_y;

   typedef float _acce_z_type;
  _acce_z_type acce_z;

   typedef float _pals_x_type;
  _pals_x_type pals_x;

   typedef float _pals_y_type;
  _pals_y_type pals_y;

   typedef float _pals_z_type;
  _pals_z_type pals_z;





  typedef boost::shared_ptr< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> const> ConstPtr;

}; // struct msg_imu_prep_

typedef ::msg_imu_prep::msg_imu_prep_<std::allocator<void> > msg_imu_prep;

typedef boost::shared_ptr< ::msg_imu_prep::msg_imu_prep > msg_imu_prepPtr;
typedef boost::shared_ptr< ::msg_imu_prep::msg_imu_prep const> msg_imu_prepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator1> & lhs, const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator2> & rhs)
{
  return lhs.acce_x == rhs.acce_x &&
    lhs.acce_y == rhs.acce_y &&
    lhs.acce_z == rhs.acce_z &&
    lhs.pals_x == rhs.pals_x &&
    lhs.pals_y == rhs.pals_y &&
    lhs.pals_z == rhs.pals_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator1> & lhs, const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_imu_prep

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fea41e4b55f2b301664a8d463d24fcb";
  }

  static const char* value(const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fea41e4b55f2b30ULL;
  static const uint64_t static_value2 = 0x1664a8d463d24fcbULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_imu_prep/msg_imu_prep";
  }

  static const char* value(const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 acce_x		#惯性系下沿x轴加速度 \n"
"float32 acce_y		#惯性系下沿y轴加速度 \n"
"float32 acce_z		#惯性系下沿z轴加速度 \n"
"float32 pals_x		#惯性系下绕x轴角速度 \n"
"float32 pals_y		#惯性系下绕y轴角速度 \n"
"float32 pals_z		#惯性系下绕z轴角速度 \n"
;
  }

  static const char* value(const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acce_x);
      stream.next(m.acce_y);
      stream.next(m.acce_z);
      stream.next(m.pals_x);
      stream.next(m.pals_y);
      stream.next(m.pals_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_imu_prep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_imu_prep::msg_imu_prep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_imu_prep::msg_imu_prep_<ContainerAllocator>& v)
  {
    s << indent << "acce_x: ";
    Printer<float>::stream(s, indent + "  ", v.acce_x);
    s << indent << "acce_y: ";
    Printer<float>::stream(s, indent + "  ", v.acce_y);
    s << indent << "acce_z: ";
    Printer<float>::stream(s, indent + "  ", v.acce_z);
    s << indent << "pals_x: ";
    Printer<float>::stream(s, indent + "  ", v.pals_x);
    s << indent << "pals_y: ";
    Printer<float>::stream(s, indent + "  ", v.pals_y);
    s << indent << "pals_z: ";
    Printer<float>::stream(s, indent + "  ", v.pals_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_IMU_PREP_MESSAGE_MSG_IMU_PREP_H
