# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_global_planning/msg_global_planning.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import msg_common.msg

class msg_global_planning(genpy.Message):
  _md5sum = "795e276f86cc7924b4ca1a4fae9f02fc"
  _type = "msg_global_planning/msg_global_planning"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 target_id	        #target_id
msg_common/WayPoint[] way_point		#路径
float32 remote_spd
float32 remote_steering
float32 remote_parking
uint32 traj_id
uint8 gear_num 			#档位
uint8 carrier_control		#货舱控制信号
uint8 turn_light		#转向灯信号
uint8 dipped_light		#近光灯信号
uint8 marker_light		#示廓灯信号
uint8 emer_light		#紧急信号灯信号
uint8 trumpet			#喇叭信号
string[] path_array		#路由路径，成员为区域名 


================================================================================
MSG: msg_common/WayPoint
float64 x			#路径x坐标
float64 y			#路径y坐标
float64 z			#路径z坐标
float64 left			#距左边界值
float64 right			#距右边界值
float32 heading_angle		#路径的方向
float32 curvature		#曲率
float32 speed			#路径的速度
float32 distance		#路点与路径起点沿路径的距离
float32 slope			#坡度信息
uint32  attribute		#属性(0: 进站路段 1: 出站路段 2: 路口路段(圆弧) 3:常规路段)
float32 speed_limit	        #速度上限
uint8 direction			#0表示前进，1表示后退
uint8 waypointattr		#路点属性，1代表是参考路径上的点，2代表混合AStar搜出来的点
float64 t			#时间
string area_name		#区域名称	
string onareaid			#混合AStar搜出来的点为区域名，参考路径上的点为参考路径所在的区域(与点所在的区域无关)	
"""
  __slots__ = ['target_id','way_point','remote_spd','remote_steering','remote_parking','traj_id','gear_num','carrier_control','turn_light','dipped_light','marker_light','emer_light','trumpet','path_array']
  _slot_types = ['int32','msg_common/WayPoint[]','float32','float32','float32','uint32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','string[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_id,way_point,remote_spd,remote_steering,remote_parking,traj_id,gear_num,carrier_control,turn_light,dipped_light,marker_light,emer_light,trumpet,path_array

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_global_planning, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target_id is None:
        self.target_id = 0
      if self.way_point is None:
        self.way_point = []
      if self.remote_spd is None:
        self.remote_spd = 0.
      if self.remote_steering is None:
        self.remote_steering = 0.
      if self.remote_parking is None:
        self.remote_parking = 0.
      if self.traj_id is None:
        self.traj_id = 0
      if self.gear_num is None:
        self.gear_num = 0
      if self.carrier_control is None:
        self.carrier_control = 0
      if self.turn_light is None:
        self.turn_light = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.trumpet is None:
        self.trumpet = 0
      if self.path_array is None:
        self.path_array = []
    else:
      self.target_id = 0
      self.way_point = []
      self.remote_spd = 0.
      self.remote_steering = 0.
      self.remote_parking = 0.
      self.traj_id = 0
      self.gear_num = 0
      self.carrier_control = 0
      self.turn_light = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.emer_light = 0
      self.trumpet = 0
      self.path_array = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.target_id
      buff.write(_get_struct_i().pack(_x))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3fI7B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.traj_id, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet))
      length = len(self.path_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.path_array:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.way_point is None:
        self.way_point = None
      end = 0
      start = end
      end += 4
      (self.target_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.way_point.append(val1)
      _x = self
      start = end
      end += 23
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.traj_id, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet,) = _get_struct_3fI7B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.path_array = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.path_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.target_id
      buff.write(_get_struct_i().pack(_x))
      length = len(self.way_point)
      buff.write(_struct_I.pack(length))
      for val1 in self.way_point:
        _x = val1
        buff.write(_get_struct_5d5fIf2Bd().pack(_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t))
        _x = val1.area_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.onareaid
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3fI7B().pack(_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.traj_id, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet))
      length = len(self.path_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.path_array:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.way_point is None:
        self.way_point = None
      end = 0
      start = end
      end += 4
      (self.target_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.way_point = []
      for i in range(0, length):
        val1 = msg_common.msg.WayPoint()
        _x = val1
        start = end
        end += 78
        (_x.x, _x.y, _x.z, _x.left, _x.right, _x.heading_angle, _x.curvature, _x.speed, _x.distance, _x.slope, _x.attribute, _x.speed_limit, _x.direction, _x.waypointattr, _x.t,) = _get_struct_5d5fIf2Bd().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.area_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.area_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.onareaid = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.onareaid = str[start:end]
        self.way_point.append(val1)
      _x = self
      start = end
      end += 23
      (_x.remote_spd, _x.remote_steering, _x.remote_parking, _x.traj_id, _x.gear_num, _x.carrier_control, _x.turn_light, _x.dipped_light, _x.marker_light, _x.emer_light, _x.trumpet,) = _get_struct_3fI7B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.path_array = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = str[start:end]
        self.path_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fI7B = None
def _get_struct_3fI7B():
    global _struct_3fI7B
    if _struct_3fI7B is None:
        _struct_3fI7B = struct.Struct("<3fI7B")
    return _struct_3fI7B
_struct_5d5fIf2Bd = None
def _get_struct_5d5fIf2Bd():
    global _struct_5d5fIf2Bd
    if _struct_5d5fIf2Bd is None:
        _struct_5d5fIf2Bd = struct.Struct("<5d5fIf2Bd")
    return _struct_5d5fIf2Bd
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
