# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_v_control/msg_v_control.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class msg_v_control(genpy.Message):
  _md5sum = "22edec3cff924e8fcb908dbc10ac7aff"
  _type = "msg_v_control/msg_v_control"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """char static_check                 # 0:no commend; 1: checking; 2: pass check; 4: check failed
float64 steering_angle            # Steering angle. Unit: deg.
float64 steering_spd              # Steering speed. Unit: deg/s.
int32 thr_angle                   # Throttle angle. Unit: %.
float32 brake_pressure            # Brake pressure. Unit: MPa.
float32 brk_current               # Unit: %.
char   flag                       # Drive: 1; Brake: 2; Emergency brake: 3.
char   engine_ctr                 # No operation: 0; turn off: 1; start: 2.
char   park_brk                   # Turn off: 0; start: 1.
char   load_brk                   # Turn off: 0; start: 1.
char   carrier_control            # Rising: 0; keep: 1; floating: 2; decline: 3;
float32 dumpbed_ctr               # dumpbed level, %
char   turn_light                 # Turn off: 0; turn on the right: 1; turn on the left: 2;
int32  gear_num
int32  gear_cmd
int32  gear_flag
int32  gear_cleardriver
char   dipped_light               # Turn off: 0; turn on the near light: 1; turn on the high beam: 2;
char   marker_light               # Turn off: 0; turn on: 1;
char   brake_light                # Turn off: 0; turn on: 1;
char   emer_light                 # Turn off: 0; turn on: 1;
char   trumpet                    # Turn off: 0; turn on: 1;
char   state_light                # Under power state: 0; silent mode: 1; automatic driving mode: 2; remote control mode: 3; Manual driving mode: 4;
char   rest_off_ctr               # Turn off: 1; turn on: 0;
char   lube_ctr                   # Turn off: 0; turn on: 1;
char   auto_cmd                   # Manual: 0; Auto: 1;
char   override_cmd               # Off: 0; On: 1;
char   light_ctr                  # Off: 0; Red: 1; Yellow: 2; Blue: 4;"""
  __slots__ = ['static_check','steering_angle','steering_spd','thr_angle','brake_pressure','brk_current','flag','engine_ctr','park_brk','load_brk','carrier_control','dumpbed_ctr','turn_light','gear_num','gear_cmd','gear_flag','gear_cleardriver','dipped_light','marker_light','brake_light','emer_light','trumpet','state_light','rest_off_ctr','lube_ctr','auto_cmd','override_cmd','light_ctr']
  _slot_types = ['char','float64','float64','int32','float32','float32','char','char','char','char','char','float32','char','int32','int32','int32','int32','char','char','char','char','char','char','char','char','char','char','char']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       static_check,steering_angle,steering_spd,thr_angle,brake_pressure,brk_current,flag,engine_ctr,park_brk,load_brk,carrier_control,dumpbed_ctr,turn_light,gear_num,gear_cmd,gear_flag,gear_cleardriver,dipped_light,marker_light,brake_light,emer_light,trumpet,state_light,rest_off_ctr,lube_ctr,auto_cmd,override_cmd,light_ctr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_v_control, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.static_check is None:
        self.static_check = 0
      if self.steering_angle is None:
        self.steering_angle = 0.
      if self.steering_spd is None:
        self.steering_spd = 0.
      if self.thr_angle is None:
        self.thr_angle = 0
      if self.brake_pressure is None:
        self.brake_pressure = 0.
      if self.brk_current is None:
        self.brk_current = 0.
      if self.flag is None:
        self.flag = 0
      if self.engine_ctr is None:
        self.engine_ctr = 0
      if self.park_brk is None:
        self.park_brk = 0
      if self.load_brk is None:
        self.load_brk = 0
      if self.carrier_control is None:
        self.carrier_control = 0
      if self.dumpbed_ctr is None:
        self.dumpbed_ctr = 0.
      if self.turn_light is None:
        self.turn_light = 0
      if self.gear_num is None:
        self.gear_num = 0
      if self.gear_cmd is None:
        self.gear_cmd = 0
      if self.gear_flag is None:
        self.gear_flag = 0
      if self.gear_cleardriver is None:
        self.gear_cleardriver = 0
      if self.dipped_light is None:
        self.dipped_light = 0
      if self.marker_light is None:
        self.marker_light = 0
      if self.brake_light is None:
        self.brake_light = 0
      if self.emer_light is None:
        self.emer_light = 0
      if self.trumpet is None:
        self.trumpet = 0
      if self.state_light is None:
        self.state_light = 0
      if self.rest_off_ctr is None:
        self.rest_off_ctr = 0
      if self.lube_ctr is None:
        self.lube_ctr = 0
      if self.auto_cmd is None:
        self.auto_cmd = 0
      if self.override_cmd is None:
        self.override_cmd = 0
      if self.light_ctr is None:
        self.light_ctr = 0
    else:
      self.static_check = 0
      self.steering_angle = 0.
      self.steering_spd = 0.
      self.thr_angle = 0
      self.brake_pressure = 0.
      self.brk_current = 0.
      self.flag = 0
      self.engine_ctr = 0
      self.park_brk = 0
      self.load_brk = 0
      self.carrier_control = 0
      self.dumpbed_ctr = 0.
      self.turn_light = 0
      self.gear_num = 0
      self.gear_cmd = 0
      self.gear_flag = 0
      self.gear_cleardriver = 0
      self.dipped_light = 0
      self.marker_light = 0
      self.brake_light = 0
      self.emer_light = 0
      self.trumpet = 0
      self.state_light = 0
      self.rest_off_ctr = 0
      self.lube_ctr = 0
      self.auto_cmd = 0
      self.override_cmd = 0
      self.light_ctr = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2di2f5BfB4i11B().pack(_x.static_check, _x.steering_angle, _x.steering_spd, _x.thr_angle, _x.brake_pressure, _x.brk_current, _x.flag, _x.engine_ctr, _x.park_brk, _x.load_brk, _x.carrier_control, _x.dumpbed_ctr, _x.turn_light, _x.gear_num, _x.gear_cmd, _x.gear_flag, _x.gear_cleardriver, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.trumpet, _x.state_light, _x.rest_off_ctr, _x.lube_ctr, _x.auto_cmd, _x.override_cmd, _x.light_ctr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 66
      (_x.static_check, _x.steering_angle, _x.steering_spd, _x.thr_angle, _x.brake_pressure, _x.brk_current, _x.flag, _x.engine_ctr, _x.park_brk, _x.load_brk, _x.carrier_control, _x.dumpbed_ctr, _x.turn_light, _x.gear_num, _x.gear_cmd, _x.gear_flag, _x.gear_cleardriver, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.trumpet, _x.state_light, _x.rest_off_ctr, _x.lube_ctr, _x.auto_cmd, _x.override_cmd, _x.light_ctr,) = _get_struct_B2di2f5BfB4i11B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2di2f5BfB4i11B().pack(_x.static_check, _x.steering_angle, _x.steering_spd, _x.thr_angle, _x.brake_pressure, _x.brk_current, _x.flag, _x.engine_ctr, _x.park_brk, _x.load_brk, _x.carrier_control, _x.dumpbed_ctr, _x.turn_light, _x.gear_num, _x.gear_cmd, _x.gear_flag, _x.gear_cleardriver, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.trumpet, _x.state_light, _x.rest_off_ctr, _x.lube_ctr, _x.auto_cmd, _x.override_cmd, _x.light_ctr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 66
      (_x.static_check, _x.steering_angle, _x.steering_spd, _x.thr_angle, _x.brake_pressure, _x.brk_current, _x.flag, _x.engine_ctr, _x.park_brk, _x.load_brk, _x.carrier_control, _x.dumpbed_ctr, _x.turn_light, _x.gear_num, _x.gear_cmd, _x.gear_flag, _x.gear_cleardriver, _x.dipped_light, _x.marker_light, _x.brake_light, _x.emer_light, _x.trumpet, _x.state_light, _x.rest_off_ctr, _x.lube_ctr, _x.auto_cmd, _x.override_cmd, _x.light_ctr,) = _get_struct_B2di2f5BfB4i11B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2di2f5BfB4i11B = None
def _get_struct_B2di2f5BfB4i11B():
    global _struct_B2di2f5BfB4i11B
    if _struct_B2di2f5BfB4i11B is None:
        _struct_B2di2f5BfB4i11B = struct.Struct("<B2di2f5BfB4i11B")
    return _struct_B2di2f5BfB4i11B
