(cl:in-package msg_info_router-msg)
(cl:export '(MODE-VAL
          MODE
          TASK_TYPE-VAL
          TASK_TYPE
          TASK_NUM-VAL
          TASK_NUM
          SEGMENTS_NUM-VAL
          SEGMENTS_NUM
          CUR_SEGMENTS_NUM-VAL
          CUR_SEGMENTS_NUM
          STATE_TYPE-VAL
          STATE_TYPE
          PATH_POINT-VAL
          PATH_POINT
          STOP_POINT-VAL
          STOP_POINT
          IS_UPDATE_MAP-VAL
          IS_UPDATE_MAP
          REMOTE_SPD-VAL
          REMOTE_SPD
          REMOTE_STEERING-VAL
          REMOTE_STEERING
          REMOTE_PARKING-VAL
          REMOTE_PARKING
          REMOTE_STOPENGINE-VAL
          REMOTE_STOPENGINE
          REMOTE_SERVICE_BRAKE-VAL
          REMOTE_SERVICE_BRAKE
          REMOTE_PARK_BRAKE-VAL
          REMOTE_PARK_BRAKE
          REMOTE_LOAD_BRAKE-VAL
          REMOTE_LOAD_BRAKE
          GEAR_NUM-VAL
          GEAR_NUM
          CARRIER_CONTROL-VAL
          CARRIER_CONTROL
          TURN_LIGHT-VAL
          TURN_LIGHT
          DIPPED_LIGHT-VAL
          DIPPED_LIGHT
          MARKER_LIGHT-VAL
          MARKER_LIGHT
          FOG_LIGHT-VAL
          FOG_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          EMER_LIGHT-VAL
          EMER_LIGHT
          WIPER_SIGN-VAL
          WIPER_SIGN
          TRUMPET-VAL
          TRUMPET
))