(cl:in-package msg_common-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          HEADING_ANGLE-VAL
          HEADING_ANGLE
          CURVATURE-VAL
          CURVATURE
          SPEED-VAL
          SPEED
          DISTANCE-VAL
          DISTANCE
          SLOPE-VAL
          SLOPE
          ATTRIBUTE-VAL
          ATTRIBUTE
          SPEED_LIMIT-VAL
          SPEED_LIMIT
          DIRECTION-VAL
          DIRECTION
          WAYPOINTATTR-VAL
          WAYPOINTATTR
          T-VAL
          T
          AREA_NAME-VAL
          AREA_NAME
          ONAREAID-VAL
          ONAREAID
))