// Generated by gencpp from file msg_obj_fuse/msg_obj_fuse.msg
// DO NOT EDIT!


#ifndef MSG_OBJ_FUSE_MESSAGE_MSG_OBJ_FUSE_H
#define MSG_OBJ_FUSE_MESSAGE_MSG_OBJ_FUSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_obj/Obj.h>
#include <msg_common/Time.h>

namespace msg_obj_fuse
{
template <class ContainerAllocator>
struct msg_obj_fuse_
{
  typedef msg_obj_fuse_<ContainerAllocator> Type;

  msg_obj_fuse_()
    : obj_fuse()
    , time()  {
    }
  msg_obj_fuse_(const ContainerAllocator& _alloc)
    : obj_fuse(_alloc)
    , time(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::msg_obj::Obj_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_obj::Obj_<ContainerAllocator> >> _obj_fuse_type;
  _obj_fuse_type obj_fuse;

   typedef  ::msg_common::Time_<ContainerAllocator>  _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> const> ConstPtr;

}; // struct msg_obj_fuse_

typedef ::msg_obj_fuse::msg_obj_fuse_<std::allocator<void> > msg_obj_fuse;

typedef boost::shared_ptr< ::msg_obj_fuse::msg_obj_fuse > msg_obj_fusePtr;
typedef boost::shared_ptr< ::msg_obj_fuse::msg_obj_fuse const> msg_obj_fuseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator1> & lhs, const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator2> & rhs)
{
  return lhs.obj_fuse == rhs.obj_fuse &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator1> & lhs, const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_obj_fuse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ee5de8b7831aa58e60b913c1ef61fe2";
  }

  static const char* value(const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ee5de8b7831aa58ULL;
  static const uint64_t static_value2 = 0xe60b913c1ef61fe2ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_obj_fuse/msg_obj_fuse";
  }

  static const char* value(const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_obj/Obj[] obj_fuse  \n"
"msg_common/Time time     #障碍物检测时间 2020-11-19 赵国春添加\n"
"\n"
"\n"
"================================================================================\n"
"MSG: msg_obj/Obj\n"
"float64 x #单位m\n"
"float64 y #单位m\n"
"float64 z #单位m\n"
"float32 vx #单位m/s\n"
"float32 vy #单位m/s\n"
"float32 vz #单位m/s\n"
"float32 width #宽度，单位m\n"
"float32 length #长度，单位m\n"
"float32 height #高度，单位m\n"
"#float64 yaw_angle #横摆脚，角度信息，单位为度\n"
"uint8 track_state #跟踪状态,0：删除或无效；1：新的；2：测量的；3：预测的；4：待删除；5：待跟踪\n"
"uint8 predict_length #预测时长， 单位s\n"
"int32 type #障碍物类型, 0:未知；1：汽车；2：卡车；3：行人；4：摩托车；5自行车；6：大障碍物；7：小障碍物； 8：矿坑； 9：灰尘\n"
"uint32 type_age #障碍物类型时间长度，单位s\n"
"float32 orientation #障碍物形状方位角，单位度，\n"
"float32 bbox_yaw\n"
"float32 bbox_pitch\n"
"float32 bbox_roll\n"
"float32 ax #x轴加速度，单位m/s^2\n"
"float32 ay #y轴加速度，单位m/s^2\n"
"float32 az #z轴加速度，单位m/s^2\n"
"msg_common/Covariance cov     #协方差\n"
"uint8 type_certainty #障碍物类型确信度 0-100\n"
"uint8 obj_certainty #障碍物存在确信度, 0:无效；1：小于0.25；2：小于0.5;3：小于0.75;4：小于0.9;5：小于0.99;6：小于0.999\n"
"int8 source #数据来源编号，预设的传感器编号\n"
"msg_common/GridPoint[] contour_point #obj对象包含的点信息\n"
"uint32 id #跟踪之后给出的最终obj的id\n"
"uint8 absolute_motion #绝对的运动状态，0：未知; 1：静止；2：运动\n"
"uint8 relative_motion #相对车辆的运动状态，0：静止；1:迎面而来；2：远去；3：横越；4:未知\n"
"float32 orientation_rate #方向角速度\n"
"\n"
"================================================================================\n"
"MSG: msg_common/Covariance\n"
"float32[] value #矩阵值\n"
"int8 row #协方差行\n"
"int8 col #协方差列\n"
"================================================================================\n"
"MSG: msg_common/GridPoint\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
"================================================================================\n"
"MSG: msg_common/Time\n"
"int32 sec #秒\n"
"int32 msec #毫秒\n"
;
  }

  static const char* value(const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_fuse);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_obj_fuse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_obj_fuse::msg_obj_fuse_<ContainerAllocator>& v)
  {
    s << indent << "obj_fuse[]" << std::endl;
    for (size_t i = 0; i < v.obj_fuse.size(); ++i)
    {
      s << indent << "  obj_fuse[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_obj::Obj_<ContainerAllocator> >::stream(s, indent + "    ", v.obj_fuse[i]);
    }
    s << indent << "time: ";
    s << std::endl;
    Printer< ::msg_common::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_OBJ_FUSE_MESSAGE_MSG_OBJ_FUSE_H
