# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_imu_prep/msg_imu_prep.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class msg_imu_prep(genpy.Message):
  _md5sum = "0fea41e4b55f2b301664a8d463d24fcb"
  _type = "msg_imu_prep/msg_imu_prep"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 acce_x		#惯性系下沿x轴加速度 
float32 acce_y		#惯性系下沿y轴加速度 
float32 acce_z		#惯性系下沿z轴加速度 
float32 pals_x		#惯性系下绕x轴角速度 
float32 pals_y		#惯性系下绕y轴角速度 
float32 pals_z		#惯性系下绕z轴角速度 
"""
  __slots__ = ['acce_x','acce_y','acce_z','pals_x','pals_y','pals_z']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acce_x,acce_y,acce_z,pals_x,pals_y,pals_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(msg_imu_prep, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.acce_x is None:
        self.acce_x = 0.
      if self.acce_y is None:
        self.acce_y = 0.
      if self.acce_z is None:
        self.acce_z = 0.
      if self.pals_x is None:
        self.pals_x = 0.
      if self.pals_y is None:
        self.pals_y = 0.
      if self.pals_z is None:
        self.pals_z = 0.
    else:
      self.acce_x = 0.
      self.acce_y = 0.
      self.acce_z = 0.
      self.pals_x = 0.
      self.pals_y = 0.
      self.pals_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.acce_x, _x.acce_y, _x.acce_z, _x.pals_x, _x.pals_y, _x.pals_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.acce_x, _x.acce_y, _x.acce_z, _x.pals_x, _x.pals_y, _x.pals_z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.acce_x, _x.acce_y, _x.acce_z, _x.pals_x, _x.pals_y, _x.pals_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.acce_x, _x.acce_y, _x.acce_z, _x.pals_x, _x.pals_y, _x.pals_z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
