(cl:in-package msg_gnss_prep-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          SPD_EAST-VAL
          SPD_EAST
          SPD_NORTH-VAL
          SPD_NORTH
          SPD_DOWN-VAL
          SPD_DOWN
          HEADING_ANGLE-VAL
          HEADING_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          YAW_RATE-VAL
          YAW_RATE
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          SPEED-VAL
          SPEED
          SPD_LON-VAL
          SPD_LON
          SPD_LAT-VAL
          SPD_LAT
          ACCE-VAL
          ACCE
          ACCE_LON-VAL
          ACCE_LON
          ACCE_LAT-VAL
          ACCE_LAT
          FLAG-VAL
          FLAG
          GPS_STATUS-VAL
          GPS_STATUS
))